import type { Story } from '../../types'

export const blackDeathEs: Story = {
  slug: 'black-death',
  title: 'El jornal de después',
  subtitle: '1346–1353 — mató quizá a la mitad de Europa en siete años, y los supervivientes acabaron mejor. Las dos mitades son la historia.',
  hook: 'La Peste Negra mató a entre un tercio y la mitad de toda Europa en siete años — y en una generación, quienes la sobrevivieron cobraban más de lo que sus padres habían ganado nunca.',
  era: 'medieval',
  category: 'eras',
  years: [1346, 1381],
  regions: ['Europa', 'Oriente Próximo', 'Asia central'],
  nodes: ['black-death', 'yersinia-pestis', 'feudalism', 'silk-road', 'plague-pogroms'],
  tags: ['plague', 'economics', 'labour', 'medicine', 'europe', 'legend'],
  readingMinutes: 11,
  reviewed: '2026-08-05',
  mood: 'noir',

  reel: [
    { beat: 'hook', punch: true, text: 'Mató a entre un tercio y la mitad de Europa en siete años.' },
    { beat: 'hook', text: 'Y quienes la sobrevivieron acabaron más ricos de lo que sus padres habían sido nunca.' },
    { beat: 'worldBefore', kicker: 'h. 1300', text: 'Europa está llena. La tierra se subdivide, las cosechas van justas, los jornales son bajos,' },
    { beat: 'worldBefore', text: 'y una hambruna en 1315 ya ha matado quizá a un décimo del norte.' },
    { beat: 'worldBefore', punch: true, text: 'Hay demasiada gente para la tierra, y no hay salida.' },
    { beat: 'problem', text: 'Y Eurasia nunca ha sido tan fácil de cruzar. Un imperio va de Hungría a Corea,' },
    { beat: 'problem', mark: 'web', text: 'así que se mueven caravanas, y barcos, y todo lo que llevan se mueve con ellos.' },
    { beat: 'problem', kicker: '1346', text: 'Algo llega a un puerto comercial genovés del mar Negro.' },
    { beat: 'story', kicker: 'Octubre de 1347', text: 'Doce galeras alcanzan Mesina, en Sicilia, con casi toda la tripulación muerta o muriéndose.' },
    { beat: 'story', text: 'La ciudad las expulsa. Es muchísimo más tarde; ya está en tierra.' },
    { beat: 'story', text: 'Génova en invierno. Marsella. París en verano. Inglaterra el junio siguiente.' },
    { beat: 'story', punch: true, mark: 'spike', text: 'Se mueve a la velocidad de una persona que viaja, porque viaja con personas.' },
    { beat: 'story', text: 'Un médico de Florencia escribe que los enfermos morían en tres días, y a menudo en uno.' },
    { beat: 'story', text: 'Nadie sabe qué es. Los mejores médicos de Europa culpan a la alineación de los planetas.' },
    { beat: 'story', punch: true, text: 'Así que la gente busca a quién culpar, y encuentra a sus vecinos.' },
    { beat: 'story', kicker: 'Estrasburgo, 1349', text: 'Cientos de comunidades judías son acusadas de envenenar pozos y destruidas.' },
    { beat: 'story', text: 'El papa señala, dos veces y por escrito, que los judíos también se están muriendo.' },
    { beat: 'story', punch: true, text: 'No cambia nada, porque la acusación nunca fue sobre pruebas.' },
    { beat: 'whyItHappened', text: 'Luego para, y Europa cuenta, y la aritmética se ha invertido en silencio.' },
    { beat: 'whyItHappened', text: 'La tierra sigue ahí. Los molinos siguen ahí. La mitad de los trabajadores no.' },
    { beat: 'whyItHappened', punch: true, mark: 'reversal', text: 'Por primera vez en siglos, lo escaso es la mano de obra.' },
    { beat: 'consequences', text: 'Suben los jornales. Bajan las rentas. Los siervos se van a mejores ofertas y no vuelven.' },
    { beat: 'consequences', kicker: '1351', text: 'Inglaterra prohíbe pagar más que los salarios de 1346.' },
    { beat: 'consequences', punch: true, text: 'La ley se persigue sin parar, en todas partes, treinta años — lo que dice que fracasó.' },
    { beat: 'consequences', text: 'En 1381 los jornaleros marchan sobre Londres, y la servidumbre no llega al siglo siguiente.' },
    { beat: 'whyItMatters', text: 'Nada de esto fue un lado bueno. Fue consecuencia de la escala de la muerte.' },
    { beat: 'whyItMatters', punch: true, text: 'Lo que hizo valiosos a los supervivientes fue que quedaban muy pocos.' },
  ],

  beats: {
    worldBefore: {
      heading: 'El mundo de antes',
      paragraphs: [
        'La Europa de 1300 estaba abarrotada. Tres siglos de crecimiento demográfico habían empujado a la gente a tierras marginales, subdividido las parcelas hasta hacerlas apenas viables y hundido los salarios reales hasta más o menos lo más bajo que estarían en quinientos años. Había quizá ochenta millones de personas y una tecnología agrícola capaz de alimentar aproximadamente a esas mismas en un año bueno.',
        'La Gran Hambruna de 1315-17 fue la primera señal de que los años buenos se habían acabado. La lluvia arruinó las cosechas del norte de Europa tres temporadas seguidas, y murió algo así como un décimo de la población de las zonas afectadas. Fue sobrevivible, y todo volvió a como estaba, que era: demasiada gente, poca tierra y salarios de subsistencia.',
        'Esto es lo que los economistas llaman una trampa maltusiana, y lo característico es que desde dentro no hay salida. Cualquier mejora del rendimiento se la come que sobrevivan más niños, y acabas otra vez en la subsistencia con más gente. Europa llevaba muchísimo tiempo atrapada ahí.',
        'El otro dato relevante del siglo XIV es que Eurasia nunca había sido tan fácil de cruzar. Las conquistas mongolas habían producido una autoridad única desde Hungría hasta Corea, y bajo ella las rutas terrestres estaban, por primera vez en siglos, lo bastante seguras para que los mercaderes las usaran de forma rutinaria. Factorías genovesas y venecianas se asentaban en la costa del mar Negro, en el extremo occidental de ese sistema.',
        'Por ahí se movían mercancías. Y también el papel, y la pólvora, y las historias, y —en la década de 1340— algo en el pelo de una marmota o en las pulgas de un saco de grano.',
      ],
      aside: {
        kind: 'analogy',
        label: 'Imagínalo',
        body: 'Imagina una economía donde lo único que sobra con creces son las personas. Lo que paga es la tierra; si eres dueño, pones las condiciones, y si no lo eres, las aceptas. Todas las instituciones de la Europa medieval —la servidumbre, las restricciones gremiales, las rentas de la tierra— se apoyaban en el supuesto de que a un trabajador siempre se lo puede reemplazar. En 1348 ese supuesto dejó de ser cierto, y nada estaba diseñado para eso.',
      },
      sourceIds: ['herlihy-1997', 'benedictow-2004'],
    },

    problem: {
      heading: 'El problema',
      paragraphs: [
        'La enfermedad era la peste, causada por la bacteria *Yersinia pestis*. Esa frase se discutió durante décadas y hoy está tan asentada como casi cualquier cosa en historia medieval: en 2011 un equipo recuperó y reconstruyó un borrador del genoma de *Y. pestis* a partir de los dientes de víctimas enterradas en el cementerio de emergencia de East Smithfield, en Londres, abierto en 1348 precisamente para los muertos de esta epidemia.',
        'En 2022 otro equipo fue más atrás y secuenció genomas de peste de un cementerio cercano al lago Issyk-Kul, en Kirguistán, donde las sepulturas de 1338-39 llevan una fórmula insólita: que el difunto murió de pestilencia. Esas cepas se sitúan exactamente en el punto del árbol genealógico de la bacteria del que desciende la pandemia del siglo XIV. Es la mejor prueba hasta ahora de dónde vino.',
        'Lo que está mucho menos resuelto es cómo se propagó, y eso importa más de lo que parece. El modelo de manual son las ratas y sus pulgas: la bacteria circula entre roedores, las pulgas pican a los humanos cuando mueren las ratas, y la enfermedad sigue a la población de ratas. Eso encaja con la forma bubónica y con los brotes de peste en la India que se estudiaron al detalle hacia 1900.',
        'Con la Peste Negra encaja bastante peor. Esta epidemia se movió demasiado rápido, se propagó en invierno, atravesó regiones sin poblaciones significativas de ratas y mató a unas tasas que el modelo de la rata tiene dificultades para producir. Trabajos recientes de modelización sostienen que los ectoparásitos humanos —la pulga humana y el piojo del cuerpo— encajan mucho mejor con el patrón observado, y que la transmisión de persona a persona hacía casi todo el trabajo.',
        'De un modo u otro, una cosa era cierta y es todo el horror del asunto: nadie de entonces tenía ni idea. La facultad de medicina de la Universidad de París, a la que el rey pidió una explicación, produjo un informe que atribuía la peste a una conjunción de Saturno, Júpiter y Marte en el signo de Acuario el 20 de marzo de 1345.',
      ],
      aside: {
        kind: 'caution',
        label: 'Con cuidado',
        body: 'Que el patógeno fuera *Yersinia pestis* está establecido por ADN antiguo. Cómo se transmitió a la escala y la velocidad observadas es una cuestión genuinamente abierta, y el modelo rata-pulga que aparece en la mayoría de los manuales está seriamente cuestionado. Son dos preguntas distintas y el atlas las mantiene separadas.',
        sourceId: 'bos-2011',
      },
      sourceIds: ['bos-2011', 'spyrou-2022', 'benedictow-2004'],
    },

    story: {
      heading: 'La historia',
      paragraphs: [
        'En 1346 la peste apareció en Caffa, una colonia comercial genovesa de Crimea, durante un asedio de la Horda de Oro. Un notario de Piacenza llamado Gabriele de’ Mussis escribió después que los sitiadores catapultaron a sus propios muertos por encima de las murallas, y desde entonces se ha contado como el primer uso registrado de guerra biológica. Puede que ocurriera. De’ Mussis no estaba allí, y la peste iba a llegar al Mediterráneo por barco de todas maneras.',
        'En octubre de 1347, doce galeras entraron en el puerto de Mesina, en Sicilia, con casi todos los hombres a bordo muertos o muriéndose. La ciudad ordenó que salieran. No sirvió de nada; el puerto estaba infectado desde el momento en que amarraron. De Sicilia pasó a Génova y Venecia, a Marsella en el invierno de 1347, por Francia durante la primavera, a París en junio de 1348, a Inglaterra ese mismo mes, a Escandinavia en 1349 y a Rusia en 1351 — llegando, por fin, desde el oeste, tras haber dado toda la vuelta.',
        'Viajaba más o menos a la velocidad del movimiento humano: unos dos a cuatro kilómetros al día por tierra, y a velocidad de barco por las costas. Eso, más que ninguna otra cosa, es lo que identifica algo que la gente estaba llevando encima.',
        'Los síntomas en la forma bubónica eran hinchazones —bubones— en la ingle, la axila o el cuello, con fiebre y manchas negras o moradas, y muerte normalmente en tres a cinco días. Había también una forma neumónica, en los pulmones, que se contagiaba al toser, mataba en uno o dos días y mataba a casi todo el que tocaba.',
        'Los relatos de la época convergen en los mismos detalles, en países distintos y de plumas distintas: la velocidad, el olor, el abandono. Boccaccio, que estaba en Florencia en 1348, describe gente que desayunaba con su familia y cenaba con sus antepasados, hermanos abandonando a hermanos y —el detalle que se repite en todas partes— cadáveres en la calle que nadie quería mover por ningún precio.',
        'Las estimaciones de mortalidad se han revisado al alza en la última generación. La vieja cifra de un tercio venía de datos ingleses limitados. Ole Benedictow, repasando registros locales de toda Europa, defiende alrededor del sesenta por ciento. La mayoría de los historiadores usa hoy un rango de un tercio a la mitad, con regiones mucho peores y unas pocas —Milán, partes de Polonia y Bohemia— en gran medida a salvo por razones que nadie entiende del todo.',
        'Y luego está lo que hizo la gente mientras ocurría. Sin explicación disponible, algunos concluyeron que se habían envenenado los pozos. Entre 1348 y 1351 comunidades judías de Renania y más allá fueron acusadas, torturadas hasta confesar y destruidas: Basilea, Estrasburgo, Maguncia, Colonia, Erfurt, Bruselas y cientos de lugares menores. En Estrasburgo, el 14 de febrero de 1349, unos dos mil judíos fueron quemados en el cementerio judío de la ciudad. La peste todavía no había llegado a Estrasburgo.',
        'El papa Clemente VI publicó dos bulas, en julio y septiembre de 1348, condenando las matanzas y señalando que los judíos morían de la peste en la misma proporción que los demás. Lo ignoraron. Allí donde se destruían comunidades, sus deudas solían cancelarse y sus bienes repartirse, que es la parte que sugiere que la acusación hacía un trabajo distinto del de explicar.',
      ],
      aside: {
        kind: 'voice',
        label: 'Una voz de la época',
        body: 'Boccaccio, escribiendo en Florencia uno o dos años después de la epidemia, describe una ciudad donde los ritos habituales de la muerte simplemente se pararon: los moribundos dejados solos, funerales sin dolientes, y cadáveres sacados y dejados a la puerta de las casas en tal número que los vivos pasaban por encima. No está escribiendo historia. Está escribiendo lo que acababa de ver.',
        sourceId: 'boccaccio-1353',
      },
      sourceIds: ['boccaccio-1353', 'de-mussis-1348', 'clement-vi-1348', 'benedictow-2004'],
    },

    whyItHappened: {
      heading: 'Por qué se enriquecieron los supervivientes',
      paragraphs: [
        'Aquí viene la parte genuinamente contraintuitiva, y es aritmética antes que consuelo.',
        'Una pandemia mata personas. No destruye campos, molinos, arados, edificios, caminos ni ganado — a diferencia de una guerra, que destruye todo eso. Así que al otro lado de la Peste Negra, Europa tenía más o menos el mismo capital y la misma tierra que antes, y entre un tercio y la mitad menos de gente para trabajarlos.',
        '**La tierra pasó a sobrar y la mano de obra a faltar.** Los campos marginales, los que apenas compensaba cultivar cuando había demasiadas bocas, quedaron fuera de cultivo, y todo el mundo trabajó la buena tierra. La producción por persona subió porque se abandonó lo peor.',
        '**Lo que significaba que los trabajadores podían negociar.** Los salarios reales en Inglaterra prácticamente se duplicaron en el siglo siguiente y se mantuvieron altos doscientos años. Un jornalero podía rechazar una oferta e irse al pueblo de al lado, donde alguien le pagaría lo que pedía, porque todo el mundo necesitaba manos.',
        '**Y la maquinaria legal de la servidumbre dejó de funcionar.** La servidumbre depende de que el trabajador no tenga adónde ir. Cuando todas las haciendas del país andan cortas de brazos y contratan discretamente a los fugados, un señor que insista en sus derechos antiguos se encuentra con la tierra vacía. En Europa occidental la servidumbre se desvaneció en aproximadamente un siglo, no porque nadie la aboliera sino porque dejó de ser exigible.',
        'Los gobiernos entendían perfectamente lo que pasaba e intentaron pararlo. Inglaterra aprobó la Ordenanza de los Trabajadores en 1349 y el Estatuto de los Trabajadores en 1351, fijando los salarios en los niveles de 1346 y convirtiendo en delito exigir o pagar más. Las actas de aplicación son abundantes, y eso es precisamente la prueba de que no funcionó: una ley que se cumple no necesita treinta años de procesos.',
        'Lo que sí produjo fue una generación de jornaleros con más dinero y un Estado empeñado, a la vista de todos, en quitárselo. En 1381, tras un tercer impuesto de capitación, marcharon sobre Londres, mataron al arzobispo de Canterbury y al tesorero real y exigieron el fin de la servidumbre sin más. La revuelta fue aplastada y sus cabecillas ejecutados. La servidumbre murió igual, en el siglo siguiente, de economía.',
      ],
      sourceIds: ['herlihy-1997', 'statute-of-labourers-1351', 'benedictow-2004'],
    },

    consequences: {
      heading: 'Qué cambió',
      paragraphs: [
        'Es el mayor acontecimiento demográfico de la historia europea, y casi nada volvió a tener el mismo aspecto.',
      ],
      shortTerm: [
        'Entre un tercio y la mitad de la población de Europa murió entre 1347 y 1353: quizá de veinticinco a cincuenta millones de personas sobre unos ochenta millones.',
        'Cientos de comunidades judías fueron destruidas en matanzas entre 1348 y 1351, la mayoría concentradas en Renania y muchas veces antes incluso de que llegara la peste.',
        'El movimiento flagelante se extendió por Alemania y los Países Bajos, marchando de ciudad en ciudad y azotándose, hasta que Clemente VI lo condenó en octubre de 1349.',
        'Alrededor de una quinta parte de las aldeas inglesas quedó abandonada del todo en las décadas siguientes, y sus contornos siguen viéndose hoy marcados en los campos.',
        'Los salarios empezaron a subir de inmediato, y los gobiernos de toda Europa legislaron para impedirlo.',
      ],
      longTerm: [
        'Los salarios reales en Inglaterra prácticamente se duplicaron y siguieron altos hasta el siglo XVI. Fue el mejor momento para ser jornalero en Europa hasta la era industrial.',
        'La servidumbre desapareció en la práctica en Europa occidental durante el siglo siguiente — mientras que en Europa oriental, donde los señores eran políticamente más fuertes, se endureció. El mismo golpe produjo resultados opuestos según quién tuviera el poder.',
        'La escasez de mano de obra empujó a los empleadores hacia cualquier cosa que ahorrara trabajo: molinos de agua, mejores arados, después la imprenta. El argumento de Herlihy es que la peste rompió un bloqueo maltusiano y llevó a Europa a una senda de salarios más altos y más intensiva en capital.',
        'La deferencia hacia la autoridad quedó dañada de forma duradera. La Iglesia había rezado, procesionado y enterrado a sus propios curas en cantidades enormes, y los médicos universitarios habían culpado a los planetas. Ninguno de los dos recuperó del todo su antiguo prestigio.',
        'La peste no se fue. Volvió aproximadamente cada generación durante trescientos años —Milán en 1630, Londres en 1665, Marsella en 1720— antes de retirarse por fin de Europa.',
      ],
      unexpected: [
        'La mejor prueba de dónde empezó viene de dos cementerios de Kirguistán, con lápidas fechadas en 1338 y 1339 que registran muertes por pestilencia, y las bacterias recuperadas de las tumbas se sitúan en la raíz del árbol genealógico de la pandemia.',
        'El Estatuto de los Trabajadores de 1351 es una de las primeras leyes de control salarial de la historia inglesa, y el volumen de procesos bajo ella es nuestra mejor prueba de cuánto habían subido los salarios.',
        'En muchos lugares las matanzas de comunidades judías ocurrieron antes de que llegara la peste, lo que significa que no fueron una reacción a muertes locales sino a la noticia de que las muertes venían.',
        'Como tanta riqueza la heredaron tan pocos supervivientes, una generación de familias corrientes se encontró inesperadamente rica, y el mercado del lujo, el arte y la construcción en Italia se expandió en lugar de hundirse.',
        'El inglés se convirtió en la lengua de los tribunales y del parlamento ingleses en las décadas posteriores a la peste. Una explicación propuesta es que la élite francófona perdió a una proporción desmedida de los suyos, y a sus hijos los criaron supervivientes de habla inglesa.',
      ],
      sourceIds: ['herlihy-1997', 'spyrou-2022', 'statute-of-labourers-1351'],
    },

    whyItMatters: {
      heading: 'Por qué sigue importando',
      paragraphs: [
        'La Peste Negra es el caso más claro de la historia de una catástrofe que cambia la estructura de una sociedad en vez de solo dañarla — y el mecanismo no es moral, es aritmético.',
        'Nada de la peste fue constructivo. Mató a decenas de millones de personas con dolor, en siete años, y los supervivientes lo vieron. Lo que vino después ocurrió *por* la escala de la muerte y no a pesar de ella: la tierra y las herramientas sobreviven a una epidemia y las personas no, así que la proporción entre ambas se invierte y todo lo construido sobre la proporción antigua entra en tensión a la vez. La servidumbre, la ley salarial, el precio del pan, el equilibrio entre terrateniente y jornalero: todo se movió porque se había movido la aritmética de debajo.',
        'Conviene sostener eso con cuidado, porque la historia es facilísima de contar mal. Esto no es «no hay mal que por bien no venga». Es casi lo contrario: los supervivientes consiguieron un trato mejor solo en proporción a cuántos vecinos habían muerto, y en cuanto la población se recuperó en el siglo XVI, los salarios volvieron a caer.',
        'Lo segundo que hay que retener es lo que hizo la gente con un desastre inexplicado. Sin una causa sobre la que actuar, muchísimas comunidades se fijaron en una que sí tenían a mano — y las matanzas de 1348-49 precedieron con frecuencia a la llegada de la peste, lo que significa que fueron una respuesta al miedo y no a la pérdida. El papa les dijo por escrito que no tenía sentido. Dio igual, porque la explicación no era el objetivo.',
        'Y lo tercero es que el mismo golpe produjo el hundimiento de la servidumbre en el oeste y su endurecimiento en el este. Eso no lo decidió la peste. Lo decidió el poder relativo de señores y campesinos en cada sitio. Un desastre no tiene política propia; aplica presión, y el orden existente decide por dónde se rompen las cosas.',
      ],
      sourceIds: ['herlihy-1997', 'benedictow-2004'],
    },
  },

  timeline: [
    { year: 1315, title: 'La Gran Hambruna', detail: 'Tres años de cosechas arruinadas en el norte de Europa matan quizá a un décimo de la población, y demuestran el poco margen que tiene el sistema.' },
    { year: 1338, title: 'Muertes por pestilencia cerca de Issyk-Kul', detail: 'Las lápidas de un cementerio del actual Kirguistán recogen una causa de muerte insólita. Los genomas de peste recuperados allí están en la raíz de la pandemia.', pivotal: true, confidence: 'contested' },
    { year: 1346, title: 'La peste en Caffa', detail: 'Aparece en una colonia comercial genovesa de Crimea durante un asedio. La historia de los cadáveres catapultados viene de un autor que no estaba allí.', pivotal: true },
    { year: 1347, date: '1347-10', title: 'Doce galeras llegan a Mesina', detail: 'Entran en Sicilia con casi toda la tripulación muerta o muriéndose. La ciudad las expulsa demasiado tarde: el puerto ya está infectado.', pivotal: true },
    { year: 1348, title: 'Por todo el continente', detail: 'Génova y Venecia en invierno, Marsella, luego Francia durante la primavera, París en junio e Inglaterra ese mismo mes.', pivotal: true },
    { year: 1348, title: 'Clemente VI defiende a las comunidades judías', detail: 'Dos bulas papales condenan las matanzas y señalan que los judíos mueren de peste en la misma proporción que los demás. No cambian nada.', pivotal: true },
    { year: 1349, date: '1349-02-14', title: 'La matanza de Estrasburgo', detail: 'Unos dos mil judíos son quemados en el cementerio de la ciudad, acusados de envenenar los pozos. La peste todavía no ha llegado a Estrasburgo.', pivotal: true },
    { year: 1349, title: 'La Ordenanza de los Trabajadores', detail: 'Con los trabajadores exigiendo más paga, Inglaterra convierte en delito pedir u ofrecer más de los salarios anteriores a la peste.' },
    { year: 1351, title: 'El Estatuto de los Trabajadores', detail: 'El Parlamento convierte en ley la congelación salarial. Los procesos duran décadas, que es la prueba de que los salarios subieron igualmente.', pivotal: true },
    { year: 1353, title: 'Termina la primera oleada', detail: 'La pandemia remite tras llegar a Rusia desde el oeste. Entre un tercio y la mitad de Europa ha muerto en unos siete años.', pivotal: true },
    { year: 1381, title: 'La revuelta campesina', detail: 'Tras un tercer impuesto de capitación, los jornaleros ingleses marchan sobre Londres y exigen el fin de la servidumbre. La revuelta es aplastada; la servidumbre se apaga igual.', pivotal: true },
    { year: 1665, title: 'La Gran Peste de Londres', detail: 'Uno de los últimos grandes brotes europeos. La enfermedad volvió aproximadamente cada generación durante tres siglos después de 1353.' },
    { year: 2011, title: 'El genoma de East Smithfield', detail: 'Se reconstruye un borrador del genoma de Yersinia pestis a partir de dientes de víctimas de un cementerio londinense abierto en 1348, y se zanja qué era la enfermedad.', pivotal: true },
  ],

  causeEffect: [
    { cause: 'Tres siglos de crecimiento demográfico llenan Europa', effect: 'Los salarios caen a la subsistencia y la tierra se subdivide', because: 'Cuando la mano de obra abunda frente a la tierra, quien posee tierra pone las condiciones y los demás las aceptan.' },
    { cause: 'Las conquistas mongolas unifican Eurasia', effect: 'Las rutas terrestres vuelven a ser utilizables', because: 'Una sola autoridad de Hungría a Corea permitía cruzar sin negociar con una docena de potencias hostiles.' },
    { cause: 'Las rutas llevan mercancías más rápido y más lejos', effect: 'Una bacteria llega al mar Negro', because: 'La peste circula entre roedores de Asia central, y un roedor o sus pulgas viajan muy bien dentro de un saco de grano.' },
    { cause: 'La enfermedad se propaga con personas y no solo con ratas', effect: 'Se mueve a la velocidad del viaje humano', because: 'Dos a cuatro kilómetros al día por tierra y velocidad de barco por mar es la firma de algo que se transporta, no de algo que repta.' },
    { cause: 'Nadie puede explicar la causa', effect: 'Las comunidades se inventan una y matan a sus vecinos', because: 'Una catástrofe inexplicada es insoportable, y una acusación con deudas de por medio le resultaba útil a más de una parte.' },
    { cause: 'Muere entre un tercio y la mitad de la mano de obra', effect: 'La tierra sobra y el trabajo escasea', because: 'La peste mata personas y deja en pie campos, molinos y arados, así que la proporción entre ambos se invierte de un día para otro.' },
    { cause: 'El trabajo escasea', effect: 'Los salarios reales se duplican y la servidumbre cae en el oeste', because: 'Un trabajador que puede irse a la hacienda de al lado y ser contratado tiene poder, y la servidumbre depende de que no haya adónde ir.' },
    { cause: 'Los gobiernos legislan para congelar los salarios', effect: 'Treinta años de procesos y al final una revuelta', because: 'Una ley contra la economía solo es aplicable a un coste, y aquí el coste fue la lealtad de todos aquellos a quienes se aplicó.' },
  ],

  myths: [
    {
      myth: 'La Peste Negra mató a un tercio de Europa.',
      reality: 'Un tercio era la estimación antigua, basada sobre todo en registros eclesiásticos ingleses. El trabajo con un abanico mucho más amplio de fuentes locales ha empujado las cifras al alza: Benedictow defiende alrededor del sesenta por ciento, y hoy la mayoría usa un rango de un tercio a la mitad, señalando gran variación regional. Lo honesto es un rango, no una cifra.',
      whyItPersists: 'La cifra de un tercio estuvo un siglo en los manuales, y es más fácil recordar un número que un rango con una salvedad regional colgando.',
      sourceIds: ['benedictow-2004'],
    },
    {
      myth: 'La propagaron las ratas y sus pulgas.',
      reality: 'El patógeno es sin duda *Yersinia pestis*, confirmado por ADN de enterramientos del siglo XIV. Pero el modelo rata-pulga viene de estudiar la peste en la India hacia 1900, y encaja mal con esta pandemia: la Peste Negra se movió demasiado rápido, se propagó en invierno y llegó a regiones con pocas ratas. Trabajos recientes sostienen que las pulgas humanas y los piojos del cuerpo —de persona a persona— explican mejor el patrón observado.',
      whyItPersists: 'La rata está en todos los manuales y en todas las ilustraciones, y la corrección es reciente, técnica y menos vistosa que una rata.',
      sourceIds: ['bos-2011', 'benedictow-2004'],
    },
    {
      myth: 'Los mongoles inventaron la guerra biológica catapultando apestados dentro de Caffa.',
      reality: 'La historia viene de Gabriele de’ Mussis, un notario de Piacenza que no estaba presente y lo escribió después. Puede ser cierta. Y tampoco hace falta para explicar nada: la peste se movía por las rutas comerciales y habría llegado a los puertos mediterráneos por barco de todos modos.',
      whyItPersists: 'Es una imagen sobrecogedora y le da a una catástrofe amorfa un autor humano deliberado, cosa que las historias prefieren.',
      sourceIds: ['de-mussis-1348', 'benedictow-2004'],
    },
    {
      myth: 'Los médicos llevaban las máscaras con pico durante la Peste Negra.',
      reality: 'La máscara con pico la diseñó Charles de Lorme en la década de 1610 —más de doscientos cincuenta años después— para brotes posteriores, y aun entonces su uso fue limitado. Nadie llevaba una en 1348.',
      whyItPersists: 'Es la imagen más reconocible asociada a la peste, y las imágenes viajan hacia atrás en el tiempo con mucha más facilidad que las fechas.',
      sourceIds: ['benedictow-2004'],
    },
  ],

  disagreements: [
    {
      question: '¿Cómo se transmitió realmente la peste?',
      positions: [
        { view: 'Clásicamente, por pulgas de rata: la bacteria circula entre roedores y las pulgas pasan a los humanos cuando mueren las ratas. Es el modelo derivado de los brotes indios estudiados hacia 1900.', heldBy: 'El relato epidemiológico tradicional', sourceId: 'benedictow-2004' },
        { view: 'Sobre todo por ectoparásitos humanos —pulgas humanas y piojos del cuerpo— de persona a persona. Eso explica mejor la velocidad, la propagación invernal y las regiones con pocas ratas.', heldBy: 'Trabajos recientes de modelización sobre las curvas de mortalidad', sourceId: 'bos-2011' },
      ],
      atlasPosition: 'El atlas afirma que el patógeno fue *Yersinia pestis*, cosa que ha zanjado el ADN antiguo, y trata la vía de transmisión como una cuestión abierta con el modelo rata-pulga seriamente cuestionado. No narra a las ratas como mecanismo establecido.',
    },
    {
      question: '¿Cuánta gente murió?',
      positions: [
        { view: 'Alrededor de un tercio de Europa: la estimación de siempre, extraída sobre todo de registros eclesiásticos ingleses.', heldBy: 'El consenso más antiguo', sourceId: 'herlihy-1997' },
        { view: 'Más cerca del sesenta por ciento, a partir de un repaso sistemático de registros locales de toda Europa y no de unas pocas regiones bien documentadas.', heldBy: 'Ole Benedictow', sourceId: 'benedictow-2004' },
      ],
      atlasPosition: 'El atlas usa «entre un tercio y la mitad» como rango de trabajo, recoge la cifra más alta de Benedictow y señala la gran variación regional. No presenta ningún porcentaje concreto como establecido.',
    },
    {
      question: '¿Causó la peste la transformación económica posterior?',
      positions: [
        { view: 'Sí, de forma decisiva. Rompió un bloqueo maltusiano, invirtió la proporción entre tierra y trabajo, duplicó los salarios reales, acabó con la servidumbre occidental y empujó a Europa hacia tecnología que ahorra trabajo.', heldBy: 'David Herlihy', sourceId: 'herlihy-1997' },
        { view: 'Fue un golpe potente cuyos efectos dependieron por completo de las estructuras políticas locales: el mismo hundimiento demográfico endureció la servidumbre en el este mientras la disolvía en el oeste.', heldBy: 'La literatura comparada de historia económica', sourceId: 'benedictow-2004' },
      ],
      atlasPosition: 'El atlas sostiene las dos: el golpe demográfico creó la presión, y las relaciones de poder existentes decidieron por dónde se rompía cada región. No presenta el resultado occidental como el natural ni el inevitable.',
    },
  ],

  didYouKnow: [
    'La peste mata personas y deja en pie campos, molinos y arados, y por eso a los supervivientes les tocó más capital por cabeza, y por eso subieron los salarios.',
    'Inglaterra convirtió en delito en 1351 pagar o aceptar más que los salarios de 1346. Se persiguió durante treinta años, que es como sabemos que fracasó.',
    'Los salarios reales en Inglaterra prácticamente se duplicaron tras la peste y siguieron altos dos siglos. Fue el mejor momento para ser jornalero hasta la era industrial.',
    'En muchas ciudades las matanzas de comunidades judías ocurrieron antes de que llegara la peste: una reacción a la noticia, no a las muertes locales.',
    'El papa Clemente VI publicó dos bulas en 1348 señalando que los judíos morían de peste en la misma proporción que todos los demás. No cambió nada.',
    'La máscara con pico se inventó en la década de 1610, más de doscientos cincuenta años después de la Peste Negra.',
    'La enfermedad quedó identificada sin discusión en 2011, a partir del ADN de los dientes de unas víctimas enterradas en un cementerio londinense abierto en 1348.',
    'El mismo hundimiento demográfico acabó con la servidumbre en Europa occidental y la endureció en la oriental. La diferencia fue quién tenía el poder político.',
  ],

  lenses: [
    {
      id: 'one-minute',
      label: 'En un minuto',
      kind: 'length',
      paragraphs: [
        'La Europa de 1300 estaba superpoblada, con salarios cerca de la subsistencia y sin salida de la trampa. Mientras tanto las conquistas mongolas habían vuelto utilizables las rutas comerciales eurasiáticas, y en 1346 la peste llegó a una colonia genovesa del mar Negro.',
        'En octubre de 1347 doce galeras llegaron a Mesina con casi toda la tripulación muerta. Desde Sicilia la enfermedad cruzó Europa en unos seis años —París en junio de 1348, Inglaterra ese mismo mes, Rusia en 1351— viajando a la velocidad del movimiento humano. Murió entre un tercio y la mitad de la población. Nadie sabía qué era; la Universidad de París culpó a una conjunción planetaria.',
        'Sin explicación disponible, cientos de comunidades judías fueron acusadas de envenenar los pozos y destruidas, muchas veces antes incluso de que llegara la peste. El papa condenó las matanzas por escrito, dos veces, y lo ignoraron.',
        'Y entonces la aritmética se invirtió. La peste mata personas pero deja intactas la tierra, los molinos y las herramientas, así que la mano de obra escaseó por primera vez en siglos. Los salarios prácticamente se duplicaron, la servidumbre dejó de ser exigible en Europa occidental, e Inglaterra se pasó treinta años procesando gente bajo una ley que congelaba los salarios en el nivel de 1346. En 1381 los jornaleros marcharon sobre Londres. La servidumbre murió igual: de economía.',
      ],
    },
    {
      id: 'age-10',
      label: 'Explícamelo como si tuviera 10 años',
      kind: 'age',
      paragraphs: [
        'En la década de 1340 llegó a Europa una enfermedad y mató a entre un tercio y la mitad de todo el mundo. No a un tercio de un pueblo: a un tercio de todos, en unos siete años. Es lo peor que le ha pasado nunca a Europa.',
        'Nadie sabía qué la causaba. Los médicos más listos de Francia dijeron que era porque los planetas se habían alineado mal. Y cuando la gente no puede explicar algo terrible, algunos empiezan a culpar a otras personas: se acusó a comunidades judías de toda Alemania de envenenar los pozos, y asesinaron a miles, a veces antes incluso de que la enfermedad hubiera llegado a su ciudad.',
        'Y ahora la parte rara. Cuando aquello paró, los que seguían vivos fueron poco a poco viviendo mejor de lo que habían vivido sus padres.',
        'Piensa por qué. La enfermedad mataba gente, pero no quemaba los campos, ni rompía los molinos, ni mataba a las ovejas. Así que después había la misma cantidad de tierra y de cosas, y solo la mitad de gente para repartirlas. Si eras trabajador, de repente todo el mundo te necesitaba, y podías decir «págame más o me voy a trabajar al pueblo de al lado».',
        'El gobierno de Inglaterra llegó a prohibir por ley pagar más a la gente. Se pasaron treinta años llevando a gente a juicio por eso, y no funcionó, porque eso no se puede parar una vez que ha empezado.',
        'Es importante no llamar a esto un final feliz. Solo fue mejor para los supervivientes porque había muerto muchísima gente.',
      ],
    },
    {
      id: 'scholar',
      label: 'Nivel universitario',
      kind: 'age',
      paragraphs: [
        'La cuestión etiológica está cerrada. Bos et al. (2011) reconstruyeron un borrador del genoma de *Y. pestis* procedente de East Smithfield, y trabajos posteriores lo han confirmado y ampliado; Spyrou et al. (2022) sitúan la población de origen de la politomía en la región del Tian Shan mediante genomas de Kara-Djigach, fechados por inscripciones en 1338-39. La posición revisionista de Twigg y Cohn de que la Peste Negra no era peste ya no es sostenible ante la prueba molecular, aunque las objeciones epidemiológicas de Cohn conservan fuerza como objeciones al *modelo de transmisión* y no al patógeno.',
        'Esa cuestión de la transmisión es la viva. El modelo clásico rata-*Xenopsylla cheopis*, derivado de la Tercera Pandemia en la India, genera curvas de mortalidad y velocidades de difusión espacial que encajan mal con la evidencia del siglo XIV: las velocidades observadas, la transmisión invernal y la difusión por zonas con poca presencia de *Rattus* son difíciles de acomodar. La modelización compartimental que compara los modelos de rata, de ectoparásito humano y neumónico frente a series de mortalidad de varias ciudades europeas favorece la transmisión por ectoparásitos humanos en la mayoría, con implicaciones sustanciales para cómo se leen las cifras de mortalidad.',
        'En demografía, la revisión al alza de Benedictow hasta cerca del 60 por ciento se apoya en agregar estudios locales en vez de extrapolar desde la bien documentada serie clerical inglesa, y se le ha criticado el sesgo de selección en qué localidades producen registros utilizables. El rango prudente sigue siendo de un tercio a la mitad con alta varianza regional, y la varianza es en sí misma el dato interesante.',
        'La historiografía económica gira en torno a la tesis de Herlihy: la peste como choque exógeno que libera un equilibrio maltusiano, eleva el producto marginal del trabajo, duplica los salarios reales e induce cambio técnico ahorrador de trabajo. La prueba más fuerte es la divergencia entre Europa occidental y oriental bajo un choque demográfico idéntico —la consolidación de la *Gutsherrschaft* al este del Elba frente a la disolución de la villanía en Inglaterra—, que indica que los desplazamientos en la proporción de factores están mediados por la distribución previa de la capacidad coercitiva. La formulación de Brenner sigue siendo el encuadre estándar del debate.',
        'Por último, las persecuciones de 1348-49 merecen tratarse con sus propios criterios probatorios. Su frecuente precedencia temporal respecto a la llegada local de la peste, y la cancelación correlativa de deudas y redistribución de bienes, argumentan contra una explicación de pánico puramente epidemiológico y a favor de modelos que incorporen relaciones de crédito previas y política municipal.',
      ],
    },
    {
      id: 'the-arithmetic',
      label: 'Por qué los supervivientes cobraron más',
      kind: 'angle',
      paragraphs: [
        'La economía de esto se hace en un papel, y explica casi todo lo que vino después.',
        '**Empieza por lo que destruye una peste.** Personas. Esa es la lista. Los campos siguen ahí en primavera. Los molinos siguen girando. Los arados, los graneros, las ovejas, los caminos, las murallas: todo sobrevive. Eso es lo que distingue una epidemia de una guerra, que destruye el capital y las personas a la vez.',
        '**Ahora la proporción.** Antes de 1347, Europa tenía muchísima mano de obra y una cantidad fija de buena tierra, así que la tierra era el factor escaso y los propietarios se quedaban el excedente. Después de 1353, la misma tierra tenía entre un tercio y la mitad menos de gente trabajándola. El factor escaso pasó a ser el trabajo. Quien tiene el factor escaso pone el precio.',
        '**Y el efecto de segundo orden.** Con menos gente, se abandonó la peor tierra: las parcelas marginales que solo se cultivaban porque no había alternativa. Todo el mundo trabajó la buena. Así que la producción por trabajador subió también, lo que significa que de verdad había más que repartir por cabeza, y no solo una redistribución.',
        '**Y el derrumbe institucional.** La servidumbre es un arreglo legal que solo funciona si el siervo no puede irse. Cuando todas las haciendas del país están desesperadas por brazos y contratan discretamente a quien aparezca, el arreglo deja de ser exigible, diga lo que diga la ley. Las leyes salariales inglesas son la prueba: nadie legisla contra algo que no está pasando.',
        'El corolario incómodo es que esto se revierte. Al recuperarse la población europea a lo largo del siglo XVI, los salarios reales volvieron a caer hacia la subsistencia, y hacia 1600 un jornalero inglés estaba peor que su tatarabuelo en 1450. No se había ganado nada de forma permanente. La ventaja era función de cuánta gente había muerto.',
      ],
    },
    {
      id: 'east-and-west',
      label: 'El mismo golpe, resultados opuestos',
      kind: 'contrast',
      paragraphs: [
        'Si un hundimiento demográfico libera automáticamente a la mano de obra, la servidumbre debería haber terminado en todas partes. No fue así, y la excepción es lo más instructivo de todo el asunto.',
        '**Al oeste del Elba.** Escasez de mano de obra, empleadores compitiendo, jurisdicción real relativamente fuerte y ciudades dispuestas a acoger fugados. Los siervos negociaron, se movieron y compraron su libertad; los señores convirtieron las prestaciones en rentas y las rentas en dinero. La villanía en Inglaterra ha desaparecido en la práctica a finales del siglo XV, sin que nadie la aboliera nunca.',
        '**Al este del Elba.** La misma escasez de mano de obra y el resultado contrario. Los terratenientes eran políticamente dominantes, las ciudades más débiles y la autoridad central escasa. En vez de competir por trabajadores, los señores usaron su control de la ley local para atar a los campesinos a la tierra con más fuerza que antes: restringir el movimiento, aumentar las prestaciones y consolidar grandes dominios que producían grano para exportar al oeste. Los historiadores lo llaman la segunda servidumbre, y en partes de Europa oriental duró hasta el siglo XIX.',
        'Golpe idéntico. Economía idéntica. Resultado institucional opuesto — porque en un sitio los campesinos podían marcharse y en el otro los señores podían impedirlo.',
        'Esa es la lección que merece llevarse, y se generaliza mucho más allá de 1348. Un golpe no tiene dirección política propia. Aplica presión al orden que ya existe, y ese orden decide adónde va la presión.',
      ],
    },
  ],

  beforeAfter: {
    label: 'El mundo de un jornalero, antes y después',
    before: {
      title: 'Europa en 1340',
      points: [
        'Demasiada gente para la buena tierra disponible',
        'Salarios reales en la subsistencia o cerca',
        'Servidumbre exigible, porque no hay adónde ir',
        'Campos marginales cultivados porque no hay alternativa',
        'Los terratenientes quedándose el excedente',
      ],
    },
    after: {
      title: 'Europa en 1400',
      points: [
        'Tierra de sobra, y un tercio o la mitad de trabajadores menos',
        'Salarios reales prácticamente duplicados y manteniéndose',
        'Servidumbre inexigible en el oeste, endurecida en el este',
        'Tierra marginal abandonada y más producción por trabajador',
        'Gobiernos legislando, sin éxito, para frenar los salarios',
      ],
    },
  },

  whatIf: [
    {
      question: '¿Y si la peste no hubiera llegado nunca a Europa?',
      reasoning: 'Europa habría seguido en la situación maltusiana de 1300: población alta, salarios de subsistencia, parcelas subdivididas y servidumbre exigible. El argumento de Herlihy implica que la presión para adoptar tecnología que ahorrara trabajo, y los niveles salariales que hicieron atractivo el trabajo urbano cualificado, habrían sido mucho más débiles durante mucho más tiempo.',
      constraint: 'Es especulación, y no debe leerse como que la peste fuera necesaria para el desarrollo europeo. La población ya presionaba contra un techo tecnológico que otros golpes —hambruna, guerra, clima— también estaban poniendo a prueba, y el resultado de Europa oriental demuestra que el mismo golpe puede afianzar el orden viejo en vez de romperlo.',
    },
    {
      question: '¿Y si las leyes salariales hubieran sido aplicables?',
      reasoning: 'Si Inglaterra hubiera conseguido congelar los salarios en los niveles de 1346, el excedente creado por la escasez de mano de obra habría ido a los terratenientes y no a los jornaleros, la servidumbre podría haberse sostenido por ley en el oeste como se sostuvo por poder señorial en el este, y la divergencia entre las dos mitades de Europa quizá no se habría abierto nunca.',
      constraint: 'No está claro que fuera aplicable a ningún precio. El Estado no tenía policía, la aplicación dependía de la misma nobleza local que competía por trabajadores, y todo empleador tenía un incentivo privado para saltarse la ley. Europa oriental logró el resultado mediante el poder señorial sobre la jurisdicción local y no mediante un estatuto nacional, lo que sugiere que el mecanismo importa.',
    },
  ],

  quiz: [
    {
      question: '¿Por qué subieron los salarios después de la Peste Negra?',
      options: [
        'Los gobiernos los subieron por ley',
        'La peste mató personas pero dejó intactas tierra, molinos y herramientas, así que el trabajo escaseó',
        'Se inventaron métodos agrícolas nuevos',
        'El comercio con Asia enriqueció a Europa',
      ],
      answerIndex: 1,
      explains: 'Una epidemia destruye personas y no capital. Con los mismos campos y la mitad de trabajadores, el factor escaso pasó a ser el trabajo — y quien tiene el factor escaso pone el precio.',
    },
    {
      question: '¿Qué era el Estatuto de los Trabajadores?',
      options: [
        'Una ley que garantizaba un salario mínimo',
        'Una ley que liberaba a los siervos de sus obligaciones',
        'Una ley inglesa de 1351 que prohibía pagar o exigir más que los salarios anteriores a la peste',
        'Un impuesto sobre los terratenientes',
      ],
      answerIndex: 2,
      explains: 'El Parlamento intentó congelar los salarios en el nivel de 1346. Se persiguió sin parar durante treinta años, que es la prueba más clara de que los salarios subían igualmente.',
    },
    {
      question: '¿En qué estado está la explicación de la rata y la pulga?',
      options: [
        'Está confirmada por el ADN',
        'Está seriamente cuestionada: la propagación fue demasiado rápida y llegó a regiones con pocas ratas',
        'Se ha abandonado por completo',
        'Nunca la propusieron los científicos',
      ],
      answerIndex: 1,
      explains: 'El ADN confirma que el patógeno era Yersinia pestis, pero no la vía. El modelo de la rata viene de estudiar la peste hacia 1900 y encaja mal con el siglo XIV; las pulgas humanas y los piojos son hoy una alternativa destacada.',
    },
    {
      question: '¿Por qué terminó la servidumbre en Europa occidental y se endureció en la oriental?',
      options: [
        'La peste fue mucho peor en el oeste',
        'Los gobernantes del este aprobaron mejores leyes',
        'Los señores del este tenían poder local suficiente para impedir que los campesinos se fueran',
        'En el este no hubo escasez de mano de obra',
      ],
      answerIndex: 2,
      explains: 'El golpe demográfico fue parecido. Donde los campesinos podían marcharse y ser contratados, negociaron su salida; donde los señores controlaban la jurisdicción local, los ataron a la tierra.',
    },
  ],

  sources: [
    {
      id: 'boccaccio-1353',
      kind: 'primary',
      author: 'Giovanni Boccaccio',
      title: 'The Decameron, introduction to the First Day',
      year: 1353,
      detail: 'Escrito hacia 1349-53; traducción inglesa de referencia de G. H. McWilliam, Penguin Classics',
      note: 'Un testigo de la Florencia de 1348, escribiendo uno o dos años después. El mejor relato de lo que la epidemia hizo con el comportamiento social corriente.',
    },
    {
      id: 'de-mussis-1348',
      kind: 'primary',
      author: 'Gabriele de’ Mussis',
      title: 'Historia de Morbo (Account of the Plague)',
      year: 1348,
      detail: 'Escrito en Piacenza hacia 1348; trad. en Rosemary Horrox, «The Black Death», Manchester University Press, 1994',
      note: 'La fuente de la historia de la catapulta de Caffa, y de mucho más. No estuvo en Caffa, que es la salvedad necesaria cada vez que se repite.',
    },
    {
      id: 'clement-vi-1348',
      kind: 'primary',
      author: 'Pope Clement VI',
      title: 'Papal bulls on the protection of the Jews (July and 26 September 1348)',
      year: 1348,
      detail: 'Emitidas en Aviñón; textos en Horrox, «The Black Death», y en Simonsohn, «The Apostolic See and the Jews»',
      note: 'Condenan las matanzas y señalan que los judíos también morían de peste. Prueba de que la acusación se sabía infundada ya entonces.',
    },
    {
      id: 'statute-of-labourers-1351',
      kind: 'primary',
      author: 'The Parliament of England',
      title: 'The Statute of Labourers, 25 Edward III',
      year: 1351,
      detail: 'Statutes of the Realm, vol. I; tras la Ordenanza de los Trabajadores de 1349',
      note: 'Salarios congelados por ley en los niveles de 1346. El extenso registro de procesos bajo ella es la mejor prueba de cuánto habían subido en realidad.',
    },
    {
      id: 'benedictow-2004',
      kind: 'book',
      author: 'Ole J. Benedictow',
      title: 'The Black Death 1346–1353: The Complete History',
      year: 2004,
      detail: 'Boydell Press. ISBN 978-0-85115-943-0',
      note: 'El repaso más sistemático de los datos locales de mortalidad, y la fuente de las estimaciones más altas. Cuidadoso, detallado y polémico.',
    },
    {
      id: 'herlihy-1997',
      kind: 'book',
      author: 'David Herlihy',
      title: 'The Black Death and the Transformation of the West',
      year: 1997,
      detail: 'Harvard University Press, ed. de Samuel K. Cohn Jr. ISBN 978-0-674-07613-6',
      note: 'El argumento de que la peste rompió un bloqueo maltusiano y llevó a Europa a una senda de salarios más altos y más tecnológica. La columna de esta historia.',
    },
    {
      id: 'bos-2011',
      kind: 'paper',
      author: 'Kirsten I. Bos, Verena J. Schuenemann, G. Brian Golding and others',
      title: 'A draft genome of Yersinia pestis from victims of the Black Death',
      year: 2011,
      detail: 'Nature, vol. 478, pp. 506-510',
      note: 'ADN de los dientes de víctimas del cementerio de East Smithfield, abierto en Londres en 1348. Esto es lo que zanjó qué era la enfermedad.',
    },
    {
      id: 'spyrou-2022',
      kind: 'paper',
      author: 'Maria A. Spyrou, Lyazzat Musralina, Johannes Krause and others',
      title: 'The source of the Black Death in fourteenth-century central Eurasia',
      year: 2022,
      detail: 'Nature, vol. 606, pp. 718-724',
      note: 'Genomas de peste de tumbas cercanas al lago Issyk-Kul, fechadas por sus propias inscripciones en 1338-39, situadas en la raíz del árbol de la pandemia.',
    },
  ],
}
