import type { Story } from '../../types'

export const meijiRestorationEs: Story = {
  slug: 'meiji-restoration',
  title: 'Cuarenta años para deshacer once páginas',
  subtitle: 'Japón, 1853–1911 — llegaron cuatro barcos, se firmó un tratado a punta de cañón, y un país se reconstruyó entero para conseguir anularlo.',
  hook: 'Cuatro buques de guerra estadounidenses abrieron Japón por la fuerza en 1853. Los hombres que tomaron el poder quince años después dedicaron su vida a un solo objetivo: que no se pudiera volver a hacer.',
  era: 'industrial',
  category: 'eras',
  years: [1853, 1912],
  regions: ['Japón', 'Estados Unidos', 'Gran Bretaña'],
  nodes: ['meiji-restoration', 'tokugawa-shogunate', 'perry-expedition', 'samurai', 'charter-oath'],
  tags: ['modernisation', 'empire', 'reform', 'asia', 'treaties', 'legend'],
  readingMinutes: 11,
  reviewed: '2026-08-05',
  mood: 'ember',

  reel: [
    { beat: 'hook', punch: true, text: 'Cuatro buques de guerra estadounidenses llegaron en 1853 y abrieron un país en una semana.' },
    { beat: 'hook', text: 'Cuarenta años después ese país tenía una armada capaz de vencer a un imperio europeo.' },
    { beat: 'worldBefore', kicker: '1603–1853', text: 'Japón lleva dos siglos y medio de paz bajo un gobierno militar,' },
    { beat: 'worldBefore', text: 'con el contacto exterior reducido a unos canales con licencia: holandeses en una isla.' },
    { beat: 'worldBefore', punch: true, text: 'No sellado. Filtrado. Y el filtro es el asunto: el shogun decide qué entra.' },
    { beat: 'problem', kicker: '1842', text: 'Entonces llegan por Nagasaki los informes sobre lo que le ha pasado a China,' },
    { beat: 'problem', text: 'y en Edo los leen bien. Esto es lo que cuesta ahora negarse.' },
    { beat: 'problem', punch: true, text: 'Suavizan las normas sobre barcos extranjeros once años antes de que llegue nadie.' },
    { beat: 'story', kicker: 'Julio de 1853', text: 'Perry mete cuatro barcos en la bahía de Edo, dos de ellos de vapor,' },
    { beat: 'story', text: 'que se mueven contra el viento y la corriente, cosa que en Japón no puede hacer nada.' },
    { beat: 'story', text: 'Entrega una carta, dice que volverá a por la respuesta y se va.' },
    { beat: 'story', punch: true, mark: 'gate', text: 'Vuelve con más barcos. Se firma el tratado.' },
    { beat: 'story', text: 'Y luego un segundo: aranceles fijados, y extranjeros juzgados por sus propios tribunales.' },
    { beat: 'story', punch: true, text: 'El gobierno existe para mantener fuera a los extranjeros, y acaba de demostrar que no puede.' },
    { beat: 'story', kicker: '1863', text: 'Dos grandes dominios prueban a expulsar a los bárbaros por la fuerza, y los bombardean.' },
    { beat: 'story', punch: true, mark: 'reversal', text: 'Así que invierten la consigna. Si no puedes expulsarlos, conviértete en ellos.' },
    { beat: 'story', kicker: '1868', text: 'Una guerra civil corta, y un emperador de quince años recupera un poder que no ejerce.' },
    { beat: 'whyItHappened', text: 'Lo que sigue es lo más raro. Los hombres que ahora dirigen Japón son samuráis,' },
    { beat: 'whyItHappened', text: 'y en ocho años abolen a los samuráis: estipendios, espadas, todo.' },
    { beat: 'whyItHappened', punch: true, text: 'Disuelven su propia clase porque un ejército de reclutas vence a una casta guerrera.' },
    { beat: 'whyItHappened', text: 'Medio gabinete se va del país veintidós meses a estudiar cómo lo hacen los demás.' },
    { beat: 'whyItHappened', mark: 'chain', text: 'Ferrocarriles, telégrafo, bancos, una constitución, escuela obligatoria, una armada moderna.' },
    { beat: 'consequences', kicker: '1899', text: 'Se acaban los tribunales extranjeros. En 1911 Japón vuelve a fijar sus aranceles.' },
    { beat: 'consequences', punch: true, text: 'Cuarenta y tres años de esfuerzo nacional para anular dos tratados. Ese era el objetivo.' },
    { beat: 'whyItMatters', text: 'Y entonces Japón se queda con Taiwán, y con Corea, y se lo hace a otros.' },
    { beat: 'whyItMatters', punch: true, text: 'Las herramientas que impiden que te colonicen son las mismas que sirven para colonizar.' },
  ],

  beats: {
    worldBefore: {
      heading: 'El mundo de antes',
      paragraphs: [
        'Desde 1603 Japón estuvo gobernado por el shogunato Tokugawa: un gobierno militar bajo un shogun hereditario, con el emperador en Kioto como figura sagrada que reinaba y no gobernaba. Aquello dio dos siglos y medio sin una guerra seria, que es un historial notable para cualquier Estado en cualquier parte.',
        'También restringió el contacto exterior, desde la década de 1630, a un pequeño número de canales controlados: comerciantes holandeses confinados en la isla artificial de Dejima, en el puerto de Nagasaki; mercaderes chinos en la misma ciudad; embajadas coreanas por Tsushima; y comercio con las Ryukyu y con los ainu en los márgenes. El cristianismo se prohibió, se prohibió salir del país a los súbditos japoneses y no se construyeron barcos de altura.',
        'La palabra que suele asociarse a esto es *sakoku*, país cerrado, y induce a error. Japón no estaba sellado; estaba filtrado, a propósito, y el shogunato controlaba lo que entraba. Se importaban y estudiaban libros holandeses — todo un campo académico, el *rangaku* o saber holandés, creció alrededor de la medicina, la astronomía y la artillería occidentales. Los informes anuales holandeses sobre asuntos mundiales iban al gobierno.',
        'Y la sociedad que había tras el filtro no era atrasada. El Japón Tokugawa tenía una alfabetización alta para cualquier estándar preindustrial, con miles de escuelas de aldea; una economía comercial sofisticada, con futuros del arroz negociados en Osaka; una red urbana densa que incluía Edo, probablemente la mayor ciudad del mundo; y producción protoindustrial en textiles y metalurgia. Esto importa, porque es la razón de que lo que vino después fuera posible tan rápido.',
        'Lo que no tenía era un ejército moderno, un gobierno nacional capaz de recaudar directamente ni experiencia reciente de sentirse amenazado.',
      ],
      aside: {
        kind: 'number',
        label: 'La cifra',
        body: 'A principios del siglo XIX, alrededor del cuarenta por ciento de los niños japoneses y quizá el quince por ciento de las niñas recibían alguna escolarización formal: comparable con la Europa de la época y en algunos sitios por delante. Un país que ya sabe leer es un país que se puede reeducar.',
        sourceId: 'jansen-2000',
      },
      sourceIds: ['jansen-2000', 'gordon-2003'],
    },

    problem: {
      heading: 'El problema',
      paragraphs: [
        'El shogunato supo lo que venía antes de que llegara, y por buena fuente.',
        'Los holandeses de Nagasaki presentaban informes anuales de inteligencia, y a principios de la década de 1840 esos informes describían la Guerra del Opio: un imperio chino que se había negado a las exigencias comerciales occidentales, había sido derrotado de forma aplastante por una fuerza británica pequeña y había tenido que firmar un tratado cediendo territorio, abriendo puertos y pagando una indemnización. En Edo lo leyeron bien y de inmediato. En 1842 el shogunato revocó discretamente su orden de 1825 de disparar contra cualquier barco extranjero que se acercara a la costa, y la sustituyó por la instrucción de suministrarles agua y combustible y despedirlos con cortesía.',
        'Eso es once años antes de Perry. El gobierno entendía la situación con precisión: no podía ganar una guerra contra una potencia occidental, acababa de demostrarse que negarse en redondo era catastrófico, y no tenía ninguna buena opción.',
        'El problema era que toda la legitimidad del shogunato descansaba en su capacidad de defender el reino. El título formal del shogun significaba algo así como «generalísimo sometedor de bárbaros». Un gobierno militar que no puede rechazar una amenaza militar tiene una dificultad muy concreta, y en Japón lo veía todo el mundo.',
        'Así que cuando los barcos llegaron de verdad, la crisis no era realmente de política exterior. Era sobre quién tenía derecho a gobernar.',
      ],
      sourceIds: ['jansen-2000', 'beasley-1972'],
    },

    story: {
      heading: 'La historia',
      paragraphs: [
        'El 8 de julio de 1853, el comodoro Matthew Perry metió cuatro buques de guerra estadounidenses en la bahía de Edo y se negó a trasladarse a Nagasaki, que era adonde debían ir los extranjeros. Dos de sus barcos eran de vapor, y maniobraron dentro de la bahía contra el viento y la corriente — una capacidad que Japón no poseía y que todos los que miraban entendieron. Entregó una carta del presidente exigiendo un tratado, dijo que volvería al año siguiente a por la respuesta y se marchó.',
        'Volvió en febrero de 1854 con nueve barcos. El Convenio de Kanagawa se firmó el 31 de marzo: dos puertos abiertos, protección para los náufragos y admisión de un cónsul estadounidense. Cuatro años después, ese cónsul, Townsend Harris, negoció el tratado que de verdad importaba: comercio con aranceles bajos y fijos que Japón no podía modificar, y extraterritorialidad, es decir, que los extranjeros acusados de delitos en Japón serían juzgados por sus propios cónsules bajo su propia ley. Gran Bretaña, Francia, Rusia y los Países Bajos obtuvieron las mismas condiciones en cuestión de meses.',
        'Estos son los tratados desiguales, y son el mismo instrumento usado con China tras las Guerras del Opio. Todo lo que sigue en esta historia va de deshacerse de ellos.',
        'El resultado interno fueron quince años de crisis política. Cuajó un movimiento en torno a la consigna *sonnō jōi* —reverenciar al emperador, expulsar a los bárbaros—, que en la práctica era una manera de decir que el shogun había fracasado y que había que invocar la autoridad del emperador contra él. Hubo ataques a extranjeros. La corte de Kioto, ignorada durante siglos, se convirtió en el centro de la política nacional.',
        'Y entonces dos de los grandes dominios occidentales probaron literalmente la segunda mitad de la consigna. Satsuma mató a un comerciante británico en 1862 y como respuesta la Royal Navy bombardeó Kagoshima. Chōshū disparó contra barcos extranjeros en el estrecho de Shimonoseki y, en 1864, una escuadra combinada británica, francesa, holandesa y estadounidense le destruyó las baterías costeras.',
        'Los dos dominios sacaron la misma conclusión de que los bombardearan, y es la bisagra de toda la historia: a los bárbaros no se los podía expulsar, así que la única manera de estar a salvo de ellos era adquirir lo que los hacía fuertes. Los hombres que habían encabezado el movimiento antiextranjero se convirtieron en los modernizadores más decididos de Japón, y lo habían aprendido por las malas, en persona.',
        'Satsuma y Chōshū se aliaron en 1866, derrotaron al shogunato en una guerra civil corta y el 3 de enero de 1868 proclamaron la restauración del gobierno imperial directo. El emperador tenía quince años. El poder real estaba en manos de un grupo de samuráis de rango medio de los dominios vencedores, casi todos treintañeros.',
        'En abril de 1868 publicaron el Juramento de los Cinco Artículos: cinco frases breves que prometían asambleas deliberantes, el fin de las restricciones de clase sobre el oficio, el abandono de «las malas costumbres del pasado» y, en el quinto artículo, que se buscaría el conocimiento por todo el mundo para reforzar los cimientos del gobierno imperial. Esa última línea no era retórica. Era un programa, y lo ejecutaron.',
      ],
      aside: {
        kind: 'voice',
        label: 'Una voz de la época',
        body: 'El quinto artículo del Juramento de abril de 1868 dice que se buscará el conocimiento por todo el mundo, para reforzar los cimientos del gobierno imperial. Tres años después, medio gobierno se fue de Japón durante veintidós meses a inspeccionar en persona las instituciones de Estados Unidos y de Europa. El documento decía exactamente lo que decía.',
        sourceId: 'charter-oath-1868',
      },
      sourceIds: ['perry-narrative-1856', 'kanagawa-1854', 'charter-oath-1868', 'beasley-1972'],
    },

    whyItHappened: {
      heading: 'Por qué funcionó',
      paragraphs: [
        'Muchos Estados intentaron modernizarse bajo presión occidental en el siglo XIX. Casi ninguno lo consiguió a esta escala. Las razones son concretas y en su mayoría poco vistosas.',
        '**Sabían exactamente qué estaban comprando.** El objetivo no fue nunca la modernidad en abstracto; era la revisión de los tratados. La extraterritorialidad se justificaba diciendo que el derecho japonés no era civilizado, así que Japón escribió códigos civiles y penales de modelo europeo. La autonomía arancelaria exigía que te tomaran en serio como Estado, así que Japón construyó el aparato de uno. Cada reforma llevaba un argumento pegado, y el argumento era: esto es lo que hace falta para que anulen los tratados.',
        '**Abolieron su propia clase.** Esta es la parte que no tiene verdadero paralelo. Los hombres que dirigían el país eran samuráis. Entre 1871 y 1876 abolieron los dominios, acabaron con el monopolio samurái sobre las armas, introdujeron el reclutamiento de plebeyos, conmutaron los estipendios hereditarios en bonos de pago único y prohibieron llevar espada. Desmontaron los privilegios de unos dos millones de personas, ellos incluidos, porque un ejército de reclutas con fusiles vence a una casta guerrera y ellos habían visto la demostración.',
        '**Fueron a mirar.** La Misión Iwakura de 1871-73 sacó del país a unos cincuenta altos cargos —entre ellos medio gabinete efectivo— durante veintidós meses para estudiar directamente el gobierno, la industria, el derecho y la educación de Estados Unidos y Europa. Ningún otro Estado ante este problema mandó fuera a su propia dirigencia casi dos años a tomar apuntes.',
        '**Partieron de cimientos reales.** El Japón Tokugawa ya tenía alfabetización extendida, una economía comercial monetizada, una clase mercantil y una tradición de saber holandés que había mantenido abierto un canal a la ciencia occidental durante dos siglos. El gobierno Meiji no construyó un Estado moderno sobre una página en blanco; reconstruyó uno que funcionaba sobre principios nuevos.',
        '**Y contrataron sin sentimentalismo y de forma temporal.** Se trajo a miles de expertos extranjeros —los *oyatoi*— con sueldos enormes para construir ferrocarriles, enseñar medicina y redactar códigos, y luego se los sustituyó sistemáticamente por japoneses formados con ellos. El objetivo no fue nunca importar competencia de forma permanente. Era adquirirla y dejar de pagar por ella.',
        'También costó. La reforma del impuesto sobre la tierra de 1873 puso la carga de lleno sobre los campesinos, y hubo cientos de protestas rurales. Los samuráis descontentos se rebelaron repetidamente, hasta la Rebelión de Satsuma de 1877, en la que Saigō Takamori —uno de los arquitectos de la Restauración— murió encabezando a su propia clase contra el gobierno que había ayudado a crear. El ejército de reclutas lo derrotó, lo que zanjó el debate para siempre.',
      ],
      sourceIds: ['jansen-2000', 'iwakura-1878', 'gordon-2003'],
    },

    consequences: {
      heading: 'Qué cambió',
      paragraphs: [
        'Un país se reorganizó de arriba abajo en aproximadamente una generación, y después usó lo que había construido.',
      ],
      shortTerm: [
        'Los dominios fueron abolidos en 1871 y sustituidos por prefecturas dependientes del gobierno central: trescientos años de gobierno descentralizado deshechos de un golpe.',
        'El servicio militar obligatorio se introdujo en 1873, la enseñanza primaria obligatoria en 1872, y un impuesto moderno sobre la tierra en 1873 que por primera vez dio al Estado ingresos nacionales previsibles.',
        'Los estipendios samuráis se conmutaron en bonos del Estado en 1876, y ese mismo año se prohibió llevar espada. La clase dejó de existir como categoría legal.',
        'La Rebelión de Satsuma de 1877 fue la última resistencia del viejo orden guerrero, y la venció un ejército de campesinos reclutados.',
        'El ferrocarril entre Tokio y Yokohama abrió en 1872, siguió el telégrafo, y se construyeron fábricas estatales modelo —entre ellas la hilandería de seda de Tomioka— que después se vendieron a propietarios privados.',
      ],
      longTerm: [
        'En 1889 se promulgó una constitución de modelo prusiano, y en 1890 se reunió la primera Dieta: el primer parlamento nacional en funcionamiento de Asia.',
        'La extraterritorialidad quedó abolida por el tratado de 1894 con Gran Bretaña y entró en vigor en 1899. La autonomía arancelaria plena se recuperó en 1911. El programa duró cuarenta y tres años y funcionó.',
        'Japón venció a China en 1894-95 y a Rusia en 1904-05, siendo esta última la primera derrota de una gran potencia europea a manos de un Estado asiático en la época moderna, y resonó en todos los países colonizados del mundo.',
        'También adquirió un imperio: Taiwán en 1895, el sur de Sajalín en 1905 y Corea anexionada en 1910, imponiendo a sus vecinos los instrumentos que le habían impuesto a él.',
        'El arreglo institucional de 1889, en el que el mando militar respondía ante el emperador y no ante el gabinete, fue una de las causas estructurales de los años treinta. Las fortalezas y la catástrofe salieron del mismo diseño.',
      ],
      unexpected: [
        'Los hombres que gritaban «expulsad a los bárbaros» pasaron a ser los que importaron los ferrocarriles, los códigos legales y la armada de los bárbaros. Los bombardeos les cambiaron la cabeza, y lo dijeron.',
        'Medio gobierno se fue del país casi dos años en 1871 a estudiar fuera, en un momento de aguda inestabilidad interna. Cuesta imaginar a algún Estado moderno haciendo esto.',
        'Japón emitió bonos públicos para comprar la salida de la clase samurái: compró en la práctica la disolución de la aristocracia, con los aristócratas votándola.',
        'El emperador Meiji tenía quince años en la Restauración y no tuvo poder independiente durante años. La revolución hecha en su nombre la dirigieron hombres de treinta y tantos.',
        'Los primeros buques de guerra japoneses modernos se construyeron en astilleros británicos, y la flota que destruyó a la armada rusa en Tsushima en 1905 era en buena parte de construcción británica, comprada con los impuestos de un país al que habían abierto por la fuerza cincuenta años antes.',
      ],
      sourceIds: ['gordon-2003', 'jansen-2000'],
    },

    whyItMatters: {
      heading: 'Por qué sigue importando',
      paragraphs: [
        'Este es el caso más claro de la historia moderna de un Estado que mira lo que les está pasando a sus vecinos, identifica correctamente lo que le va a pasar a él y se reorganiza a propósito para impedirlo. Las Guerras del Opio son el grupo de control: China afrontó la misma presión primero, y el atlas cuenta esa historia en otro sitio. Lo que separa los dos desenlaces no es la presión, es la respuesta.',
        'El mecanismo que conviene llevarse es que los dirigentes Meiji trataron la modernización como algo instrumental y no aspiracional. No intentaban volverse occidentales. Tenían un objetivo definido —anular los tratados desiguales— y trabajaron hacia atrás desde él, adoptando lo que servía a ese fin y descartando lo que no. Códigos legales, porque la extraterritorialidad se justificaba por la diferencia jurídica. Industria, porque una armada necesita una economía. Reclutamiento, porque una casta guerrera no puede librar una guerra moderna. Cada reforma tenía una razón que cabía en una frase.',
        'Lo segundo es el precio que estuvieron dispuestos a pagar, y quién lo pagó. Una clase dirigente se abolió a sí misma, cosa casi única. Los campesinos pagaron todo el programa con un impuesto sobre la tierra que no atendía a las cosechas. Saigō Takamori, uno de los hombres que hicieron la Restauración, murió combatiéndola ocho años después, y el gobierno que lo mató le puso después una estatua.',
        'Y lo tercero es la parte que se resiste a un final cómodo. A los treinta años de escapar de los tratados desiguales, Japón imponía arreglos equivalentes a Corea, y en 1910 la había anexionado del todo. Las herramientas que hacen imposible colonizar un país —un ejército moderno, una base industrial, un Estado capaz de recaudar, reclutar y movilizar— son exactamente las herramientas para colonizar a otro. Nada en la caja de herramientas te dice cuál de las dos cosas hacer.',
        'Eso no es un argumento contra lo que hizo Japón en 1868. Es una razón para tener cuidado con la moraleja que sacamos. La Restauración Meiji es una historia sobre capacidad, y la capacidad no tiene dirección.',
      ],
      sourceIds: ['jansen-2000', 'gordon-2003'],
    },
  },

  timeline: [
    { year: 1603, title: 'Se establece el shogunato Tokugawa', detail: 'Un gobierno militar bajo un shogun hereditario inicia dos siglos y medio sin guerras serias, con el emperador como figura sagrada en Kioto.' },
    { year: 1639, title: 'Se estrecha el contacto exterior', detail: 'Cristianismo prohibido, japoneses con prohibición de salir, y comercio exterior reducido a canales controlados: los holandeses confinados en una isla del puerto de Nagasaki.', pivotal: true },
    { year: 1842, title: 'El informe sobre la Guerra del Opio llega a Edo', detail: 'La inteligencia holandesa describe la derrota china. El shogunato revoca su orden de disparar a los barcos extranjeros, once años antes de que llegue ningún estadounidense.', pivotal: true },
    { year: 1853, date: '1853-07-08', title: 'Perry entra en la bahía de Edo', detail: 'Cuatro buques de guerra estadounidenses, dos de vapor moviéndose contra viento y corriente. Entrega una exigencia de tratado y anuncia que volverá a por la respuesta.', pivotal: true },
    { year: 1854, date: '1854-03-31', title: 'El Convenio de Kanagawa', detail: 'Perry vuelve con nueve barcos. Se abren dos puertos, se protege a los náufragos y se admite a un cónsul estadounidense.', pivotal: true },
    { year: 1858, title: 'El Tratado Harris', detail: 'Comercio con aranceles que Japón no puede fijar, y extranjeros juzgados por sus propios tribunales consulares. Gran Bretaña, Francia, Rusia y los Países Bajos obtienen lo mismo.', pivotal: true },
    { year: 1863, title: 'Kagoshima y Shimonoseki', detail: 'Satsuma y Chōshū intentan expulsar a los extranjeros por la fuerza y las escuadras occidentales los bombardean. Ambos concluyen que a los bárbaros no se los puede expulsar.', pivotal: true },
    { year: 1868, date: '1868-01-03', title: 'Se proclama la Restauración', detail: 'Tras una guerra civil corta se declara el gobierno imperial directo. El emperador tiene quince años; el poder está en samuráis de rango medio de los dominios vencedores.', pivotal: true },
    { year: 1868, date: '1868-04-06', title: 'El Juramento de los Cinco Artículos', detail: 'Cinco artículos que terminan prometiendo que se buscará el conocimiento por todo el mundo para reforzar el gobierno imperial. Es un programa, no una floritura.', pivotal: true },
    { year: 1871, title: 'Se abolen los dominios y parte la Misión Iwakura', detail: 'Tres siglos de gobierno descentralizado terminan de un golpe, y unos cincuenta altos cargos salen veintidós meses a estudiar Occidente de primera mano.', pivotal: true },
    { year: 1876, title: 'Se abole a los samuráis', detail: 'Los estipendios hereditarios se conmutan en bonos y se prohíbe llevar espada. El gobierno disuelve la clase a la que pertenecen todos sus miembros.', pivotal: true },
    { year: 1877, title: 'La Rebelión de Satsuma', detail: 'Saigō Takamori, arquitecto de la Restauración, encabeza la última revuelta samurái y lo derrota un ejército de campesinos reclutados.' },
    { year: 1889, title: 'La Constitución Meiji', detail: 'Se promulga una constitución de modelo prusiano y en 1890 se reúne la primera Dieta, con el mando militar respondiendo ante el emperador y no ante el gabinete.' },
    { year: 1899, title: 'Termina la extraterritorialidad', detail: 'Entra en vigor el tratado de 1894 con Gran Bretaña y cierran los tribunales consulares extranjeros. La autonomía arancelaria plena llega en 1911, cuarenta y tres años después de la Restauración.', pivotal: true },
    { year: 1910, title: 'Se anexiona Corea', detail: 'Tras escapar de los tratados desiguales, Japón impone arreglos equivalentes a sus vecinos y después se queda el país entero.', pivotal: true },
  ],

  causeEffect: [
    { cause: 'Gran Bretaña derrota a China en la Guerra del Opio', effect: 'Japón cambia su política de defensa costera en 1842', because: 'Los informes holandeses dieron a Edo un relato exacto de lo que costaba ahora negarse a las exigencias occidentales, once años antes de ponerse a prueba.' },
    { cause: 'Dos de los cuatro barcos de Perry son de vapor', effect: 'La demostración no admite discusión', because: 'Unos barcos que entran en una bahía contra el viento y la corriente muestran que la brecha tecnológica no es una cuestión de grado.' },
    { cause: 'El shogunato firma tratados que no puede rechazar', effect: 'Su legitimidad se hunde', because: 'A un gobierno militar cuya única pretensión de mando es defender el reino no le queda nada cuando queda demostrado que no puede defenderlo.' },
    { cause: 'Satsuma y Chōshū son bombardeados en 1863-64', effect: 'El movimiento antiextranjero se vuelve el movimiento modernizador', because: 'Tras probar la expulsión y ser destruidos, esos mismos hombres concluyeron que adquirir capacidad occidental era la única vía hacia la seguridad.' },
    { cause: 'Los tratados desiguales se justifican por la diferencia jurídica japonesa', effect: 'Japón escribe códigos legales de estilo europeo', because: 'Si la razón declarada de la extraterritorialidad es que tu derecho no es civilizado, eliminar esa razón es la vía directa para eliminar la cláusula.' },
    { cause: 'Un ejército de reclutas con fusiles vence a una casta guerrera', effect: 'Los samuráis son abolidos por samuráis', because: 'Los hombres del gobierno habían visto en persona funcionar la potencia de fuego occidental, y unos espadachines hereditarios eran ya una irrelevancia cara.' },
    { cause: 'El impuesto sobre la tierra de 1873 recae en los campesinos con independencia de la cosecha', effect: 'El Estado gana ingresos previsibles y el campo lo paga', because: 'La industrialización necesita ingresos estables, y el único sector lo bastante grande para darlos era la agricultura.' },
    { cause: 'Japón adquiere ejército, armada y base industrial modernos', effect: 'Construye un imperio en Taiwán y Corea', because: 'La capacidad que hace imposible colonizar un Estado es la misma que se necesita para colonizar otro sitio.' },
  ],

  myths: [
    {
      myth: 'Japón era un país sellado y aislado que no sabía nada del mundo exterior.',
      reality: 'El *sakoku* era un filtro, no un muro. Los comerciantes holandeses operaron en Nagasaki todo el tiempo, los mercaderes chinos comerciaban allí, las embajadas coreanas llegaban por Tsushima, y toda una disciplina académica —el saber holandés— estudiaba la medicina, la astronomía y la artillería occidentales. El shogunato recibía informes anuales sobre asuntos mundiales y se enteró pronto de la Guerra del Opio.',
      whyItPersists: '«País cerrado» es un término real de la época y una imagen memorable, y el propio relato de Perry se escribió para presentarlo abriendo un reino ermitaño.',
      sourceIds: ['jansen-2000', 'perry-narrative-1856'],
    },
    {
      myth: 'Japón se modernizó desde la nada en una sola generación.',
      reality: 'Se industrializó extraordinariamente rápido, pero no desde la nada. El Japón Tokugawa tenía alta alfabetización, miles de escuelas de aldea, una economía comercial monetizada con un mercado de futuros del arroz, ciudades densas y protoindustria previa. La reforma Meiji reconstruyó una sociedad que funcionaba sobre principios nuevos, no creó una.',
      whyItPersists: 'La velocidad es de verdad asombrosa, y tanto el relato nacional japonés como los observadores occidentales tenían motivos para describirla como un milagro y no como una sociedad bien preparada moviéndose rápido.',
      sourceIds: ['jansen-2000', 'gordon-2003'],
    },
    {
      myth: 'El emperador Meiji tomó el poder y dirigió la transformación.',
      reality: 'Tenía quince años en la Restauración y no tuvo autoridad independiente durante años. La revolución la llevó a cabo en su nombre un grupo reducido de samuráis de rango medio de Satsuma y Chōshū, la mayoría treintañeros. La autoridad imperial fue el instrumento, no el agente.',
      whyItPersists: 'Al nuevo gobierno le convenía que pareciera que gobernaba el emperador, y esa presentación fue política oficial durante ochenta años.',
      sourceIds: ['beasley-1972', 'jansen-2000'],
    },
    {
      myth: 'A los samuráis los destruyeron desde fuera.',
      reality: 'Los abolió su propia clase. Todas las figuras importantes del gobierno Meiji eran samuráis, y entre 1871 y 1876 acabaron con los dominios, introdujeron el reclutamiento de plebeyos, conmutaron los estipendios hereditarios en bonos y prohibieron la espada. Cuando Saigō Takamori encabezó la última revuelta samurái en 1877, lo derrotó un ejército de campesinos reclutados.',
      whyItPersists: 'El relato del último samurái es mucho más romántico que un grupo de funcionarios decidiendo que sus propios privilegios eran un lastre estratégico y votando su eliminación.',
      sourceIds: ['jansen-2000', 'gordon-2003'],
    },
  ],

  disagreements: [
    {
      question: '¿Fue la Restauración una revolución o un golpe de una facción de la élite?',
      positions: [
        { view: 'Una revolución en sus efectos: abolió los dominios, el sistema de clases y a los samuráis, rehízo la propiedad de la tierra, el derecho, la educación y el ejército, y transformó la base del Estado en una década.', heldBy: 'Marius Jansen y la lectura transformadora', sourceId: 'jansen-2000' },
        { view: 'En su forma, una toma del poder por samuráis de dos dominios occidentales, usando la autoridad imperial como legitimación. La revolución social vino de sus cálculos estratégicos y no de ningún movimiento popular.', heldBy: 'El análisis político de W. G. Beasley', sourceId: 'beasley-1972' },
      ],
      atlasPosition: 'El atlas lo describe como un golpe de una facción que después llevó a cabo una revolución, porque ambas descripciones encajan con las pruebas en fases distintas y ninguna sola explica lo que pasó.',
    },
    {
      question: '¿Cuánto explica la herencia Tokugawa la velocidad del cambio?',
      positions: [
        { view: 'Muchísimo. La alfabetización, las redes comerciales, la densidad urbana, la protoindustria y el saber holandés hicieron que el Estado Meiji estuviera reconstruyendo y no construyendo, y por eso fue tan rápido.', heldBy: 'La lectura de continuidad de la investigación reciente', sourceId: 'gordon-2003' },
        { view: 'Menos que eso. Los factores decisivos fueron políticos: el hundimiento del shogunato, la concentración de poder en un grupo pequeño y decidido, y la disposición a romper instituciones, incluidas las propias.', heldBy: 'Los relatos que subrayan la Restauración como ruptura', sourceId: 'beasley-1972' },
      ],
      atlasPosition: 'El atlas da peso a ambas: los cimientos hicieron posible la velocidad, y la ruptura política hizo posibles las decisiones. Rechaza el encuadre del Japón Meiji como una sociedad que parte de cero.',
    },
  ],

  didYouKnow: [
    'Japón se enteró de la derrota china en la Guerra del Opio por informes holandeses y cambió su política de defensa costera en 1842, once años antes de que llegara Perry.',
    'Dos de los cuatro barcos de Perry eran de vapor. Entrar en la bahía de Edo contra el viento fue la parte de la demostración que importaba.',
    'La consigna del movimiento que derribó al shogunato era «reverenciar al emperador, expulsar a los bárbaros». Sus dirigentes acabaron siendo los mayores importadores de tecnología occidental de Japón.',
    'En 1871 unos cincuenta altos cargos, entre ellos medio gabinete efectivo, se fueron de Japón veintidós meses a estudiar en persona las instituciones occidentales.',
    'A la clase samurái la abolió un gobierno compuesto íntegramente por samuráis, que se compraron sus propios estipendios hereditarios con bonos del Estado.',
    'Saigō Takamori ayudó a hacer la Restauración en 1868 y murió encabezando una revuelta contra ella en 1877. El gobierno le levantó después una estatua en Tokio.',
    'El emperador Meiji tenía quince años cuando se le «restauró» el poder, y los hombres que de verdad dirigían el país eran casi todos treintañeros.',
    'La extraterritorialidad terminó en 1899 y la autonomía arancelaria se recuperó en 1911: cuarenta y tres años de esfuerzo nacional para anular dos tratados.',
  ],

  lenses: [
    {
      id: 'one-minute',
      label: 'En un minuto',
      kind: 'length',
      paragraphs: [
        'Japón estaba gobernado desde 1603 por un shogunato militar que limitaba el contacto exterior a unos pocos canales controlados. No ignoraba el mundo: los comerciantes holandeses de Nagasaki entregaban informes anuales, y la noticia de la derrota china en la Guerra del Opio hizo que el shogunato suavizara su política de defensa costera en 1842.',
        'En julio de 1853 el comodoro Perry metió cuatro buques de guerra estadounidenses en la bahía de Edo, dos de ellos de vapor. Siguió el Convenio de Kanagawa en 1854, y el Tratado Harris de 1858 impuso aranceles fijos y extraterritorialidad: las mismas condiciones desiguales usadas con China.',
        'Un gobierno militar que no puede rechazar una amenaza militar pierde su razón de existir. Creció un movimiento para «reverenciar al emperador y expulsar a los bárbaros», y cuando dos grandes dominios probaron literalmente la expulsión y fueron bombardeados por escuadras occidentales en 1863-64, invirtieron la consigna: adquirir lo que los hace fuertes. Derribaron al shogunato en 1868 y restauraron a un emperador de quince años en un poder nominal.',
        'Los samuráis que ahora gobernaban abolieron los dominios, introdujeron el reclutamiento, acabaron con su propia clase, mandaron a medio gabinete al extranjero veintidós meses y construyeron ferrocarriles, escuelas, industria, códigos legales, una constitución y una armada. La extraterritorialidad terminó en 1899 y la autonomía arancelaria en 1911: el objetivo entero. Después Japón usó esas mismas capacidades para quedarse con Taiwán y Corea.',
      ],
    },
    {
      id: 'age-10',
      label: 'Explícamelo como si tuviera 10 años',
      kind: 'age',
      paragraphs: [
        'Durante unos doscientos cincuenta años, Japón dejó entrar solo a muy pocos extranjeros, y los vigilaba de cerca. Era un país en paz y le funcionaba.',
        'Pero Japón estaba atento a las noticias. Y las noticias de China eran terribles: Gran Bretaña había aparecido con buques de guerra, había vencido a China con dureza y la había obligado a firmar un acuerdo horrible. En Japón se dieron cuenta de que probablemente les tocaría a ellos.',
        'En 1853 cuatro buques de guerra estadounidenses entraron en la bahía que hay junto a Tokio. Dos eran de vapor, lo que quería decir que podían ir a donde quisieran incluso contra el viento — y ningún barco de Japón podía hacer eso. Los americanos entregaron una carta exigiendo un acuerdo comercial y dijeron que volverían a por la respuesta.',
        'Japón tuvo que firmar. Y el acuerdo era injusto: los extranjeros que cometieran delitos en Japón los juzgaban jueces de su propio país, y Japón no podía decidir sus propios impuestos sobre las importaciones.',
        'Algunos guerreros japoneses decidieron echar a los extranjeros por la fuerza. Lo intentaron. Los buques de guerra occidentales les aplastaron los fuertes. Así que cambiaron de idea del todo y dijeron: vale, si no podemos ganarles, aprenderemos todo lo que saben.',
        'Y lo hicieron. Tomaron el gobierno, construyeron ferrocarriles y fábricas y escuelas y una armada moderna, e incluso se deshicieron de la clase guerrera a la que ellos mismos pertenecían, porque los ejércitos modernos no funcionan así. Cuarenta y tres años después consiguieron por fin que anularan aquellos acuerdos injustos.',
        'Y luego, por desgracia, Japón le hizo a Corea y a Taiwán casi exactamente lo que tanto miedo le había dado que le hicieran a él.',
      ],
    },
    {
      id: 'scholar',
      label: 'Nivel universitario',
      kind: 'age',
      paragraphs: [
        'La historiografía se ha desplazado decididamente de la ruptura hacia la continuidad. El encuadre antiguo —una sociedad feudal y aislada transformada por un choque externo— ha dado paso a relatos que subrayan los cimientos Tokugawa: comercialización y protoindustrialización, una economía rural monetizada, tasas de alfabetización iguales o superiores a las europeas de la época, y el canal *rangaku* manteniendo el contacto con la ciencia occidental. La reforma Meiji se lee así mejor como reorientación de una capacidad existente que como construcción desde una base baja, lo que también explica su velocidad inverosímil.',
        'Sobre la causalidad, el análisis político de Beasley sigue siendo fundacional: la crisis *bakumatsu* se entiende mejor como crisis de legitimación, en la que los tratados destruyeron la pretensión del shogunato sobre el *taisei* al demostrar su incapacidad para cumplir la función defensiva en que descansaba esa pretensión. El movimiento *sonnō jōi* funciona menos como ideología coherente que como vocabulario para afirmar la autoridad de la corte frente al bakufu, y por eso sus partidarios pudieron abandonar del todo el *jōi* después de 1864 sin apuro ideológico.',
        'El objetivo de la revisión de los tratados merece más centralidad de la que le dan los relatos generales. La secuencia de las reformas sigue de cerca los requisitos diplomáticos: los códigos de Boissonade y los posteriores de influencia alemana responden directamente a la justificación de la extraterritorialidad; la constitución de 1889 y la Dieta de 1890 aportan el criterio de Estado constitucional; el tratado Aoki-Kimberley de 1894 y su aplicación en 1899, seguidos de la recuperación arancelaria en 1911, cierran el programa. Leer la política Meiji como occidentalización genérica pierde de vista la instrumentalidad.',
        'La disolución del estamento samurái es el caso más claro de la historia moderna de una élite desmontando sus propios privilegios legales, y el mecanismo merece atención: el *chitsuroku shobun* conmutó los estipendios en bonos con interés, convirtiendo un pasivo fiscal de en torno a un tercio del gasto público en una deuda manejable y creando a la vez un estrato rentista que capitalizó en parte la banca temprana. La coacción y la compensación fueron de la mano, y la Rebelión de Satsuma marca el límite de lo que la compensación podía absorber.',
        'Por último, la continuidad entre modernización defensiva y expansión imperial no debería tratarse como epílogo moral sino como problema analítico. La previsión del arreglo de 1889 de que el mando militar respondiera directamente al trono, la lógica estratégica de la «línea de ventaja» formulada por Yamagata y la adquisición de Taiwán y Corea se siguen todas del mismo proyecto de construcción estatal. Cualquier relato que trate el imperialismo japonés como una desviación de los propósitos Meiji tiene que explicar por qué las instituciones se construyeron como se construyeron.',
      ],
    },
    {
      id: 'the-objective',
      label: 'Trabajar hacia atrás desde un tratado',
      kind: 'angle',
      paragraphs: [
        'Las reformas Meiji parecen un programa general de occidentalización. No lo eran. Eran una lista de requisitos para un resultado concreto, y cada punto puede rastrearse hasta un argumento que esgrimían las potencias extranjeras.',
        '**Decían: vuestro sistema jurídico no es civilizado, así que nuestros ciudadanos no pueden ser juzgados en él.** Japón encargó a juristas europeos, escribió un código penal, uno civil y uno mercantil, y reorganizó sus tribunales. Esa es la respuesta directa a la justificación declarada de la extraterritorialidad.',
        '**Decían: no sois un Estado constitucional.** Japón promulgó una constitución en 1889 y abrió un parlamento nacional en 1890, el primero de Asia. Para lo que fuera además, eliminó un argumento.',
        '**Y decían, implícitamente: no podéis hacer cumplir nada.** Así que Japón construyó un ejército de modelo prusiano, una armada en buena parte en astilleros británicos, una red ferroviaria, un sistema telegráfico, un impuesto nacional sobre la tierra y escolarización obligatoria. Un Estado capaz de recaudar, reclutar, moverse y comunicarse es un Estado con el que otros Estados negocian.',
        '**Y el calendario demuestra la intención.** El tratado revisado con Gran Bretaña se firmó en 1894 y entró en vigor en 1899, acabando con la jurisdicción consular. La autonomía arancelaria volvió en 1911. Y entonces la intensidad del programa reformista baja de forma perceptible, porque el objetivo se había alcanzado.',
        'Cuarenta y tres años, una aristocracia abolida, un impuesto pesado sobre los campesinos y una guerra civil — para anular dos documentos. Es uno de los ejercicios de estadística dirigida a un fin más sostenidos que existen, y el fin fue siempre legible.',
      ],
    },
    {
      id: 'china-and-japan',
      label: 'La misma presión, dos respuestas',
      kind: 'contrast',
      paragraphs: [
        'China y Japón se toparon con el mismo problema con unos quince años de diferencia, y el atlas cuenta las dos historias. La comparación es el asunto.',
        '**China, desde 1839.** Un imperio enorme y seguro de sí mismo, con una burocracia sofisticada, derrotado en dos guerras y obligado a aceptar puertos de tratado, indemnizaciones, extraterritorialidad y aranceles fijados. Los intentos de reforma —el Movimiento de Autofortalecimiento— compraron barcos y arsenales pero no pudieron reorganizar el Estado a su alrededor, porque los intereses que habría habido que romper eran los intereses que dirigían el país.',
        '**Japón, desde 1853.** Un país más pequeño, más pobre y más descentralizado, con un gobierno que se hundió casi de inmediato bajo la misma presión. Ese hundimiento es la diferencia crucial: produjo un grupo dirigente nuevo sin ninguna participación en los arreglos antiguos, salido de dominios excluidos del poder durante doscientos cincuenta años y, por tanto, dispuesto a abolir instituciones que el régimen anterior no habría podido tocar.',
        '**La lectura incómoda** es que la ventaja de Japón fue en parte que su viejo orden falló deprisa. El Estado imperial chino era lo bastante fuerte para sobrevivir al golpe y estaba demasiado enredado para reconstruirse; la dinastía tardó hasta 1911 en caer, y para entonces el sistema de tratados llevaba setenta años en pie.',
        'Los dos países acabaron produciendo un Estado moderno. Uno lo hizo en cuarenta años y consiguió anular los tratados; el otro tardó un siglo y llamó al periodo intermedio el Siglo de la Humillación. La diferencia no fue de inteligencia, ni de cultura, ni de voluntad. Fue sobre todo qué instituciones había que destruir primero, y si alguien estaba en condiciones de destruirlas.',
      ],
    },
  ],

  beforeAfter: {
    label: 'Japón, antes y después',
    before: {
      title: 'En 1853',
      points: [
        'Un shogun gobernando a través de 260 dominios semiautónomos',
        'Una clase guerrera hereditaria de unos dos millones con estipendios',
        'Contacto exterior filtrado por Nagasaki y unos pocos márgenes',
        'Ni ejército nacional, ni armada, ni moneda, ni impuesto directo',
        'Tratados impuestos a punta de cañón en menos de un año',
      ],
    },
    after: {
      title: 'En 1911',
      points: [
        'Un Estado centralizado con prefecturas y función pública nacional',
        'Un ejército de reclutas y una armada moderna, y ningún samurái',
        'Embajadas, una constitución, un parlamento y un código legal',
        'Ferrocarriles, telégrafo, escolarización obligatoria e industria',
        'Los tratados desiguales anulados, y un imperio propio',
      ],
    },
  },

  whatIf: [
    {
      question: '¿Y si el shogunato hubiera sobrevivido y dirigido él mismo las reformas?',
      reasoning: 'El gobierno Tokugawa ya estaba reformando en la década de 1860: mandaba estudiantes al extranjero, compraba buques de guerra y construía un arsenal en Yokosuka con ayuda francesa. Un shogunato que se modernizara con éxito habría producido otro Japón: más descentralizado, con los dominios y la clase samurái intactos, y bastante probablemente más lento en abolir los arreglos que estorbaban.',
      constraint: 'Y ese es justamente el problema, y por eso el escenario es dudoso. Los Tokugawa no podían abolir los dominios, porque los dominios eran la base de su propia autoridad, y no podían abolir a los samuráis, porque los samuráis eran su clientela. El Movimiento de Autofortalecimiento chino es el ejemplo real más cercano de un Estado intentando modernizarse sin romper los intereses que lo bloqueaban.',
    },
    {
      question: '¿Y si Japón hubiera recuperado la autonomía arancelaria en la década de 1870?',
      reasoning: 'Los aranceles bajos y fijos impidieron a Japón proteger a sus industrias nacientes durante cuatro décadas, y el retraso es una queja recurrente en la historia económica. Una autonomía arancelaria temprana podría haber acelerado la industrialización y desplazado el equilibrio de la seda de exportación hacia la industria pesada bastante antes.',
      constraint: 'También es posible que la restricción ayudara: incapaz de proteger, Japón compitió en costes y en absorber técnica extranjera, y la presión fiscal forzó la reforma del impuesto sobre la tierra que dio al Estado su base de ingresos. El escenario elimina a la vez la desventaja y la disciplina, y no hay manera de decir cuál pesó más.',
    },
  ],

  quiz: [
    {
      question: '¿Cómo supo Japón lo que venía antes de que llegara Perry?',
      options: [
        'Por espías en Pekín',
        'Por informes holandeses en Nagasaki que describían la derrota china en la Guerra del Opio',
        'Se lo advirtió un embajador británico',
        'No lo supo: Perry fue una sorpresa total',
      ],
      answerIndex: 1,
      explains: 'Los holandeses de Nagasaki presentaban informes anuales de inteligencia. Edo se enteró de la derrota china y revocó su orden de disparar a los barcos extranjeros en 1842, once años antes de Perry.',
    },
    {
      question: '¿En qué se convirtió el movimiento para «expulsar a los bárbaros»?',
      options: [
        'En una campaña exitosa para volver a cerrar Japón',
        'En el movimiento modernizador más decidido de Japón',
        'En un renacimiento religioso',
        'En un levantamiento campesino',
      ],
      answerIndex: 1,
      explains: 'Después de que Satsuma y Chōshū intentaran la expulsión y les bombardearan Kagoshima y Shimonoseki en 1863-64, esos mismos dirigentes concluyeron que adquirir capacidad occidental era la única vía hacia la seguridad.',
    },
    {
      question: '¿Quién abolió la clase samurái?',
      options: [
        'Los estadounidenses, como condición del tratado',
        'El shogun, antes de 1868',
        'El gobierno Meiji, compuesto íntegramente por samuráis',
        'Una revolución campesina',
      ],
      answerIndex: 2,
      explains: 'Entre 1871 y 1876 los samuráis del gobierno acabaron con los dominios, introdujeron el reclutamiento de plebeyos, conmutaron los estipendios hereditarios en bonos y prohibieron la espada, disolviendo su propia clase.',
    },
    {
      question: '¿Cuál era el objetivo central de las reformas Meiji?',
      options: [
        'Volverse culturalmente occidentales',
        'Conquistar China',
        'Conseguir que anularan los tratados desiguales',
        'Devolver el poder real al emperador',
      ],
      answerIndex: 2,
      explains: 'Toda reforma importante puede rastrearse hasta un requisito para revisar los tratados. La extraterritorialidad terminó en 1899 y la autonomía arancelaria se recuperó en 1911: cuarenta y tres años de trabajo sobre un solo objetivo.',
    },
  ],

  sources: [
    {
      id: 'kanagawa-1854',
      kind: 'primary',
      author: 'The United States and the Tokugawa shogunate',
      title: 'The Convention of Kanagawa',
      year: 1854,
      detail: 'Firmado el 31 de marzo de 1854; texto en los US Statutes at Large y en las colecciones diplomáticas japonesas',
      note: 'El primer tratado. Modesto en apariencia —dos puertos, náufragos, un cónsul— y la apertura que hizo inevitable el tratado comercial de 1858.',
    },
    {
      id: 'perry-narrative-1856',
      kind: 'primary',
      author: 'Francis L. Hawks, from the notes of Matthew C. Perry',
      title: 'Narrative of the Expedition of an American Squadron to the China Seas and Japan',
      year: 1856,
      detail: 'Publicado por orden del Congreso de Estados Unidos, Washington, 1856, en tres volúmenes',
      note: 'El relato oficial estadounidense, y un documento sobre cómo quería entenderse la expedición a sí misma. Léase tanto por la intención como por los hechos.',
    },
    {
      id: 'charter-oath-1868',
      kind: 'primary',
      author: 'The Meiji government',
      title: 'The Charter Oath (Gokajō no Goseimon)',
      year: 1868,
      detail: 'Promulgado el 6 de abril de 1868; traducción de referencia en «Sources of Japanese Tradition», Columbia University Press',
      note: 'Cinco artículos, una página. El quinto —buscar el conocimiento por todo el mundo— resulta describir con exactitud los cuarenta años siguientes de política.',
    },
    {
      id: 'iwakura-1878',
      kind: 'primary',
      author: 'Kume Kunitake',
      title: 'Beiō kairan jikki (A True Account of the Ambassador Extraordinary’s Journey through America and Europe)',
      year: 1878,
      detail: 'Cinco volúmenes, Tokio, 1878; trad. como «The Iwakura Embassy 1871–1873», Japan Documents, 2002',
      note: 'El acta oficial de la misión de estudio de veintidós meses, escrita por su secretario. Lo que pensó medio gobierno japonés al mirar Occidente de frente.',
    },
    {
      id: 'beasley-1972',
      kind: 'book',
      author: 'W. G. Beasley',
      title: 'The Meiji Restoration',
      year: 1972,
      detail: 'Stanford University Press. ISBN 978-0-8047-0815-0',
      note: 'El análisis político de referencia sobre cómo cayó el shogunato y quién lo sustituyó. Muy fuerte en la crisis de legitimidad y en la política de los dominios.',
    },
    {
      id: 'jansen-2000',
      kind: 'book',
      author: 'Marius B. Jansen',
      title: 'The Making of Modern Japan',
      year: 2000,
      detail: 'Harvard University Press. ISBN 978-0-674-00334-7',
      note: 'El gran panorama desde los Tokugawa hasta el siglo XX, y la fuente de la insistencia de esta historia en la continuidad frente al milagro.',
    },
    {
      id: 'gordon-2003',
      kind: 'book',
      author: 'Andrew Gordon',
      title: 'A Modern History of Japan: From Tokugawa Times to the Present',
      year: 2003,
      detail: 'Oxford University Press. ISBN 978-0-19-511060-7',
      note: 'Especialmente bueno sobre quién pagó la transformación: el impuesto sobre la tierra, las protestas rurales y el coste social de las reformas.',
    },
  ],
}
