import type { Story } from '../../types'

export const opiumWarsEs: Story = {
  slug: 'opium-wars',
  title: 'Una guerra para seguir vendiendo una droga',
  subtitle: 'Las Guerras del Opio — cómo el gusto por el té acabó en cañoneros.',
  hook: 'Gran Bretaña fue a la guerra contra China porque no podía dejar de beber té, y encontró una sola cosa que China le compraría a cambio: opio.',
  era: 'industrial',
  category: 'milestones',
  years: [1839, 1860],
  regions: ['China', 'Gran Bretaña', 'India'],
  nodes: ['opium-wars', 'opium-trade', 'tea-trade', 'east-india-company', 'hong-kong'],
  tags: ['trade', 'empire', 'drugs', 'economics', 'china', 'britain'],
  readingMinutes: 11,
  reviewed: '2026-08-03',
  mood: 'ember',

  reel: [
    { beat: 'hook', punch: true, text: 'Un imperio fue a la guerra para seguir vendiendo una droga, y a la guerra la llamó otra cosa.' },
    { beat: 'hook', text: 'Empieza con el té.' },
    { beat: 'worldBefore', kicker: '1750', text: 'China hace la mejor seda, la mejor porcelana y el mejor té de la tierra,' },
    { beat: 'worldBefore', text: 'y no quiere nada que Gran Bretaña pueda meter en un barco a cambio —' },
    { beat: 'worldBefore', text: 'ni la lana, ni los relojes, ni el hierro.' },
    { beat: 'worldBefore', punch: true, text: 'Hay una sola cosa que sí acepta. Plata.' },
    { beat: 'problem', text: 'Así que la plata va al este y el té al oeste, y cada año' },
    { beat: 'problem', mark: 'drain', text: 'un poco más del dinero británico se queda en Cantón y no vuelve,' },
    { beat: 'problem', text: 'mientras el impuesto del té es lo que paga la armada.' },
    { beat: 'problem', text: 'Gran Bretaña necesita una sola cosa que China quiera comprar,' },
    { beat: 'story', punch: true, text: 'y ya la cultiva, en la India. Opio.' },
    { beat: 'story', text: 'China lo prohibió en 1729, y eso no es el obstáculo —' },
    { beat: 'story', punch: true, text: 'es la razón de que el precio esté tan bien.' },
    { beat: 'story', text: 'La Compañía cultiva el opio, subasta los cajones en Calcuta' },
    { beat: 'story', text: 'y deja que otros hagan el contrabando.' },
    { beat: 'story', kicker: '1838', mark: 'spike', text: 'Cuarenta mil cajones al año, hacia un país donde es ilegal,' },
    { beat: 'story', kicker: '1839', text: 'hasta que China manda a su funcionario más insobornable a acabar con ello.' },
    { beat: 'story', text: 'Lin Zexu destruye mil toneladas y le escribe a la reina Victoria,' },
    { beat: 'story', text: 'y le pregunta cómo un país que prohíbe el opio en casa puede mandarlo fuera.' },
    { beat: 'story', punch: true, text: 'Nadie sabe si ella llegó a leerlo.' },
    { beat: 'whyItHappened', text: 'Entonces un funcionario en Cantón les promete a los contrabandistas' },
    { beat: 'whyItHappened', text: 'que la Corona cubrirá todo lo que han perdido,' },
    { beat: 'whyItHappened', punch: true, mark: 'reversal', text: 'y en una tarde una deuda de droga se vuelve una deuda nacional,' },
    { beat: 'whyItHappened', punch: true, text: 'porque una deuda es mucho más fácil de defender que una droga.' },
    { beat: 'whyItHappened', kicker: '1840', text: 'El Parlamento vota la guerra por nueve votos.' },
    { beat: 'consequences', text: 'Gran Bretaña no marcha sobre Pekín — corta el canal que lo alimenta,' },
    { beat: 'consequences', kicker: '1842', text: 'y se lleva cinco puertos, una indemnización enorme y una isla rocosa' },
    { beat: 'consequences', punch: true, text: 'que en Londres nadie creía que valiera gran cosa. Hong Kong.' },
    { beat: 'consequences', text: 'El tratado no menciona el opio ni una vez.' },
    { beat: 'whyItMatters', punch: true, text: 'China llama Humillación al siglo que sigue, y sigue respondiendo a 1840.' },
  ],

  beats: {
    worldBefore: {
      heading: 'El mundo de antes',
      paragraphs: [
        'En 1750, China no era un país que necesitara nada de Europa.',
        'Hacía la mejor seda del mundo. Hacía una porcelana tan buena que los europeos pasaron doscientos años fracasando al copiarla. Y cultivaba té — que Gran Bretaña acababa de descubrir que no podía dejar de beber.',
        'Así que el comercio iba en una sola dirección. Los barcos británicos llegaban al puerto de Cantón, en el sur, y ofrecían lana, relojes y hierro. Los mercaderes chinos miraban la lana y declinaban con cortesía. En Cantón no llueve igual. Casi nada de lo que Gran Bretaña fabricaba le interesaba a China.',
        'Había una cosa que China sí aceptaba: plata.',
        'Y eso fue lo que pasó durante más de un siglo. Los barcos británicos salían al este cargados de plata y volvían cargados de té. Cada año se marchaba más plata. Cada año llegaba más té. En Gran Bretaña el té dejó de ser un lujo y se convirtió en el desayuno.',
      ],
      aside: {
        kind: 'analogy',
        label: 'Imagínalo así',
        body: 'Piensa en una tienda de tu calle que vende lo único que toda tu familia bebe cada mañana — y que se niega a comprarte nada de lo que tú haces. Cada mes entregas dinero y no recibes de vuelta más que la bebida. Eso va bien, hasta que te das cuenta de que el dinero se está acabando.',
      },
      sourceIds: ['platt-2018', 'lovell-2011'],
    },

    problem: {
      heading: 'El problema',
      paragraphs: [
        'La Gran Bretaña del siglo XVIII creía algo que hoy suena extraño: que un país se hacía rico reteniendo plata y oro, y pobre dejándolos salir. El comercio no era un intercambio. Era una pelea, y Gran Bretaña la perdía todos los años frente a un país contra el que nunca había combatido.',
        'Y no era solo una teoría de libro. El impuesto sobre el té era una de las fuentes de dinero más fiables del Estado británico. Con él se pagaban buques de guerra. Un comercio que vaciaba el tesoro para financiar el tesoro no era un arreglo estable.',
        'Mientras tanto el propio comercio funcionaba con reglas chinas, y las reglas eran estrictas. Los extranjeros podían comerciar en un solo puerto —Cantón— y únicamente a través de un grupo autorizado de casas mercantiles chinas. No podían aprender chino con un maestro oficial. No podían llevar a sus esposas. No podían quedarse durante el invierno. No podían hablar directamente con el gobierno, solo elevarle peticiones.',
        'A los mercaderes británicos aquello les parecía un insulto. Para los Qing era simple administración: un imperio grande gestionando un comercio pequeño y lejano en su borde, igual que gestionaba todo lo demás.',
        'Lo que Gran Bretaña necesitaba era algo —cualquier cosa— que los compradores chinos quisieran tanto como Gran Bretaña quería el té.',
        'La Compañía de las Indias Orientales ya lo cultivaba.',
      ],
      aside: {
        kind: 'caution',
        label: 'No era «cerrada al mundo»',
        body: 'El sistema de Cantón suele describirse como China encerrándose. No lo era. Era un comercio regulado, en funcionamiento y extremadamente rentable — con condiciones fijadas por el país anfitrión, como suelen fijarse las condiciones comerciales. Parecía aislamiento sobre todo a quienes no podían fijarlas.',
      },
      sourceIds: ['platt-2018', 'lovell-2011'],
    },

    story: {
      heading: 'La historia',
      paragraphs: [
        'El opio no era nuevo en China. Llevaba siglos usándose como medicina, y el Estado chino había prohibido fumarlo ya en 1729 — mucho antes de que Gran Bretaña tuviera nada que ver.',
        'Lo nuevo era la escala.',
        'La Compañía de las Indias Orientales tenía el monopolio del opio cultivado en Bengala y Bihar, en la India. Campesinos con licencia de la Compañía cultivaban la adormidera. Las fábricas de la Compañía convertían la pasta en cajones. Y entonces la Compañía hacía algo cuidadoso: no metía ella misma el opio de contrabando en China. Subastaba los cajones en Calcuta a comerciantes privados y dejaba que lo hicieran ellos.',
        'Esa distancia importaba. Significaba que la Compañía podía conservar su comercio legal en Cantón mientras su producto llegaba a las ensenadas chinas a bordo del barco de otro. Todo el mundo lo sabía. El papeleo estaba limpio.',
        'Las cifras dejaron de ser pequeñas. Hacia 1800 llegaban a China unos pocos miles de cajones al año. En 1838 eran unos cuarenta mil — bastante más de dos mil toneladas de opio procesado en un solo año, entrando en un país donde era ilegal.',
        'Y la plata dio media vuelta. Empezó a salir *de* China para pagarlo.',
        'En marzo de 1839 el emperador Daoguang envió a Cantón a un funcionario llamado Lin Zexu con la orden de acabar con el comercio para siempre. Lin no era un exaltado. Era el administrador más respetado de su generación, elegido precisamente porque no se le podía comprar.',
        'Rodeó los almacenes extranjeros, cortó los suministros y se negó a moverse hasta que le entregaran el opio. Lo consiguió: 20.283 cajones. Entonces hizo algo que nadie esperaba. En vez de quemarlo —al quemarlo queda un residuo que merece la pena robar— mandó cavar zanjas en Humen, mezcló el opio con sal y cal, lo dejó disolverse durante semanas y arrojó unas mil toneladas al mar. Escribió una disculpa a los dioses del mar por la contaminación.',
        'También escribió a la reina Victoria. La carta hacía una pregunta sencilla: el opio está prohibido también en su país, así que ¿cómo puede permitir que sus súbditos traigan al mío lo que usted no permite en casa? No hay pruebas de que llegara nunca a sus manos.',
        'Aquí la historia gira sobre la decisión de un solo hombre. Charles Elliot, superintendente británico de comercio, había ordenado a los mercaderes entregar su opio — pero les prometió que el gobierno británico se lo pagaría. En una tarde, una pérdida privada de contrabandistas se convirtió en una deuda pública de la Corona. Londres tenía ahora una factura que nunca había aceptado, con acreedores furiosos y excelentes grupos de presión.',
        'En abril de 1840 el Parlamento discutió el asunto durante tres días. Un joven William Gladstone se levantó y dijo que no conocía una guerra más injusta en su origen ni más calculada para cubrir a su país de deshonra permanente. La moción de censura al gobierno se rechazó por nueve votos: 271 contra 262.',
        'La flota ya iba navegando.',
        'Lo que siguió fue menos una guerra que una demostración. China tenía un ejército grande, pero repartido por una frontera terrestre enorme y diseñado para otra clase de amenaza. Gran Bretaña llegó con algo a lo que China no tenía respuesta en el agua: el *Nemesis*, un vapor de casco de hierro que calaba tan poco que podía remontar ríos, y al que le daba igual de dónde soplara el viento.',
        'Los británicos no marcharon sobre Pekín. Hicieron algo más discreto y mucho más eficaz — remontaron el Yangtsé en 1842 y cortaron el Gran Canal, la arteria que llevaba grano a la capital. Se podía matar de hambre a Pekín sin disparar un tiro contra ella.',
        'Los Qing pidieron la paz. El 29 de agosto de 1842, a bordo de un buque de guerra británico fondeado en Nankín, unos funcionarios firmaron un tratado que abría cinco puertos, suprimía el monopolio mercantil, fijaba aranceles del gusto británico, pagaba una indemnización de veintiún millones de dólares de plata y entregaba a Gran Bretaña una isla rocosa y poco poblada con un puerto de aguas profundas magnífico: Hong Kong.',
        'El tratado no menciona el opio ni una sola vez.',
        'Catorce años después volvió a pasar. Las autoridades británicas en Cantón usaron el abordaje de un barco de propiedad china matriculado en Hong Kong —el *Arrow*— como motivo para una segunda guerra, esta vez con Francia al lado. Terminó en 1860 con tropas extranjeras en Pekín, la península de Kowloon añadida a Hong Kong, un emperador en fuga y el Antiguo Palacio de Verano saqueado y quemado por orden de lord Elgin.',
        'Esta vez los tratados legalizaron el comercio de opio sin rodeos.',
      ],
      aside: {
        kind: 'voice',
        label: 'Lin Zexu a la reina Victoria, 1839',
        body: '«Preguntemos: ¿dónde está vuestra conciencia? He oído que en vuestro país está estrictamente prohibido fumar opio… Si no se permite hacer daño a vuestro propio país, menos aún deberíais dejar que se transmita en daño de otros países.»',
        sourceId: 'lin-1839',
      },
      sourceIds: ['lovell-2011', 'platt-2018', 'hansard-1840', 'nanking-1842'],
    },

    whyItHappened: {
      heading: 'Por qué pasó',
      paragraphs: [
        'Es tentador decir que Gran Bretaña fue a la guerra para vender droga. Es casi cierto, pero se salta la maquinaria — y la maquinaria es la parte interesante.',
        '**El dinero tenía que volver.** El té no era una moda; era una base fiscal. Un comercio que solo iba hacia fuera no podía durar siempre, y a nadie en Londres se le ocurría un producto legítimo que lo invirtiera.',
        '**Nadie tenía que sentirse responsable.** La Compañía cultivaba el opio y lo vendía en subasta, y luego se lavaba las manos. Comerciantes privados lo transportaban. Contrabandistas chinos lo desembarcaban. A funcionarios chinos se les pagaba por mirar hacia otro lado. Una cadena de decisiones pequeñas y negables producía un resultado del que ninguna persona tenía que hacerse cargo.',
        '**Una deuda del Estado convirtió un delito en una causa.** La promesa de Elliot es la bisagra. Antes de ella, Gran Bretaña defendía a contrabandistas. Después, defendía el Tesoro — y eso sí es un argumento que un Parlamento vota.',
        '**El «libre comercio» era una creencia sincera, y muy conveniente.** Muchos diputados votaron convencidos de que defendían el comercio abierto y la dignidad nacional frente a un trato arbitrario. Que el comercio en cuestión fuera narcótico de contrabando era, para ellos, un detalle. Los motivos pueden ser sinceros e interesados a la vez.',
        '**Y la tecnología había cambiado sin ruido.** En 1793 Gran Bretaña no habría podido ganar esta guerra. En 1839, el vapor, los cascos de hierro y la artillería industrial hacían que una fuerza pequeña pudiera imponer condiciones al mayor imperio de la tierra. La Revolución Industrial no solo construyó fábricas. Cambió lo que merecía la pena intentar.',
      ],
      sourceIds: ['platt-2018', 'lovell-2011', 'hansard-1840'],
    },

    consequences: {
      heading: 'Qué cambió',
      paragraphs: [
        'Los resultados inmediatos se escribieron en un tratado. Los duraderos se escribieron en cómo una quinta parte de la humanidad entiende su propio pasado.',
      ],
      shortTerm: [
        'Cinco puertos chinos se abrieron al comercio y a la residencia extranjera, y la isla de Hong Kong pasó a Gran Bretaña — a la que se sumó Kowloon en 1860.',
        'Una indemnización de veintiún millones de dólares de plata, además de la carga destruida, se cargó a un tesoro ya tensionado.',
        'Los extranjeros en China pasaron a responder ante sus propios cónsules y no ante los tribunales chinos — la extraterritorialidad, concedida en el tratado suplementario de 1843.',
        'A Lin Zexu, que había hecho exactamente lo que se le ordenó, se le culpó de la derrota y se le desterró al lejano noroeste.',
      ],
      longTerm: [
        'El Tratado de Nankín se convirtió en plantilla. En el siglo siguiente Francia, Estados Unidos, Rusia, Alemania y Japón negociaron sus propias versiones — los «tratados desiguales».',
        'El opio se legalizó después de 1860, y las importaciones siguieron subiendo hasta que el cultivo interno chino las superó del todo. A finales del siglo XIX el mayor proveedor de opio a China era China.',
        'El Estado Qing pasó sus setenta años restantes pagando indemnizaciones y combatiendo rebeliones con un tesoro que no se recuperaba, y cayó en 1912.',
        'Hong Kong, tomada como puerto y despachada en Londres como una roca yerma, se convirtió en una de las ciudades más ricas del mundo — y se devolvió en 1997.',
      ],
      unexpected: [
        'La guerra produjo el relato fundacional de la China moderna. El periodo que arranca en 1839 se enseña allí como el «Siglo de la Humillación», y sigue siendo un elemento vivo de la política exterior china — un país al que trocearon una vez tiende a fijarse cuando le piden abrirse otra vez.',
        'El propio movimiento antiopio británico salió del escándalo, y el Parlamento acabó volviéndose contra el comercio por el que había luchado — el tráfico de opio entre la India y China se desmanteló a principios del siglo XX.',
        'La idea de que una potencia extranjera pudiera fijar sin más los aranceles de otro país marcó cómo construyó China su Estado después, y por qué el control de su propia economía se volvió innegociable.',
        'El té se escapó. Gran Bretaña, harta de depender de China, hizo que cazadores de plantas lo sacaran de contrabando y lo establecieran en Assam y Ceilán — y por eso el «té británico» viene hoy sobre todo de la India y Sri Lanka.',
      ],
      sourceIds: ['lovell-2011', 'nanking-1842', 'platt-2018'],
    },

    whyItMatters: {
      heading: 'Por qué sigue importando',
      paragraphs: [
        'Cada vez que China se niega a dejar que una empresa extranjera opere en términos extranjeros, o reacciona con dureza a los sermones sobre abrir sus mercados, está respondiendo a una pregunta que le planteó por primera vez una flota en 1840.',
        'No es una metáfora. Los escolares chinos aprenden que la era moderna empieza aquí. La entrega de Hong Kong en 1997 se presentó en casa no como un traspaso administrativo sino como el cierre de una herida abierta en 1842. La palabra que se usa no es «adquisición». Es «retorno».',
        'Y hay una segunda lección, menos cómoda, que no tiene nada que ver con China. Este fue un imperio de la droga construido enteramente con instituciones respetables: una compañía con carta real, campesinos con licencia, una casa de subastas, seguros, una armada y una votación parlamentaria. Nadie en la cadena se veía a sí mismo como un criminal. Cada paso era el trabajo corriente de alguien.',
        'Así es como suelen organizarse de verdad los grandes daños. No con villanos — con papeleo.',
      ],
      sourceIds: ['lovell-2011'],
    },
  },

  timeline: [
    { year: 1637, title: 'Los primeros barcos británicos llegan a Cantón', detail: 'Llegan casi sin nada que China quiera comprar, y el patrón queda fijado.' },
    { year: 1729, title: 'China prohíbe fumar opio', detail: 'El emperador Yongzheng prohíbe la venta y el consumo de opio — un siglo antes del pico del comercio.', pivotal: true },
    { year: 1757, title: 'Se formaliza el sistema de Cantón', detail: 'El comercio exterior queda confinado a un puerto y canalizado por casas mercantiles chinas con licencia.' },
    { year: 1773, title: 'La Compañía toma el monopolio del opio de Bengala', detail: 'Controla la producción y luego subasta los cajones a comerciantes privados que los llevan a China.', pivotal: true },
    { year: 1793, title: 'Fracasa la embajada Macartney', detail: 'Gran Bretaña pide comercio abierto y un embajador residente. El emperador Qianlong declina, señalando que a China no le falta de nada.' },
    { year: 1834, title: 'Termina el monopolio chino de la Compañía', detail: 'El comercio se abre a todos los mercaderes británicos, y el volumen de opio de contrabando sube con fuerza.' },
    { year: 1839, date: '1839-03', title: 'Lin Zexu llega a Cantón', detail: 'Enviado por el emperador Daoguang con la orden de acabar con el comercio del opio para siempre.', pivotal: true },
    { year: 1839, date: '1839-06-03', title: 'El opio se destruye en Humen', detail: '20.283 cajones confiscados se disuelven en sal y cal y se arrojan al mar a lo largo de veintitrés días.', pivotal: true },
    { year: 1839, title: 'Elliot promete una indemnización', detail: 'El superintendente británico de comercio garantiza a los mercaderes el pago del gobierno, y convierte una pérdida privada en deuda de la Corona.', pivotal: true },
    { year: 1840, date: '1840-04', title: 'Vota el Parlamento', detail: 'Tras tres días de debate, y el discurso de Gladstone en contra, la moción de censura cae 271 a 262. La flota ya está en el mar.' },
    { year: 1841, title: 'El Nemesis cambia la guerra', detail: 'Un vapor de casco de hierro y poco calado permite a Gran Bretaña combatir río arriba, sin depender del viento ni de la marea.' },
    { year: 1842, date: '1842-07', title: 'Se corta el Gran Canal', detail: 'Las fuerzas británicas seccionan la ruta del grano hacia Pekín. Se puede matar de hambre a la capital sin atacarla.', pivotal: true },
    { year: 1842, date: '1842-08-29', title: 'El Tratado de Nankín', detail: 'Cinco puertos abiertos, una indemnización de veintiún millones de dólares de plata, Hong Kong cedida. El opio no se menciona.', pivotal: true },
    { year: 1843, title: 'Extraterritorialidad', detail: 'El tratado suplementario de la Bogue exime a los súbditos británicos de la ley china y añade la cláusula de nación más favorecida.' },
    { year: 1856, title: 'El incidente del Arrow', detail: 'El abordaje de un barco de propiedad china matriculado en Hong Kong sirve de pretexto para una segunda guerra, con Francia sumándose.' },
    { year: 1860, date: '1860-10', title: 'Pekín ocupada, el Palacio de Verano quemado', detail: 'La Convención de Pekín legaliza el opio, cede Kowloon y abre más puertos. El Yuanmingyuan se destruye por orden de Elgin.', pivotal: true },
    { year: 1997, title: 'Hong Kong vuelve a China', detail: 'Presentado en Pekín como el cierre del periodo que empezó en 1839.' },
  ],

  causeEffect: [
    { cause: 'Gran Bretaña se aficiona al té', effect: 'La plata se drena hacia el este año tras año', because: 'China aceptaba el pago en plata y apenas le interesaban las manufacturas británicas.' },
    { cause: 'Un déficit comercial permanente', effect: 'La Compañía monta una industria del opio en la India', because: 'Era el único producto bajo control británico que los compradores chinos pagarían en cantidad.' },
    { cause: 'El opio llega en volumen', effect: 'El flujo de plata se invierte y China aprieta su prohibición', because: 'Las importaciones ya eran lo bastante grandes como para alterar la moneda y alarmar al Estado.' },
    { cause: 'Lin Zexu destruye el opio confiscado', effect: 'Elliot garantiza a los mercaderes una indemnización del gobierno', because: 'Sin esa garantía los mercaderes no habrían entregado la carga que él se había comprometido a dar.' },
    { cause: 'Una pérdida privada se vuelve deuda de la Corona', effect: 'El Parlamento vota la guerra por nueve votos', because: 'Defender el Tesoro y la dignidad nacional es un caso que un diputado puede defender; defender contrabandistas no.' },
    { cause: 'Gran Bretaña gana en el mar y corta el Gran Canal', effect: 'Los Qing aceptan las condiciones en seis semanas', because: 'El punto vulnerable era el suministro de grano de Pekín, no su ejército.' },
    { cause: 'El Tratado de Nankín sienta precedente', effect: 'Sigue un siglo de tratados desiguales', because: 'Las demás potencias tenían ya una plantilla y una cláusula de nación más favorecida para copiarla.' },
  ],

  myths: [
    {
      myth: 'Gran Bretaña introdujo el opio en China.',
      reality: 'El opio llevaba siglos en China como medicina, y fumarlo ya estaba prohibido en 1729. Lo que Gran Bretaña cambió fue el volumen — de unos pocos miles de cajones al año hacia 1800 a unos cuarenta mil en 1838.',
      whyItPersists: 'Hace un relato más limpio, con un solo villano, y la magnitud del aumento sí fue obra británica.',
      sourceIds: ['dikotter-2004', 'lovell-2011'],
    },
    {
      myth: 'Las guerras se libraron formalmente por el opio.',
      reality: 'Gran Bretaña defendió el caso como una cuestión de derechos comerciales, igualdad diplomática e indemnización por bienes incautados. El Tratado de Nankín no menciona el opio en absoluto — solo se legalizó tras la segunda guerra.',
      whyItPersists: 'El nombre «Guerra del Opio» se puso después, y describe mejor la causa que el casus belli declarado.',
      sourceIds: ['nanking-1842', 'hansard-1840'],
    },
    {
      myth: 'La reina Victoria leyó la carta de Lin Zexu y la ignoró.',
      reality: 'No hay pruebas de que la carta le llegara. Se publicó en Cantón y más tarde se imprimió en The Times, que es como casi todo el mundo la ha leído.',
      whyItPersists: 'La carta está tan bien argumentada que la imagen de recibirla y desdeñarla resulta irresistible.',
      sourceIds: ['lin-1839'],
    },
    {
      myth: 'China era un imperio cerrado y atrasado que se negaba a modernizarse.',
      reality: 'Los Qing dirigían un comercio regulado grande y sofisticado, y sí intentaron reformas. La distancia en 1839 era estrecha y concreta —buques de vapor y artillería industrial—, no general.',
      whyItPersists: 'Halaga a los vencedores, y fue el relato que se contó entonces para justificar la guerra.',
      sourceIds: ['platt-2018'],
    },
  ],

  disagreements: [
    {
      question: '¿Causaron de verdad las importaciones de opio la crisis de la plata en China?',
      positions: [
        { view: 'Sí — los pagos del opio invirtieron el flujo de plata y desestabilizaron la moneda.', heldBy: 'El relato tradicional, en manuales tanto chinos como occidentales', sourceId: 'lovell-2011' },
        { view: 'Solo en parte — la oferta mundial de plata se hundió en esas mismas décadas, cuando la independencia latinoamericana trastocó la minería, y China quedó atrapada en una escasez global.', heldBy: 'Lin Man-houng y los historiadores económicos posteriores', sourceId: 'linmh-2006' },
      ],
      atlasPosition: 'El atlas afirma que la plata salió de China y que el opio fue una razón importante. No afirma que el opio fuera la única razón, porque las pruebas no lo sostienen.',
    },
    {
      question: '¿Cuánto daño hizo realmente el opio a la sociedad china?',
      positions: [
        { view: 'Catastrófico — la adicción masiva vació comunidades y la capacidad del Estado para funcionar.', heldBy: 'Los funcionarios Qing de la época, y la mayor parte de la historiografía nacionalista posterior', sourceId: 'lovell-2011' },
        { view: 'Exagerado — la mayor parte del consumo era moderado, y la «plaga del opio» fue en parte un pánico moral amplificado por misioneros y después por reformistas.', heldBy: 'Frank Dikötter y sus coautores', sourceId: 'dikotter-2004' },
      ],
      atlasPosition: 'Esta está genuinamente abierta. El atlas informa de la escala del comercio, que está bien documentada, y marca el daño como discutido en lugar de elegir una cifra.',
    },
  ],

  didYouKnow: [
    'Lin Zexu escribió una disculpa formal a los dioses del mar antes de arrojar al océano mil toneladas de opio disuelto.',
    'El Tratado de Nankín se firmó en la cubierta de un buque de guerra británico, el HMS Cornwallis, fondeado en el Yangtsé.',
    'La respuesta británica a depender del té chino fue sacar la planta de contrabando y cultivarla en la India — por eso el té «English breakfast» es sobre todo indio.',
    'Hong Kong pareció un botín tan pobre en Londres que el ministro de Exteriores la llamó una isla yerma sin apenas una casa encima.',
    'A finales del siglo XIX, el mayor proveedor de opio de China ya no era la India. Era China.',
    'Gladstone, que en 1840 denunció la guerra como una deshonra permanente, llegó después a ser cuatro veces primer ministro del imperio que la libró.',
  ],

  lenses: [
    {
      id: 'one-minute',
      label: 'En un minuto',
      kind: 'length',
      paragraphs: [
        'A Gran Bretaña le encantaba el té. China lo vendía, pero no quería a cambio nada de lo que Gran Bretaña fabricaba — solo plata. Así que la plata se iba drenando año tras año.',
        'La Compañía de las Indias Orientales encontró un producto que China sí compraría: opio, cultivado en la India. Era ilegal en China, así que la Compañía lo subastaba a contrabandistas privados y mantenía limpias sus propias manos. En 1838 llegaban unos cuarenta mil cajones al año.',
        'En 1839 el funcionario Lin Zexu confiscó y destruyó más de mil toneladas. El superintendente británico de comercio había prometido a los mercaderes que Londres pagaría lo que entregasen — convirtiendo la pérdida de unos contrabandistas en deuda del gobierno. El Parlamento votó la guerra por nueve votos.',
        'Los cañoneros de vapor la ganaron deprisa. El Tratado de Nankín de 1842 abrió cinco puertos, impuso una indemnización enorme y entregó Hong Kong a Gran Bretaña. Una segunda guerra en 1856-60 legalizó el opio sin más. China llama al siglo siguiente el Siglo de la Humillación, y sigue enseñando que su historia moderna empieza aquí.',
      ],
    },
    {
      id: 'age-16',
      label: 'Explícamelo con 16 años',
      kind: 'age',
      paragraphs: [
        'El problema de fondo era una crisis de balanza de pagos dentro de una visión mercantilista. Gran Bretaña tenía un déficit estructural con China porque la demanda china de manufacturas británicas era casi nula mientras la demanda británica de té era inelástica y creciente — y el impuesto del té era una partida importante de ingresos del Estado.',
        'El opio resolvía la aritmética. Era la única mercancía con demanda china suficiente para invertir el flujo, y Gran Bretaña controlaba su oferta mediante el monopolio de Bengala. Y algo clave: la Compañía estructuró el comercio de modo que ella nunca hacía contrabando de nada; producía y subastaba, y unos «country traders» independientes cargaban con el riesgo.',
        'El detonante fue institucional más que moral. Cuando Charles Elliot indemnizó a los mercaderes por el opio que Lin Zexu exigía, convirtió contrabando en manos privadas en un pasivo del Estado británico — que es lo que hizo la guerra políticamente defendible en el Parlamento, donde la votación aun así salió por nueve.',
        'El resultado lo decidieron una asimetría tecnológica militar y una elección correcta de objetivo: en vez de asaltar la capital, las fuerzas británicas cortaron el Gran Canal y amenazaron el suministro de grano de Pekín. El sistema de tratados resultante —indemnizaciones, puertos abiertos, aranceles fijados, extraterritorialidad— se convirtió en el modelo de un siglo de concesiones extranjeras.',
      ],
    },
    {
      id: 'scholar',
      label: 'Nivel universitario',
      kind: 'age',
      paragraphs: [
        'La historiografía se ha alejado decididamente de un relato monocausal del opio. El trabajo de Lin Man-houng sobre la moneda sitúa la crisis de la plata de la era Daoguang dentro de una contracción global de metálico tras la disrupción de la minería hispanoamericana, lo que convierte la tesis del drenaje por opio en una explicación contribuyente antes que suficiente.',
        'Platt reencuadra las décadas previas a la guerra como un periodo de acomodación anglo-china sustancial, en el que el sistema de Cantón funcionaba de forma tolerable para ambas partes, y localiza la ruptura en la disolución del monopolio de la Compañía tras 1834 y la consiguiente entrada de comerciantes privados sin regular con acceso directo al Parlamento.',
        'La aportación central de Lovell es sobre la posteridad más que sobre el hecho: la «Guerra del Opio» como trauma nacional coherente es en buena medida una construcción del siglo XX, montada por la historiografía nacionalista y después comunista, que encontró en 1839-42 un punto de origen utilizable para un relato de victimización y recuperación.',
        'La posición revisionista de Dikötter sobre el consumo sigue siendo discutida y así se trata aquí: desestabiliza con utilidad las estadísticas de adicción de origen misionero sin desplazar la escala documentada de los volúmenes de importación.',
      ],
    },
    {
      id: 'follow-the-money',
      label: 'Sigue el dinero',
      kind: 'angle',
      paragraphs: [
        'Tres balances explican esta guerra mejor que cualquier batalla.',
        '**El Tesoro británico.** El impuesto del té era ingreso fiable. Un comercio que sacaba plata del país para generar ese ingreso se socavaba a sí mismo, y la teoría mercantilista hacía que la salida pareciera una herida nacional y no una preferencia.',
        '**El gobierno de la India.** El opio fue durante décadas una de las mayores fuentes individuales de ingresos de la India británica. En los años treinta ya no era un negocio secundario — una administración india estaba financiada en parte por el consumo chino, lo que significaba que acabar con él tenía un coste que en Calcuta se podía calcular con precisión.',
        '**Los libros de los mercaderes.** Casas como Jardine, Matheson & Co. llevaban la carga y el riesgo. Cuando Elliot garantizó sus pérdidas, se convirtieron en acreedores del Estado británico con un interés directo en una guerra que recuperase el dinero — y con la capacidad de presión para defenderla.',
      ],
    },
    {
      id: 'technology',
      label: 'El ángulo tecnológico',
      kind: 'angle',
      paragraphs: [
        'Esta guerra la decidió el calado — cuánto se hunde un barco en el agua.',
        'Las defensas chinas daban por hecho que los buques de vela de casco profundo podían detenerse en fuertes que vigilaban las bocas de los ríos, y que las vías interiores eran en la práctica inalcanzables. Contra la vela de madera eso era cierto.',
        'El *Nemesis* rompió el supuesto. Construido de hierro, movido por una máquina de vapor de ruedas y con un calado de metro y medio, podía remontar el río contra el viento y la corriente, mantenerse en bajíos donde los fuertes no lo alcanzaban y llevar cañones más pesados de lo que su tamaño sugería.',
        'La lección se generaliza. El efecto militar decisivo de la Revolución Industrial no fue mejores armas en un combate frontal — fue la capacidad de proyectar una fuerza pequeña hasta lugares que antes estaban a salvo por geografía.',
      ],
    },
    {
      id: 'from-china',
      label: 'Desde el lado chino',
      kind: 'contrast',
      paragraphs: [
        'Visto desde Pekín, esto no es una historia sobre política comercial. Es la historia de un sistema legal en funcionamiento al que le dicen que no se aplica a los extranjeros.',
        'Los Qing habían prohibido un narcótico, como hacen los Estados. Nombraron a un funcionario insobornable para hacer cumplir la prohibición, que es el aspecto que tiene una burocracia que funciona. La hizo cumplir contra traficantes, incautó contrabando y lo destruyó — y el gobierno de los traficantes mandó una flota.',
        'La humillación concreta de los tratados no era el dinero. Era la extraterritorialidad: el principio de que un extranjero que cometiera un delito en China respondería ante su propio cónsul. Un Estado que no puede aplicar su ley dentro de sus fronteras es un Estado solo a medias.',
        'Ese es el hilo que llega hasta hoy. Cuando la China actual insiste en la soberanía en términos que a los de fuera les parecen desproporcionados, la proporción se fijó aquí.',
      ],
    },
  ],

  beforeAfter: {
    label: 'Las condiciones comerciales de China, antes y después',
    before: {
      title: 'Antes de 1839',
      points: [
        'Un solo puerto abierto al comercio europeo, en Cantón',
        'Casas mercantiles chinas autorizadas por el Estado como intermediarias',
        'Aranceles fijados por China',
        'Los extranjeros, sujetos a la ley china',
        'Opio ilegal y formalmente perseguido',
      ],
    },
    after: {
      title: 'Después de 1860',
      points: [
        'Decenas de puertos abiertos por tratado, más legaciones extranjeras en Pekín',
        'Monopolio mercantil abolido; los extranjeros comercian directamente',
        'Aranceles fijados por tratado en tasas del gusto británico',
        'Los extranjeros responden ante sus cónsules, no ante tribunales chinos',
        'El opio, importación legal',
      ],
    },
  },

  whatIf: [
    {
      question: '¿Y si Charles Elliot no hubiera prometido nunca una indemnización?',
      reasoning: 'El opio confiscado habría seguido siendo una pérdida privada de unas pocas decenas de casas comerciales. Habrían presionado con fuerza, pero el Parlamento acababa de pasar tres días demostrando lo incómodo que le resultaba votar por proteger a contrabandistas — la moción de censura cayó por nueve votos con una deuda de la Corona sobre la mesa.',
      constraint: 'Las presiones de fondo no desaparecen. El déficit comercial, el fin del monopolio de la Compañía y un cuerpo creciente de mercaderes con acceso parlamentario directo apuntan todos a un choque. Elliot cambió el momento y el pretexto; probablemente no creó la colisión.',
    },
    {
      question: '¿Y si China hubiera ganado la primera guerra?',
      reasoning: 'Una victoria Qing en 1842 habría preservado con toda probabilidad el sistema de Cantón otra generación y retrasado la plantilla de puertos abiertos que después copiaron Francia, Estados Unidos y Rusia.',
      constraint: 'Cuesta ver cómo podría haberse ganado en el mar en 1842, y la brecha industrial se ensanchaba en vez de cerrarse. Es más fácil imaginar un retraso que una inversión.',
    },
  ],

  quiz: [
    {
      question: '¿Por qué salía plata de Gran Bretaña hacia China, para empezar?',
      options: [
        'China exigía tributo a los comerciantes europeos',
        'Gran Bretaña quería té, y China casi no quería nada de lo que Gran Bretaña fabricaba',
        'Gran Bretaña devolvía un préstamo al gobierno Qing',
        'La plata valía más en China que en Europa',
      ],
      answerIndex: 1,
      explains: 'El comercio solo iba en una dirección. Los barcos británicos llegaban con mercancías que China declinaba y salían con té, así que el saldo se pagaba en plata, año tras año.',
    },
    {
      question: '¿Cómo evitaba la Compañía de las Indias Orientales el delito de introducir opio de contrabando en China?',
      options: [
        'Consiguió una licencia Qing para opio medicinal',
        'Solo enviaba a Hong Kong, que era británica',
        'Cultivaba y subastaba el opio en la India y dejaba que lo llevaran comerciantes privados',
        'Sobornaba a los mercaderes del Cohong para registrar la carga como té',
      ],
      answerIndex: 2,
      explains: 'La Compañía producía el opio y lo vendía en subasta en Calcuta. Los «country traders» independientes se lo llevaban desde ahí — lo que dejaba intacto el comercio legal de la Compañía en Cantón.',
    },
    {
      question: '¿Qué obligó finalmente a los Qing a aceptar condiciones de paz en 1842?',
      options: [
        'La toma de Pekín',
        'La destrucción del ejército chino en una sola batalla',
        'Una epidemia de cólera en las provincias del sur',
        'Que las fuerzas británicas cortaran el Gran Canal, que abastecía de grano a Pekín',
      ],
      answerIndex: 3,
      explains: 'La capital nunca fue asaltada. Seccionar la ruta del grano hizo creíble la amenaza de matar de hambre a Pekín, y la corte negoció en cuestión de semanas.',
    },
    {
      question: '¿Qué dice el Tratado de Nankín sobre el opio?',
      options: [
        'Legaliza el comercio',
        'Prohíbe el comercio para siempre',
        'Nada en absoluto',
        'Fija un arancel sobre las importaciones de opio',
      ],
      answerIndex: 2,
      explains: 'El opio está ausente del tratado. Gran Bretaña defendió la guerra por derechos comerciales e indemnización; la droga solo se legalizó tras la segunda guerra, en 1860.',
    },
  ],

  sources: [
    {
      id: 'lovell-2011',
      kind: 'book',
      author: 'Julia Lovell',
      title: 'The Opium War: Drugs, Dreams and the Making of China',
      year: 2011,
      detail: 'Picador. ISBN 978-0-330-45747-7',
      note: 'El relato moderno de referencia, y el mejor tratamiento de cómo la guerra se convirtió después en relato nacional de origen.',
    },
    {
      id: 'platt-2018',
      kind: 'book',
      author: 'Stephen R. Platt',
      title: 'Imperial Twilight: The Opium War and the End of China’s Last Golden Age',
      year: 2018,
      detail: 'Alfred A. Knopf. ISBN 978-0-307-96173-0',
      note: 'Lo más sólido sobre las décadas anteriores a 1839 y sobre lo bien que funcionaba en realidad el sistema de Cantón.',
    },
    {
      id: 'linmh-2006',
      kind: 'book',
      author: 'Lin Man-houng',
      title: 'China Upside Down: Currency, Society, and Ideologies, 1808–1856',
      year: 2006,
      detail: 'Harvard University Asia Center. ISBN 978-0-674-02268-2',
      note: 'El argumento de historia económica de que la crisis de la plata fue en parte un fenómeno monetario global y no puramente del opio.',
    },
    {
      id: 'dikotter-2004',
      kind: 'book',
      author: 'Frank Dikötter, Lars Laamann and Zhou Xun',
      title: 'Narcotic Culture: A History of Drugs in China',
      year: 2004,
      detail: 'Hurst / University of Chicago Press. ISBN 978-1-85065-725-3',
      note: 'El argumento revisionista sobre consumo y daño. Se cita aquí como posición discutida, no como zanjada.',
    },
    {
      id: 'lin-1839',
      kind: 'primary',
      author: 'Lin Zexu',
      title: 'Letter to Queen Victoria',
      year: 1839,
      note: 'Escrita en Cantón y publicada allí; después impresa en The Times. No hay pruebas de que llegara a la reina.',
    },
    {
      id: 'nanking-1842',
      kind: 'primary',
      author: 'Great Britain and the Qing Empire',
      title: 'Treaty of Nanking',
      year: 1842,
      detail: 'Firmado el 29 de agosto de 1842 a bordo del HMS Cornwallis',
      note: 'El texto operativo: cinco puertos, veintiún millones de dólares de plata, cesión de la isla de Hong Kong. Ni una mención del opio.',
    },
    {
      id: 'hansard-1840',
      kind: 'primary',
      author: 'UK Parliament',
      title: 'House of Commons debate on the China trade, 7–9 April 1840',
      year: 1840,
      detail: 'Hansard, 3.ª serie, vol. 53',
      note: 'Contiene el discurso de Gladstone contra la guerra y la votación que tumbó la moción de censura, 271 a 262.',
    },
  ],
}
