import type { Story } from '../../types'

export const unitedFruitEs: Story = {
  slug: 'united-fruit',
  title: 'La empresa que era dueña de un país',
  subtitle: 'El Pulpo — cómo una frutera, un publicista y la CIA acabaron con diez años de democracia.',
  hook: 'Guatemala se ofreció a comprar unas tierras al precio que su dueño había jurado que valían, y ese fue el crimen que le costó la democracia.',
  era: 'contemporary',
  category: 'milestones',
  years: [1899, 1996],
  regions: ['Guatemala', 'Estados Unidos', 'Centroamérica'],
  nodes: ['guatemala-coup', 'united-fruit', 'guatemala', 'decree-900', 'public-relations'],
  tags: ['empire', 'propaganda', 'cold-war', 'economics', 'latin-america', 'legend'],
  readingMinutes: 11,
  reviewed: '2026-08-03',
  mood: 'jungle',

  reel: [
    { beat: 'hook', punch: true, text: 'Un país se ofreció a comprar unas tierras al precio que su dueño había jurado que valían,' },
    { beat: 'hook', text: 'y ese fue el crimen.' },
    { beat: 'worldBefore', kicker: '1899', text: 'Una empresa estadounidense empieza a plantar bananos en Centroamérica,' },
    { beat: 'worldBefore', text: 'y como los bananos se pudren tiende los ferrocarriles para moverlos,' },
    { beat: 'worldBefore', text: 'luego compra los puertos a los que llegan los trenes, luego los cables del telégrafo,' },
    { beat: 'worldBefore', mark: 'web', text: 'hasta que toda cosecha del país se mueve en sus vías, a su precio.' },
    { beat: 'worldBefore', punch: true, text: 'Los guatemaltecos tienen un nombre para eso. El Pulpo.' },
    { beat: 'problem', mark: 'imbalance', text: 'Se vuelve el mayor terrateniente del país y casi no planta nada,' },
    { beat: 'problem', text: 'y mantiene el resto vacío para que tampoco pueda cultivarlo nadie más,' },
    { beat: 'problem', punch: true, text: 'en un país donde casi nadie tiene tierra.' },
    { beat: 'problem', kicker: '1944', text: 'Entonces Guatemala echa a su dictador y empieza a votar,' },
    { beat: 'problem', text: 'y a los diez años que siguen todavía los llaman la Primavera.' },
    { beat: 'story', kicker: '1951', text: 'Sale elegido Árbenz, y no es ningún revolucionario —' },
    { beat: 'story', text: 'quiere un país moderno, y un país moderno no puede vivir de tierra ociosa.' },
    { beat: 'story', kicker: '1952', text: 'Así que el Estado compra los campos sin cultivar y se los entrega a campesinos,' },
    { beat: 'story', text: 'no incautados sino pagados, en bonos del gobierno,' },
    { beat: 'story', punch: true, mark: 'reversal', text: 'justo al valor que la empresa llevaba años declarándole a Hacienda.' },
    { beat: 'story', punch: true, text: '600.000 dólares, dijo Guatemala. 16 millones, dijo la empresa.' },
    { beat: 'story', text: 'Probablemente tenía razón. Solo que no podía explicar por qué.' },
    { beat: 'whyItHappened', text: 'Así que deja de discutir sobre tierras' },
    { beat: 'whyItHappened', text: 'y contrata a Edward Bernays, el hombre que inventó las relaciones públicas,' },
    { beat: 'whyItHappened', mark: 'echo', text: 'que convierte un pleito fiscal en una cabeza de puente soviética a un paso del canal,' },
    { beat: 'whyItHappened', text: 'en un Washington donde el secretario de Estado y el jefe de la CIA' },
    { beat: 'whyItHappened', punch: true, text: 'habían trabajado los dos para el bufete de la empresa.' },
    { beat: 'consequences', kicker: '1954', text: 'Unos cuatrocientos ochenta hombres cruzan la frontera y apenas avanzan,' },
    { beat: 'consequences', text: 'aviones sin distintivo bombardean la capital,' },
    { beat: 'consequences', mark: 'collapse', text: 'y una emisora hace el papel de un ejército que no existe.' },
    { beat: 'consequences', punch: true, text: 'Guatemala tenía un ejército de verdad. Creyó a la radio.' },
    { beat: 'consequences', text: 'Árbenz dimite invicto, la tierra vuelve atrás, y empieza una guerra de treinta y seis años' },
    { beat: 'whyItMatters', punch: true, text: 'que mata a doscientas mil personas — y la empresa hoy se llama Chiquita.' },
  ],

  beats: {
    worldBefore: {
      heading: 'El mundo de antes',
      paragraphs: [
        'La United Fruit Company se montó en 1899 a partir de dos cosas: un importador de fruta de Boston y un hombre del ferrocarril.',
        'Esa combinación es la historia entera. Minor Keith llevaba años construyendo ferrocarriles en Costa Rica y había descubierto que un ferrocarril por terreno vacío pierde dinero — a menos que plantes a su lado algo que haya que transportar. Plantó bananos.',
        'La empresa que salió de ahí no se veía a sí misma como una finca. Se veía como un negocio logístico que además cultivaba fruta, y compró lo que la logística necesita: tierra, vías, barcos, muelles y las líneas de telégrafo que te decían dónde estaba todo.',
        'En Guatemala fue donde más lejos llegó. Hacia los años cuarenta la United Fruit era el mayor terrateniente y el mayor empleador del país. Controlaba los Ferrocarriles Internacionales de Centroamérica y, por tanto, Puerto Barrios, el único puerto caribeño relevante del país. El café de cualquier otro llegaba al mercado por sus vías, por su muelle, a sus tarifas.',
        'Los guatemaltecos la llamaban *El Pulpo*.',
      ],
      aside: {
        kind: 'number',
        label: 'Qué significaba «terrateniente»',
        body: 'Casi todo lo que la empresa tenía no estaba plantado. El cultivo del banano agota e infecta el suelo, así que guardaba grandes reservas contra futuras enfermedades. En un país donde alrededor del 2 % de los propietarios tenía cerca del 70 % de la tierra cultivable, una finca enorme y ociosa no era un dato neutro.',
      },
      sourceIds: ['gleijeses-1991', 'schlesinger-kinzer-1982'],
    },

    problem: {
      heading: 'El problema',
      paragraphs: [
        'En octubre de 1944 una coalición de estudiantes, maestros y oficiales jóvenes derrocó al sucesor del dictador Jorge Ubico, y Guatemala empezó a celebrar elecciones de verdad.',
        'Lo que siguió se recuerda allí como los Diez Años de Primavera. Salario mínimo. Seguridad social. Sindicatos legalizados. Campañas de alfabetización. Juan José Arévalo gobernó seis años y entregó el poder a un sucesor elegido, algo que no había ocurrido antes.',
        'Ese sucesor, elegido en 1951 con unas dos terceras partes de los votos, fue Jacobo Árbenz — militar, hijo de un farmacéutico suizo, y un hombre cuya ambición declarada era casi agresivamente poco revolucionaria. Dijo que quería convertir Guatemala de país atrasado con economía semifeudal en un Estado capitalista moderno.',
        'Eso no se hace con tierra ociosa. Cerca de tres cuartas partes de la tierra cultivable estaba en manos de un número minúsculo de propietarios, y la mayor parte no se cultivaba. El país importaba comida que tenía suelo de sobra para producir.',
        'Así que el problema que Árbenz se propuso resolver era, en apariencia, un problema de eficiencia capitalista. Lo que lo volvió imperdonable fue la solución que eligió.',
      ],
      sourceIds: ['gleijeses-1991'],
    },

    story: {
      heading: 'La historia',
      paragraphs: [
        'El Decreto 900 se convirtió en ley en junio de 1952. Conviene ser preciso con él, porque casi todo lo que se dijo entonces no lo era.',
        'Se aplicaba solo a la tierra **sin cultivar**, y solo en fincas por encima de cierto umbral de tamaño. Las explotaciones en producción quedaban intactas, del tamaño que fueran. La tierra no se confiscaba: el Estado la compraba, pagando en bonos públicos a veinticinco años al 3 %.',
        'Y el precio se fijaba en el valor que el propietario había declarado a efectos fiscales.',
        'Esa última cláusula es el choque entero. La United Fruit llevaba décadas declarando sus propiedades guatemaltecas por una pequeña fracción de su valor de mercado, porque sobre eso se calculaba su factura fiscal. Cuando el gobierno se ofreció a comprar 234.000 acres sin cultivar, ofreció algo más de 600.000 dólares — la cifra de la propia empresa.',
        'La United Fruit contestó que la tierra valía casi 16 millones, y el Departamento de Estado estadounidense respaldó formalmente esa cifra.',
        'Probablemente la empresa tenía razón sobre el valor de mercado. Solo que no podía decirlo sin explicar para qué había servido la otra cifra.',
        '**Entonces la discusión cambió de tema.** Ni tierra, ni indemnización: comunismo.',
        'La United Fruit había contratado a Edward Bernays — sobrino de Sigmund Freud, el hombre que acuñó «relaciones públicas» precisamente porque «propaganda» se había vuelto inservible tras la Primera Guerra Mundial. Bernays hizo lo que después contó él mismo con toda franqueza. Organizó viajes a Guatemala para periodistas estadounidenses, les preparó los itinerarios y las entrevistas, y suministró la interpretación. Sembró material a través de un servicio de noticias falsamente neutral. Trabajó el relato durante años antes de que hiciera falta.',
        'Cuajó. The New York Times, Time, Newsweek y el Herald Tribune reprodujeron el encuadre: una cabeza de puente soviética en Centroamérica, a ciento cincuenta kilómetros del canal de Panamá.',
        'El encuadre encontró un Washington inusualmente dispuesto a aceptarlo. El secretario de Estado John Foster Dulles había sido socio principal en Sullivan & Cromwell, el bufete que representaba a la United Fruit. Su hermano Allen Dulles, director de la CIA, había trabajado en el mismo bufete. El subsecretario de Estado para Asuntos Interamericanos, John Moors Cabot, venía de una familia con acciones de la empresa. La secretaria personal de Eisenhower, Ann Whitman, estaba casada con el jefe de relaciones públicas de la United Fruit.',
        'Nada de eso es una teoría de la conspiración; es una lista de historiales laborales. Lo que producía era una sala en la que nadie se sentía inclinado a preguntar si una discusión sobre valoración de tierras era de verdad una operación soviética.',
        '**La operación PBSUCCESS se aprobó en 1953.**',
        'No fue una invasión. Carlos Castillo Armas cruzó desde Honduras con unos 480 hombres y apenas avanzó. Aviones sin distintivo pilotados por estadounidenses bombardearon la capital. Y una emisora de la CIA, La Voz de la Liberación, emitía como si fuera un gran ejército rebelde sobre el terreno — anunciando victorias que no habían ocurrido, describiendo columnas que no existían y nombrando unidades que nunca se habían formado.',
        'El ejército guatemalteco creyó a la radio. Árbenz, incapaz de fiarse de sus propios oficiales y negándose a armar milicias civiles, dimitió el 27 de junio de 1954.',
        'No lo habían derrotado. Lo habían convencido.',
      ],
      aside: {
        kind: 'voice',
        label: 'Árbenz, discurso de toma de posesión, 1951',
        body: 'Describió su objetivo como convertir Guatemala de país atrasado con economía predominantemente feudal en un Estado capitalista moderno — una frase citada muchas veces desde entonces, porque cuesta reconciliarla con aquello de lo que se le acusó.',
        sourceId: 'arbenz-1951',
      },
      sourceIds: ['gleijeses-1991', 'schlesinger-kinzer-1982', 'cullather-1999', 'decree-900'],
    },

    whyItHappened: {
      heading: 'Por qué pasó',
      paragraphs: [
        'Tenían que darse tres cosas a la vez, y conviene separarlas, porque la versión popular las aplasta en «la CIA lo hizo por los bananos».',
        '**La empresa tenía un agravio real, y letal.** Su tierra sí valía más que la indemnización ofrecida. Pero la cifra que le ofrecían era la suya, y corregirla en público significaba confesar años de declaraciones a la baja. No podía ganar la discusión que de verdad tenía, así que necesitaba otra.',
        '**Las relaciones públicas se habían vuelto una profesión, y este fue su banco de pruebas.** Bernays no estaba maquillando un ciclo informativo; dirigió una campaña de varios años para que una interpretación concreta se sintiera como conocimiento de fondo antes de que nadie tuviera que actuar sobre ella. En 1954 a la prensa estadounidense no había que convencerla de que Guatemala era comunista. Ya lo daba por hecho.',
        '**Y la Guerra Fría hacía traducible cualquier disputa local.** Una reforma agraria en un país pequeño es una cuestión de política interior. Replanteada como pregunta sobre de qué lado estaba Guatemala, se convirtió en un asunto de seguridad estadounidense — y, una vez que lo fue, los detalles de hectáreas y valoraciones dejaron de ser relevantes para la decisión.',
        'Las conexiones personales concretas entre la United Fruit y la administración Eisenhower son reales y están documentadas. Lo que mejor explican no es que el golpe ocurriera, sino que nadie con peso se opusiera.',
        'También conviene decir lo que el atlas no afirma. El Partido Guatemalteco del Trabajo sí tenía influencia sobre Árbenz, y él sí aceptó un envío de armas checoslovacas en mayo de 1954 — después de que Estados Unidos le impusiera un embargo. Los historiadores discrepan sobre cuánto importó eso. En lo que no discrepan es en que la Unión Soviética casi no tenía presencia en Guatemala, y en que el país no se dirigía desde Moscú.',
      ],
      sourceIds: ['cullather-1999', 'gleijeses-1991', 'schlesinger-kinzer-1982'],
    },

    consequences: {
      heading: 'Qué cambió',
      paragraphs: [
        'La operación se juzgó un triunfo, y ese juicio hizo más daño que la operación.',
      ],
      shortTerm: [
        'Castillo Armas revirtió el Decreto 900 en menos de un año. La tierra expropiada volvió a sus antiguos dueños, la United Fruit incluida.',
        'Se prohibieron los partidos políticos, se suspendió la constitución de 1945 y se retiró el voto a los ciudadanos analfabetos — la mayoría.',
        'Miles fueron detenidos; los sindicatos, desarticulados. Al propio Castillo Armas lo asesinaron en 1957.',
        'Árbenz entró en un exilio que duró el resto de su vida, moviéndose entre media docena de países. Murió en México en 1971.',
      ],
      longTerm: [
        'La guerra civil guatemalteca empezó en 1960 y duró hasta 1996 — treinta y seis años, unos 200.000 muertos o desaparecidos.',
        'La comisión de la verdad respaldada por la ONU atribuyó el 93 % de las violaciones documentadas a fuerzas del Estado y concluyó que se habían cometido actos de genocidio contra comunidades mayas.',
        'PBSUCCESS se convirtió en plantilla. Los mismos planificadores, envalentonados por Guatemala, pasaron a bahía de Cochinos en 1961, donde los supuestos fallaron frente a un adversario que había estudiado 1954 con cuidado.',
        'La United Fruit no sacó provecho mucho tiempo. La acción antimonopolio la obligó a desprenderse de activos, y tras una fusión en 1970 y un escándalo de sobornos en 1975 el negocio superviviente pasó a llamarse Chiquita.',
      ],
      unexpected: [
        'Un joven médico argentino llamado Ernesto Guevara estaba en Ciudad de Guatemala en 1954 y lo vio pasar. Sacó la conclusión de que una revolución que deja intacto el ejército acaba derribada, y se la llevó a Cuba.',
        'La CIA escribió su propia historia clasificada de la operación, y es inusualmente crítica. Desclasificada en los años noventa, hoy es una de las mejores fuentes sobre cuánto del «ejército rebelde» era un programa de radio.',
        'La expresión «república bananera» no tiene nada que ver con 1954. La acuñó O. Henry en 1904, escribiendo en Honduras mientras huía de una acusación de desfalco en Texas.',
        'Los restos de Árbenz volvieron a Guatemala en 1995, y en 2011 el gobierno guatemalteco pidió perdón formalmente a su familia.',
      ],
      sourceIds: ['ceh-1999', 'cullather-1999', 'schlesinger-kinzer-1982'],
    },

    whyItMatters: {
      heading: 'Por qué sigue importando',
      paragraphs: [
        'Lo útil aquí no es «las empresas estadounidenses son malas». Es el mecanismo, que es portátil y sigue en uso.',
        'Alguien con un interés comercial no podía ganar la discusión que de verdad tenía — un pleito de valoración que habría perdido con sus propias cifras. Así que cambió el tema a otro en el que la otra parte no podía responder: la lealtad. No «páguennos más» sino «están en el otro bando».',
        'Esa sustitución funcionó porque un profesional se había pasado años haciendo que el tema de reemplazo pareciera saber común, y porque la época suministraba un binario que se tragaba el detalle local. A quienes decidían no los sobornaron. Simplemente operaban dentro de un relato que ya les habían contado.',
        'Guatemala lo pagó con treinta y seis años de guerra y doscientas mil personas.',
        'Y el detalle más afilado es el más pequeño. La tierra iba a comprarse al precio que su dueño había jurado que valía. La catástrofe entera empieza con una empresa a la que tomaron la palabra.',
      ],
      sourceIds: ['gleijeses-1991', 'ceh-1999'],
    },
  },

  timeline: [
    { year: 1899, title: 'Se funda la United Fruit', detail: 'Un importador de fruta de Boston se fusiona con los intereses ferroviarios centroamericanos de Minor Keith. Vías y fruta en una sola empresa desde el principio.', pivotal: true },
    { year: 1904, title: 'Se acuña la expresión', detail: 'O. Henry, escribiendo en Honduras como fugitivo, inventa «república bananera» en Cabbages and Kings — cincuenta años antes del golpe con el que hoy se asocia.' },
    { year: 1928, title: 'La masacre de las bananeras', detail: 'Tropas colombianas disparan contra trabajadores en huelga de la United Fruit en Ciénaga. La cifra de muertos se discute hasta hoy.', confidence: 'contested' },
    { year: 1944, date: '1944-10', title: 'La Revolución de Octubre', detail: 'Estudiantes, maestros y oficiales jóvenes derrocan la dictadura. Guatemala empieza a celebrar elecciones de verdad.', pivotal: true },
    { year: 1951, title: 'Árbenz es elegido', detail: 'Unas dos terceras partes de los votos, con un programa de modernizar una economía semifeudal.', pivotal: true },
    { year: 1952, date: '1952-06', title: 'El Decreto 900', detail: 'La tierra sin cultivar de las grandes fincas la compra el Estado en bonos, al valor que el dueño declaró a Hacienda.', pivotal: true },
    { year: 1953, title: 'La pelea por la valoración', detail: 'Guatemala ofrece unos 600.000 dólares por 234.000 acres sin cultivar. La empresa y el Departamento de Estado exigen casi 16 millones.', pivotal: true },
    { year: 1953, title: 'Se aprueba PBSUCCESS', detail: 'Eisenhower autoriza una operación encubierta para derribar a Árbenz. Presupuesto de millones; fuerza, deliberadamente, mínima.' },
    { year: 1954, date: '1954-05', title: 'El envío de armas checas', detail: 'Árbenz compra armas a Checoslovaquia tras un embargo estadounidense. Se usa como confirmación de todo lo ya denunciado.', confidence: 'contested' },
    { year: 1954, date: '1954-06-18', title: 'La invasión que casi no se mueve', detail: 'Castillo Armas cruza desde Honduras con unos 480 hombres. La Voz de la Liberación emite una guerra mucho mayor.', pivotal: true },
    { year: 1954, date: '1954-06-27', title: 'Árbenz dimite', detail: 'Invicto en el campo, incapaz de fiarse de sus oficiales y sin querer armar a civiles. Se marcha al exilio.', pivotal: true },
    { year: 1955, title: 'La tierra vuelve atrás', detail: 'Se revierte el Decreto 900, se prohíben los partidos y los ciudadanos analfabetos pierden el voto.' },
    { year: 1960, title: 'Empieza la guerra civil', detail: 'Dura hasta 1996. Unas 200.000 personas mueren o desaparecen.', pivotal: true },
    { year: 1961, title: 'Bahía de Cochinos', detail: 'Los mismos planificadores aplican el mismo manual contra Cuba, donde la lección de 1954 se había estudiado con cuidado.' },
    { year: 1970, title: 'La United Fruit pasa a ser United Brands', detail: 'La acción antimonopolio y la enfermedad ya habían roto la vieja estructura. Tras un escándalo de sobornos en 1975 pasa a llamarse Chiquita.' },
    { year: 1999, title: 'Informa la comisión de la verdad', detail: 'La CEH, respaldada por la ONU, atribuye el 93 % de las violaciones documentadas a fuerzas del Estado y concluye que hubo actos de genocidio contra comunidades mayas.', pivotal: true },
    { year: 2011, title: 'Guatemala pide perdón', detail: 'El gobierno pide perdón formalmente a la familia de Árbenz, cincuenta y siete años después del golpe.' },
  ],

  causeEffect: [
    { cause: 'Un ferrocarril por terreno vacío pierde dinero', effect: 'La empresa ferroviaria planta bananos junto a la vía', because: 'Una línea solo sale rentable si hay carga, así que había que crear la carga.' },
    { cause: 'La empresa compra el puerto, las vías y el telégrafo', effect: 'Las exportaciones de todos los demás se mueven a su precio', because: 'Tener la única ruta al mercado es más duradero que tener la cosecha.' },
    { cause: 'La empresa infravalora su tierra ante Hacienda', effect: 'La indemnización del Decreto 900 se calcula sobre esa cifra', because: 'La ley usaba a propósito el valor declarado por el dueño, lo que hizo que mentir saliera caro exactamente una vez.' },
    { cause: 'La empresa no puede ganar una discusión sobre valoración', effect: 'Cambia el tema al comunismo', because: 'Corregir la cifra en público significaba admitir para qué había servido la cifra.' },
    { cause: 'Bernays dirige una campaña de prensa de varios años', effect: 'Los estadounidenses ya creen que Guatemala es una cabeza de puente soviética', because: 'Un marco instalado años antes no se vive como persuasión; se vive como conocimiento de fondo.' },
    { cause: 'La Guerra Fría suministra un binario', effect: 'Una reforma agraria se vuelve cuestión de seguridad', because: 'En cuanto una disputa va sobre de qué lado estás, los detalles de la disputa dejan de importar para decidir.' },
    { cause: 'Una emisora informa de una guerra que no está ocurriendo', effect: 'El ejército guatemalteco deja de combatir', because: 'Un ejército que se cree ya rodeado se comporta como si lo estuviera.' },
    { cause: 'El golpe sale barato', effect: 'El método se reutiliza en bahía de Cochinos', because: 'Un éxito que nadie examina se convierte en plantilla, y los supuestos viajan con él sin examinar.' },
  ],

  myths: [
    {
      myth: 'Árbenz cayó porque Guatemala no tenía ejército con el que resistir la invasión.',
      reality: 'Guatemala tenía un ejército permanente bastante mayor que los cerca de 480 hombres que cruzaron desde Honduras, y esa fuerza apenas avanzó. Lo que la derrotó fue la información: ataques aéreos sin distintivo y una emisora de la CIA emitiendo como gran ejército rebelde, informando de victorias y nombrando unidades que no existían. La oficialidad se lo creyó, y Árbenz no podía apoyarse en oficiales que se creían ya derrotados.',
      whyItPersists: 'Un golpe da a entender una batalla, así que la historia se recuenta como tal. La verdad —que un ejército se retiró por un programa de radio— es más extraña y mucho más difícil de imaginar.',
      sourceIds: ['cullather-1999', 'gleijeses-1991'],
    },
    {
      myth: '«República bananera» se acuñó para Guatemala en 1954.',
      reality: 'O. Henry inventó la expresión en Cabbages and Kings en 1904, a partir del año que pasó en Honduras evitando una acusación de desfalco en Texas. Es medio siglo anterior al golpe.',
      whyItPersists: 'La expresión encaja tan exactamente con 1954 que parece que tuvo que hacerse para eso.',
      sourceIds: ['ohenry-1904'],
    },
    {
      myth: 'Árbenz era comunista, y el golpe frenó una toma del poder soviética.',
      reality: 'Árbenz no era militante y describía su objetivo como construir un Estado capitalista moderno. Los comunistas tenían influencia en su coalición y sí compró armas checas tras un embargo estadounidense, pero la Unión Soviética casi no tenía presencia en Guatemala. La propia historia desclasificada de la CIA se muestra notablemente poco convencida de la amenaza sobre la que actuó.',
      whyItPersists: 'Fue la justificación oficial, repetida durante décadas, y la fabricaron profesionales años antes de que hiciera falta.',
      sourceIds: ['cullather-1999', 'gleijeses-1991', 'arbenz-1951'],
    },
    {
      myth: 'El Decreto 900 se incautó de la tierra sin pagar nada.',
      reality: 'Se aplicaba solo a tierra sin cultivar por encima de un umbral de tamaño, y el Estado pagaba en bonos a veinticinco años. La disputa nunca fue sobre si pagar — fue sobre el precio, que la ley fijaba en el valor fiscal declarado por el propio dueño.',
      whyItPersists: '«Expropiación» fue la palabra que se usó entonces, y arrastra una connotación de confiscación que el decreto no sostiene.',
      sourceIds: ['decree-900', 'gleijeses-1991'],
    },
    {
      myth: 'La CIA derribó a Árbenz con un ejército invasor.',
      reality: 'La fuerza terrestre eran unos 480 hombres y apenas avanzó. Las armas decisivas fueron aviones sin distintivo y una emisora que se hacía pasar por un gran ejército rebelde — informando de victorias, columnas y unidades que no existían.',
      whyItPersists: 'Un golpe da a entender una batalla. Este fue sobre todo una emisión, que es más difícil de imaginar y mucho más raro.',
      sourceIds: ['cullather-1999', 'schlesinger-kinzer-1982'],
    },
  ],

  disagreements: [
    {
      question: '¿Se hizo esto por la United Fruit o por la Guerra Fría?',
      positions: [
        { view: 'Lo impulsó la empresa. Sus presiones, sus abogados en el gabinete y su campaña de relaciones públicas crearon tanto la presión como la justificación.', heldBy: 'Schlesinger y Kinzer, y la mayoría de los relatos populares desde entonces', sourceId: 'schlesinger-kinzer-1982' },
        { view: 'Washington habría actuado igual. La administración creía de verdad que el hemisferio estaba en disputa, y la empresa aportó un caso conveniente más que el motivo.', heldBy: 'Gleijeses, y la propia historia interna de la CIA', sourceId: 'gleijeses-1991' },
      ],
      atlasPosition: 'El atlas informa de las conexiones documentadas —el bufete de los hermanos Dulles, el matrimonio Whitman, la campaña de Bernays— y no afirma que el golpe no habría ocurrido sin ellas. Las dos lecturas coinciden en que la amenaza se exageró; discrepan sobre a quién le hacía más falta exagerarla.',
    },
    {
      question: '¿Cuánta influencia comunista había realmente?',
      positions: [
        { view: 'Considerable. El PGT tenía influencia real sobre la política agraria y acceso a Árbenz, y la compra de armas checas era un alineamiento genuino.', heldBy: 'Las evaluaciones estadounidenses de la época, y parte de la investigación posterior' },
        { view: 'Marginal para el resultado. La implicación soviética fue insignificante, y el programa de reforma era reconociblemente capitalista y constitucional.', heldBy: 'Gleijeses y el peso del trabajo de archivo posterior', sourceId: 'gleijeses-1991' },
      ],
      atlasPosition: 'El atlas afirma que los comunistas tenían influencia y que la Unión Soviética no. Trata «Guatemala se estaba convirtiendo en satélite soviético» como no sostenido, que es también como lo lee la propia historia desclasificada de la CIA.',
    },
  ],

  didYouKnow: [
    'La fórmula de indemnización usaba el valor que cada dueño había declarado a Hacienda. La United Fruit llevaba años declarando su tierra casi sin valor.',
    'Edward Bernays, que dirigió la campaña de prensa, era sobrino de Sigmund Freud y acuñó «relaciones públicas» porque «propaganda» se había vuelto inservible después de 1918.',
    'El secretario de Estado y el director de la CIA habían trabajado los dos en el bufete que representaba a la United Fruit.',
    'El arma decisiva fue una emisora de radio. Describía un ejército rebelde que no existía, y el ejército guatemalteco la creyó.',
    'El Che Guevara estaba en Ciudad de Guatemala en 1954 y se llevó una sola lección: una revolución que deja intacto el viejo ejército no sobrevive.',
    'La propia historia clasificada de la CIA sobre la operación, desclasificada en los noventa, es uno de los relatos más escépticos que existen sobre ella.',
    '«República bananera» la acuñó en 1904 O. Henry, que estaba en Honduras escondiéndose de una acusación de fraude.',
  ],

  lenses: [
    {
      id: 'one-minute',
      label: 'En un minuto',
      kind: 'length',
      paragraphs: [
        'La United Fruit se fundó en 1899 fusionando un importador de fruta con un constructor de ferrocarriles, y en Guatemala acabó siendo dueña de las mayores fincas, del ferrocarril, del único puerto caribeño y del telégrafo. Los guatemaltecos la llamaban El Pulpo.',
        'Después de 1944 Guatemala se hizo democracia. En 1952 el presidente Árbenz sacó el Decreto 900: el Estado compraría tierra sin cultivar de las grandes fincas, pagando en bonos, al valor que el dueño había declarado a Hacienda. La United Fruit llevaba años infravalorando ese dato, así que la oferta salió por unos 600.000 dólares por una tierra que ahora decía que valía 16 millones.',
        'Incapaz de ganar esa discusión sin admitir su posición fiscal, la empresa cambió de tema. Edward Bernays dirigió una campaña de años presentando Guatemala como cabeza de puente soviética, en un Washington donde el secretario de Estado y el director de la CIA habían trabajado los dos en el bufete de la empresa.',
        'En 1954 la CIA ejecutó PBSUCCESS: unos 480 hombres que apenas avanzaron, bombarderos sin distintivo y una emisora que se hacía pasar por un gran ejército rebelde. Árbenz dimitió invicto. La reforma se revirtió, y la guerra civil que siguió duró treinta y seis años y mató a unas 200.000 personas.',
      ],
    },
    {
      id: 'age-16',
      label: 'Explícamelo con 16 años',
      kind: 'age',
      paragraphs: [
        'Empieza por la estructura. La United Fruit no era ante todo un negocio de plantaciones; era infraestructura integrada verticalmente. Tener las vías y el único puerto caribeño de aguas profundas significaba fijar el precio efectivo de exportación para todo el país, que es una posición mucho más duradera que tener la cosecha.',
        'El Decreto 900 era una reforma de eficiencia dirigida, no una colectivización: solo tierra sin cultivar, por encima de un umbral, indemnizada en bonos a veinticinco años. Su elegancia —y su detonador— era la regla de valoración. Usar el valor fiscal declarado por el dueño hacía la reforma autotasadora y volvía de golpe carísima la infradeclaración crónica.',
        'La respuesta de la empresa es la parte que merece estudio. Tenía una reclamación legítima sobre el valor de mercado y ninguna manera de defenderla sin exponer sus declaraciones fiscales. Así que desplazó la disputa a un eje donde la otra parte no tenía réplica: no el precio, sino la lealtad. La aportación de Bernays fue instalar ese marco en la prensa estadounidense años antes de que hiciera falta, de modo que en 1954 funcionaba como trasfondo y no como argumento.',
        'PBSUCCESS triunfó después por información y no por fuerza. Una columna de 480 hombres que apenas se movió, más ataques aéreos y una red de radio rebelde inventada, produjeron una percepción de inevitabilidad sobre la que actuó la oficialidad guatemalteca. Árbenz dimitió sin derrota militar — que es precisamente por qué la operación se leyó como plantilla barata, y por qué después vino bahía de Cochinos.',
      ],
    },
    {
      id: 'scholar',
      label: 'Nivel universitario',
      kind: 'age',
      paragraphs: [
        'El eje historiográfico va de la lectura de captura corporativa de Schlesinger y Kinzer a la ideológico-securitaria de Gleijeses. El trabajo de archivo de Gleijeses, apoyado en fuentes guatemaltecas y entrevistas con participantes supervivientes, sigue siendo la reconstrucción más autorizada de las intenciones del gobierno de Árbenz y de la influencia del PGT, y complica sustancialmente cualquier relato en el que la United Fruit sea causa suficiente.',
        'Secret History, de Cullather, es el contrapeso imprescindible a ambos, por ser la evaluación interna de la propia Agencia: se muestra marcadamente poco persuadida por el análisis de amenaza, es franca sobre el carácter teatral de la operación y resulta útil precisamente porque no se escribió para persuadir al público.',
        'El mecanismo de valoración del Decreto 900 merece más atención de la que suele recibir. Es un caso raro de instrumento redistributivo diseñado para autoaplicarse contra la infradeclaración, y la incapacidad de la empresa de impugnarlo sin autoinculparse fiscalmente es el pivote estructural del episodio entero.',
        'Sobre las consecuencias, el informe de la CEH aporta la base probatoria para tratar 1954 como antecedente del conflicto armado y no como mero hecho previo, sin llegar a una afirmación monocausal. Esa distinción conviene conservarla.',
      ],
    },
    {
      id: 'propaganda',
      label: 'Cómo funcionó el encuadre',
      kind: 'angle',
      paragraphs: [
        'Bernays es la razón de que esto vaya al lado de los panfletos de Drácula y no al lado de una guerra.',
        '**Trabajó años antes de la necesidad.** La campaña para asociar Guatemala con el comunismo empezó bastante antes de que el Decreto 900 fuera una crisis. Cuando hizo falta decidir, el marco no era un argumento que hubiera que ganar — era el supuesto ambiental.',
        '**Suministró experiencia, no afirmaciones.** A los periodistas se les llevaba en avión a Guatemala en viajes organizados con entrevistas concertadas. Lo que escribían les parecía reporterismo de primera mano, porque lo era; la selección había ocurrido más arriba.',
        '**Usó la voz neutra.** El material se movía por lo que parecía un servicio de noticias corriente. La atribución es lo que permite a un lector descontar una fuente, y quitarla quita el descuento.',
        '**Y la época hizo el resto.** Bernays no tuvo que probar que Guatemala fuera soviética. Solo tuvo que lograr que esa pareciera la pregunta relevante, en una década en la que esa pregunta tenía una sola respuesta aceptable.',
      ],
    },
    {
      id: 'from-guatemala',
      label: 'Desde el lado guatemalteco',
      kind: 'contrast',
      paragraphs: [
        'En Guatemala, 1944-1954 tiene nombre — *los diez años de primavera* — y la metáfora lleva dentro el argumento. Fue un intervalo, y todo el mundo sabe qué vino después.',
        'Esos diez años dieron salario mínimo, seguridad social, sindicatos legales, campañas de alfabetización y, con el Decreto 900, tierra para algo así como medio millón de personas en un país de tres millones. Eso no es una nota al pie del golpe; para muchísimas familias es la única década del siglo en la que el Estado actuó a su favor.',
        'Luego se lo quitaron, y lo que siguió no fue un regreso a 1944 sino algo mucho peor: treinta y seis años de guerra, y una comisión de la verdad que tuvo que usar la palabra genocidio sobre la conducta del Estado hacia las comunidades mayas.',
        'Por eso aquí el encuadre importa más que el mecanismo. En Estados Unidos la historia se cuenta a menudo como un error de la Guerra Fría, un cálculo político que ponderar. En Guatemala los diez años son lo que fue real, y 1954 el año en que lo terminó gente a la que le habían contado un cuento sobre ello.',
      ],
    },
  ],

  beforeAfter: {
    label: 'Guatemala, a cada lado de 1954',
    before: {
      title: 'Los diez años de primavera',
      points: [
        'Elecciones libres y un traspaso pacífico del poder',
        'Sindicatos legales, salario mínimo y seguridad social',
        'Tierra repartida a cerca de medio millón de personas',
        'Indemnización pagada en bonos, al valor declarado',
        'Una prensa y un sistema de partidos que funcionaban',
      ],
    },
    after: {
      title: 'Después del golpe',
      points: [
        'Decreto 900 revertido; las fincas devueltas',
        'Partidos políticos prohibidos, constitución suspendida',
        'Ciudadanos analfabetos —la mayoría— sin derecho al voto',
        'Sindicatos desarticulados, miles de detenidos',
        'Guerra civil de 1960 a 1996, unos 200.000 muertos',
      ],
    },
  },

  whatIf: [
    {
      question: '¿Y si la United Fruit hubiera declarado su tierra con honestidad?',
      reasoning: 'El Decreto 900 habría ofrecido algo cercano al valor de mercado, y la disputa por la indemnización —lo único que la empresa podía llevar de verdad a Washington— se evapora en buena medida. Sin un agravio que escalar, defender que una reforma agraria era una emergencia de seguridad se vuelve mucho más difícil.',
      constraint: 'El marco de la Guerra Fría existía por su cuenta, y Washington ya estaba predispuesto a ver el hemisferio en disputa. La empresa aportó urgencia y acceso; probablemente no aportó el apetito de fondo. Había otro pretexto disponible.',
    },
    {
      question: '¿Y si Árbenz hubiera armado a las milicias civiles?',
      reasoning: 'La fuerza invasora era minúscula y estaba parada. Una resistencia armada habría dejado al descubierto con mucha probabilidad que las emisiones eran ficción y habría frenado la columna, porque allí casi no había nada que frenar.',
      constraint: 'Habría supuesto que un presidente esquivara a su propio ejército, que es como empieza un golpe desde el otro lado — y Estados Unidos ya había demostrado que escalaría. El Che Guevara, mirando desde Ciudad de Guatemala, sacó exactamente esa lección y la aplicó en Cuba, donde exigió desmontar el viejo ejército por completo.',
    },
  ],

  quiz: [
    {
      question: '¿Cómo decidía el Decreto 900 cuánto pagar por la tierra expropiada?',
      options: [
        'Una tasación internacional independiente',
        'El valor que el dueño había declarado a efectos fiscales',
        'Una tarifa fija por acre fijada por el gobierno',
        'Nada — la tierra se confiscaba',
      ],
      answerIndex: 1,
      explains: 'Ese es el pivote de la historia entera. La United Fruit llevaba años infravalorando su tierra para pagar menos impuestos, y la reforma la tomó por su palabra.',
    },
    {
      question: '¿Qué hizo la United Fruit cuando no pudo ganar la discusión sobre la valoración?',
      options: [
        'Llevó a Guatemala a un arbitraje internacional',
        'Vendió sus propiedades guatemaltecas',
        'Recalculó y pagó los impuestos atrasados',
        'Cambió el tema al comunismo, con una campaña de relaciones públicas',
      ],
      answerIndex: 3,
      explains: 'Corregir la valoración en público significaba admitir para qué había servido la cifra baja. Edward Bernays reencuadró la disputa como cuestión de seguridad de la Guerra Fría.',
    },
    {
      question: '¿Qué hizo realmente que el ejército guatemalteco se retirara en 1954?',
      options: [
        'Una batalla decisiva a las afueras de la capital',
        'Una emisora de la CIA que emitía un ejército rebelde que no existía',
        'Un bloqueo naval',
        'Una huelga general',
      ],
      answerIndex: 1,
      explains: 'La fuerza terrestre eran unos 480 hombres y apenas se movió. La Voz de la Liberación informaba de victorias, columnas y unidades inventadas, y el ejército actuó como si fueran reales.',
    },
    {
      question: '¿De dónde viene la expresión «república bananera»?',
      options: [
        'De la cobertura de la prensa estadounidense del golpe de 1954',
        'De un libro de O. Henry de 1904, escrito mientras se escondía en Honduras',
        'De un eslogan publicitario de la United Fruit',
        'De un discurso de Árbenz',
      ],
      answerIndex: 1,
      explains: 'Es cincuenta años anterior al golpe. O. Henry la acuñó en Cabbages and Kings siendo fugitivo de una acusación de desfalco en Texas.',
    },
  ],

  sources: [
    {
      id: 'decree-900',
      kind: 'primary',
      author: 'Republic of Guatemala',
      title: 'Decreto 900: Ley de Reforma Agraria',
      year: 1952,
      detail: 'Promulgado el 17 de junio de 1952',
      note: 'El texto mismo: solo tierra sin cultivar, por encima de un umbral de tamaño, indemnizada en bonos a 25 años al valor fiscal declarado.',
    },
    {
      id: 'arbenz-1951',
      kind: 'primary',
      author: 'Jacobo Árbenz Guzmán',
      title: 'Inaugural address',
      year: 1951,
      detail: 'Ciudad de Guatemala, 15 de marzo de 1951',
      note: 'Contiene su descripción del objetivo como convertir una economía semifeudal en un Estado capitalista moderno.',
    },
    {
      id: 'ceh-1999',
      kind: 'primary',
      author: 'Comisión para el Esclarecimiento Histórico',
      title: 'Guatemala: Memoria del Silencio',
      year: 1999,
      detail: 'Informe de la comisión de la verdad respaldada por la ONU, 12 volúmenes',
      note: 'El registro autorizado de la guerra civil: atribución del 93 % de las violaciones documentadas a fuerzas del Estado, y la conclusión sobre el genocidio.',
    },
    {
      id: 'cullather-1999',
      kind: 'archive',
      author: 'Nicholas Cullather',
      title: 'Secret History: The CIA’s Classified Account of Its Operations in Guatemala, 1952–1954',
      year: 1999,
      detail: 'Stanford University Press. ISBN 978-0-8047-5468-2',
      note: 'La historia interna de la propia Agencia, escrita para uso interno y desclasificada después. Inusualmente escéptica sobre la amenaza en la que actuó.',
    },
    {
      id: 'gleijeses-1991',
      kind: 'book',
      author: 'Piero Gleijeses',
      title: 'Shattered Hope: The Guatemalan Revolution and the United States, 1944–1954',
      year: 1991,
      detail: 'Princeton University Press. ISBN 978-0-691-02556-8',
      note: 'El relato académico de referencia, y el tratamiento de archivo más sólido sobre lo que el gobierno de Árbenz pretendía realmente.',
    },
    {
      id: 'schlesinger-kinzer-1982',
      kind: 'book',
      author: 'Stephen Schlesinger and Stephen Kinzer',
      title: 'Bitter Fruit: The Story of the American Coup in Guatemala',
      year: 1982,
      detail: 'Doubleday; edición revisada Harvard University Press, 2005. ISBN 978-0-674-01930-0',
      note: 'El relato de captura corporativa, y la fuente de casi todo el conocimiento popular del episodio. Lo más sólido sobre las conexiones con la United Fruit.',
    },
    {
      id: 'ohenry-1904',
      kind: 'primary',
      author: 'O. Henry (William Sydney Porter)',
      title: 'Cabbages and Kings',
      year: 1904,
      detail: 'McClure, Phillips & Co.',
      note: 'Donde se acuña «república bananera», medio siglo antes del golpe al que hoy se asocia la expresión.',
    },
  ],
}
