import type { Story } from '../types'

export const unitedFruit: Story = {
  slug: 'united-fruit',
  title: 'The Company That Owned a Country',
  subtitle: 'El Pulpo — how a fruit company, a PR man and the CIA ended ten years of democracy.',
  hook: 'A country offered to buy back its own idle land at the owner’s own price — and that was enough to end its democracy for forty years.',
  era: 'contemporary',
  category: 'milestones',
  years: [1899, 1996],
  regions: ['Guatemala', 'United States'],
  nodes: ['guatemala-coup', 'united-fruit', 'guatemala', 'decree-900', 'public-relations'],
  tags: ['empire', 'propaganda', 'cold-war', 'economics', 'latin-america', 'legend'],
  readingMinutes: 11,
  reviewed: '2026-08-03',
  mood: 'jungle',

  reel: [
    { beat: 'hook', punch: true, text: 'A country offered to buy land at the price its owner had sworn it was worth,' },
    { beat: 'hook', text: 'and that was the crime.' },
    { beat: 'worldBefore', kicker: '1899', text: 'An American company starts planting bananas in Central America,' },
    { beat: 'worldBefore', text: 'and because bananas rot it lays the railways to move them,' },
    { beat: 'worldBefore', text: 'then buys the ports the railways run to, then the telegraph wires above them,' },
    { beat: 'worldBefore', mark: 'web', text: 'until every harvest in the country moves on its rails, at its price.' },
    { beat: 'worldBefore', punch: true, text: 'Guatemalans have a name for it. El Pulpo. The octopus.' },
    { beat: 'problem', mark: 'imbalance', text: 'It becomes the largest landowner in the country and plants almost none of it,' },
    { beat: 'problem', text: 'holding the rest empty so that nobody else can farm it either,' },
    { beat: 'problem', punch: true, text: 'in a country where most people have no land at all.' },
    { beat: 'problem', kicker: '1944', text: 'Then Guatemala throws out its dictator and starts to vote,' },
    { beat: 'problem', text: 'and the ten years that follow are still called the Spring.' },
    { beat: 'story', kicker: '1951', text: 'Árbenz is elected, and he is no revolutionary —' },
    { beat: 'story', text: 'he wants a modern country, and a modern country cannot run on idle land.' },
    { beat: 'story', kicker: '1952', text: 'So the state buys the unused fields and hands them to farmers,' },
    { beat: 'story', text: 'not seized but paid for, in government bonds,' },
    { beat: 'story', punch: true, mark: 'reversal', text: 'at exactly the value the company had been telling the tax man for years.' },
    { beat: 'story', punch: true, text: '$600,000, said Guatemala. $16 million, said the company.' },
    { beat: 'story', text: 'It was probably right. It simply could not say why.' },
    { beat: 'whyItHappened', text: 'So it stops arguing about land altogether' },
    { beat: 'whyItHappened', text: 'and hires Edward Bernays, the man who invented public relations,' },
    { beat: 'whyItHappened', mark: 'echo', text: 'who turns a tax dispute into a Soviet beachhead ninety miles from the canal,' },
    { beat: 'whyItHappened', text: 'in a Washington where the Secretary of State and the CIA chief' },
    { beat: 'whyItHappened', punch: true, text: 'had both worked for the company’s law firm.' },
    { beat: 'consequences', kicker: '1954', text: 'About four hundred and eighty men cross the border and barely move,' },
    { beat: 'consequences', text: 'unmarked planes bomb the capital,' },
    { beat: 'consequences', mark: 'collapse', text: 'and a radio station plays the part of an army that does not exist.' },
    { beat: 'consequences', punch: true, text: 'Guatemala had a real army. It believed the radio.' },
    { beat: 'consequences', text: 'Árbenz resigns undefeated, the land goes back, and a thirty-six year war begins' },
    { beat: 'whyItMatters', punch: true, text: 'that kills two hundred thousand people — and the company is called Chiquita now.' },
  ],

  beats: {
    worldBefore: {
      heading: 'The world before',
      paragraphs: [
        'The United Fruit Company was assembled in 1899 out of two things: a Boston fruit importer, and a railway man.',
        'That combination is the whole story. Minor Keith had been building railways in Costa Rica and discovered that a railway through empty country loses money — unless you plant something alongside it that has to be carried. He planted bananas.',
        'The company that resulted did not think of itself as a farm. It thought of itself as a logistics business that happened to grow fruit, and it bought the things logistics needs: land, track, ships, docks, and the telegraph lines that told you where everything was.',
        'In Guatemala this went furthest. By the 1940s United Fruit was the country’s largest landowner and largest employer. It controlled the International Railways of Central America, and therefore Puerto Barrios, the country’s only significant Caribbean port. Anyone else’s coffee moved to market on its rails, through its harbour, at its rates.',
        'Guatemalans called it *El Pulpo*. The octopus.',
      ],
      aside: {
        kind: 'number',
        label: 'What "landowner" meant',
        body: 'Most of what the company held was not planted. Banana cultivation exhausts and infects soil, so it kept large reserves against future disease. In a country where roughly 2% of owners held about 70% of the arable land, an enormous idle estate was not a neutral fact.',
      },
      sourceIds: ['gleijeses-1991', 'schlesinger-kinzer-1982'],
    },

    problem: {
      heading: 'The problem',
      paragraphs: [
        'In October 1944 a coalition of students, teachers and junior officers overthrew the dictator Jorge Ubico’s successor, and Guatemala began holding real elections.',
        'What followed is remembered there as the Ten Years of Spring. A minimum wage. Social security. Trade unions made legal. Literacy campaigns. Juan José Arévalo governed for six years and handed power to an elected successor, which had not happened before.',
        'That successor, elected in 1951 with about two-thirds of the vote, was Jacobo Árbenz — an army officer, the son of a Swiss pharmacist, and a man whose stated ambition was almost aggressively unrevolutionary. He said he wanted to convert Guatemala from a backward country with a semi-feudal economy into a modern capitalist state.',
        'You cannot do that with idle land. Roughly three-quarters of the arable land was held by a tiny number of owners, and most of it was not being farmed. The country imported food it had the ground to grow.',
        'So the problem Árbenz set out to solve was, on its face, a problem of capitalist efficiency. The solution he chose is what made him unforgivable.',
      ],
      sourceIds: ['gleijeses-1991'],
    },

    story: {
      heading: 'The story',
      paragraphs: [
        'Decree 900 became law in June 1952. It is worth being precise about it, because almost everything said about it at the time was not.',
        'It applied only to **uncultivated** land, and only on estates above a size threshold. Farms in production were untouched, regardless of size. The land was not confiscated: the state bought it, paying in twenty-five-year government bonds at 3%.',
        'And the price was set at the value the owner had declared for tax purposes.',
        'That last clause is the entire collision. United Fruit had spent decades declaring its Guatemalan holdings at a small fraction of their market value, because that is what its tax bill was calculated on. When the government offered to buy 234,000 uncultivated acres, it offered a little over $600,000 — the company’s own number.',
        'United Fruit replied that the land was worth nearly $16 million, and the United States State Department formally backed that figure.',
        'The company was probably right about the market value. It simply could not say so without explaining what the other number had been for.',
        '**Then the argument changed subject.** Not to land, and not to compensation, but to communism.',
        'United Fruit had retained Edward Bernays — Sigmund Freud’s nephew, the man who had coined "public relations" precisely because "propaganda" had become unusable after the First World War. Bernays ran what he later described quite openly. He organised tours of Guatemala for American journalists, arranged their itineraries and their interviews, and supplied the interpretation. He seeded material with a fake-neutral news service. He worked the story for years before it was needed.',
        'It landed. The New York Times, Time, Newsweek and the Herald Tribune ran the framing: a Soviet beachhead in Central America, ninety miles from the Panama Canal.',
        'The framing met a Washington unusually prepared to accept it. Secretary of State John Foster Dulles had been a senior partner at Sullivan & Cromwell, the firm that represented United Fruit. His brother Allen Dulles, Director of Central Intelligence, had worked at the same firm. The Assistant Secretary of State for Inter-American Affairs, John Moors Cabot, was from a family with company stock. Eisenhower’s personal secretary, Ann Whitman, was married to United Fruit’s head of public relations.',
        'None of that is a conspiracy theory; it is a list of employment records. What it produced was a room with no one in it inclined to ask whether a land valuation dispute was really a Soviet operation.',
        '**Operation PBSUCCESS was approved in 1953.**',
        'It was not an invasion. Carlos Castillo Armas crossed from Honduras with roughly 480 men and advanced barely at all. Unmarked aircraft flown by American pilots bombed Guatemala City. And a CIA-run radio station, the Voice of Liberation, broadcast as though it were a large rebel army in the field — announcing victories that had not happened, describing columns that did not exist, and naming units that had never been formed.',
        'The Guatemalan army believed the radio. Árbenz, unable to trust his own officers and refusing to arm civilian militias, resigned on 27 June 1954.',
        'He had not been defeated. He had been convinced.',
      ],
      aside: {
        kind: 'voice',
        label: 'Árbenz, inaugural address, 1951',
        body: 'He described his aim as converting Guatemala from a backward country with a predominantly feudal economy into a modern capitalist state — a sentence quoted often since, because it is difficult to reconcile with what he was accused of being.',
        sourceId: 'arbenz-1951',
      },
      sourceIds: ['gleijeses-1991', 'schlesinger-kinzer-1982', 'cullather-1999', 'decree-900'],
    },

    whyItHappened: {
      heading: 'Why it happened',
      paragraphs: [
        'Three things had to be true at once, and each is worth separating, because the popular version collapses them into "the CIA did it for bananas".',
        '**The company had a real grievance and a fatal one.** Its land genuinely was worth more than the compensation offered. But the number it was offered was its own, and correcting it in public meant confessing to years of understated tax. It could not win the argument it actually had, so it needed a different argument.',
        '**Public relations had become a profession, and this was its proving ground.** Bernays was not spinning a news cycle; he ran a multi-year campaign to make a specific interpretation feel like background knowledge before anyone needed to act on it. By 1954 the American press did not have to be persuaded that Guatemala was communist. It already assumed so.',
        '**And the Cold War made every local dispute translatable.** A land reform in a small country is a domestic policy question. Restated as a question about which side Guatemala was on, it became an American security matter — and once it was that, the details of acreage and valuation stopped being relevant to the decision.',
        'The specific personal connections between United Fruit and the Eisenhower administration are real and documented. What they best explain is not that the coup happened, but that nobody with standing pushed back.',
        'It is also worth stating what the atlas does not claim. The Guatemalan Party of Labour did have influence with Árbenz, and he did accept an arms shipment from Czechoslovakia in May 1954 — after the US had embargoed weapons to him. Historians disagree about how much that mattered. What they do not disagree about is that the Soviet Union had almost no presence in Guatemala, and that the country was not being run from Moscow.',
      ],
      sourceIds: ['cullather-1999', 'gleijeses-1991', 'schlesinger-kinzer-1982'],
    },

    consequences: {
      heading: 'What changed',
      paragraphs: [
        'The operation was judged a triumph, and that judgement did more damage than the operation.',
      ],
      shortTerm: [
        'Castillo Armas reversed Decree 900 within a year. The expropriated land went back to its former owners, United Fruit included.',
        'Political parties were banned, the 1945 constitution suspended, and illiterate citizens — the majority — were disenfranchised.',
        'Thousands were detained; unions were broken. Castillo Armas was himself assassinated in 1957.',
        'Árbenz went into an exile that lasted the rest of his life, moving between half a dozen countries. He died in Mexico in 1971.',
      ],
      longTerm: [
        'Guatemala’s civil war began in 1960 and ran until 1996 — thirty-six years, roughly 200,000 dead or disappeared.',
        'The UN-backed truth commission attributed 93% of documented violations to state forces and found that acts of genocide had been committed against Maya communities.',
        'PBSUCCESS became a template. The same planners, confident from Guatemala, went on to the Bay of Pigs in 1961, where the assumptions failed against an opponent who had studied 1954 closely.',
        'United Fruit did not profit for long. Antitrust action forced it to divest, and after a 1970 merger and a bribery scandal in 1975 the surviving business was renamed Chiquita.',
      ],
      unexpected: [
        'A young Argentine doctor named Ernesto Guevara was in Guatemala City in 1954 and watched it happen. He drew the conclusion that a revolution which leaves the army intact will be removed, and carried it to Cuba.',
        'The CIA wrote its own classified history of the operation, and it is unusually critical. Declassified in the 1990s, it is now one of the best sources on how much of the "rebel army" was a radio programme.',
        'The phrase "banana republic" has nothing to do with 1954. O. Henry coined it in 1904, writing in Honduras while a fugitive from an embezzlement charge in Texas.',
        'Árbenz’s remains were returned to Guatemala in 1995, and in 2011 the Guatemalan government formally apologised to his family.',
      ],
      sourceIds: ['ceh-1999', 'cullather-1999', 'schlesinger-kinzer-1982'],
    },

    whyItMatters: {
      heading: 'Why it still matters',
      paragraphs: [
        'The useful thing here is not "American companies are bad". It is the mechanism, which is portable and still in use.',
        'Someone with a commercial interest could not win the argument they actually had — a valuation dispute they would have lost by their own numbers. So they changed the subject to one where the other side could not answer: loyalty. Not "pay us more" but "they are on the other side".',
        'That substitution worked because a professional had spent years making the replacement subject feel like common knowledge, and because the era supplied a binary that swallowed local detail. The decision-makers were not bribed. They were simply operating inside a story that had already been told to them.',
        'Guatemala paid for it with thirty-six years of war and two hundred thousand people.',
        'And the sharpest detail is the smallest one. The land was to be bought at the price its owner had sworn it was worth. The whole catastrophe begins with a company being taken at its word.',
      ],
      sourceIds: ['gleijeses-1991', 'ceh-1999'],
    },
  },

  timeline: [
    { year: 1899, title: 'United Fruit is founded', detail: 'A Boston fruit importer merges with Minor Keith’s Central American railway interests. Track and fruit in one company from the start.', pivotal: true },
    { year: 1904, title: 'The phrase is coined', detail: 'O. Henry, writing in Honduras as a fugitive, invents "banana republic" in Cabbages and Kings — fifty years before the coup it is now used for.' },
    { year: 1928, title: 'The banana massacre', detail: 'Colombian troops fire on striking United Fruit workers at Ciénaga. The death toll is disputed to this day.', confidence: 'contested' },
    { year: 1944, date: '1944-10', title: 'The October Revolution', detail: 'Students, teachers and junior officers overthrow the dictatorship. Guatemala begins holding real elections.', pivotal: true },
    { year: 1951, title: 'Árbenz is elected', detail: 'Roughly two-thirds of the vote, on a platform of modernising a semi-feudal economy.', pivotal: true },
    { year: 1952, date: '1952-06', title: 'Decree 900', detail: 'Uncultivated land on large estates is bought by the state in bonds, at the value the owner declared for tax.', pivotal: true },
    { year: 1953, title: 'The valuation fight', detail: 'Guatemala offers about $600,000 for 234,000 uncultivated acres. The company and the State Department demand nearly $16 million.', pivotal: true },
    { year: 1953, title: 'PBSUCCESS is approved', detail: 'Eisenhower authorises a covert operation to remove Árbenz. Budget in the millions; force, deliberately, tiny.' },
    { year: 1954, date: '1954-05', title: 'The Czech arms shipment', detail: 'Árbenz buys weapons from Czechoslovakia after a US embargo. It is used as confirmation of everything already alleged.', confidence: 'contested' },
    { year: 1954, date: '1954-06-18', title: 'The invasion that mostly does not move', detail: 'Castillo Armas crosses from Honduras with around 480 men. The Voice of Liberation broadcasts a much larger war.', pivotal: true },
    { year: 1954, date: '1954-06-27', title: 'Árbenz resigns', detail: 'Undefeated in the field, unable to trust his officers, and unwilling to arm civilians. He leaves for exile.', pivotal: true },
    { year: 1955, title: 'The land goes back', detail: 'Decree 900 is reversed, parties are banned, and illiterate citizens lose the vote.' },
    { year: 1960, title: 'The civil war begins', detail: 'It runs until 1996. Roughly 200,000 people are killed or disappeared.', pivotal: true },
    { year: 1961, title: 'The Bay of Pigs', detail: 'The same planners run the same playbook against Cuba, where the lesson of 1954 had been studied carefully.' },
    { year: 1970, title: 'United Fruit becomes United Brands', detail: 'Antitrust action and disease have already broken the old structure. After a 1975 bribery scandal it is renamed Chiquita.' },
    { year: 1999, title: 'The truth commission reports', detail: 'The UN-backed CEH attributes 93% of documented violations to state forces and finds acts of genocide against Maya communities.', pivotal: true },
    { year: 2011, title: 'Guatemala apologises', detail: 'The government formally apologises to Árbenz’s family, fifty-seven years after the coup.' },
  ],

  causeEffect: [
    { cause: 'A railway through empty country loses money', effect: 'The railway company plants bananas along the track', because: 'A line only pays if there is freight, so the freight had to be created.' },
    { cause: 'The company buys the port, the rails and the telegraph', effect: 'Everyone else’s exports move at its price', because: 'Owning the only route to market is more durable than owning the crop.' },
    { cause: 'The company understates its land value for tax', effect: 'Compensation under Decree 900 is calculated on that figure', because: 'The law deliberately used the owner’s own declared value, which made lying about it expensive exactly once.' },
    { cause: 'The company cannot win a valuation argument', effect: 'It changes the subject to communism', because: 'Correcting the number in public meant admitting what the number had been for.' },
    { cause: 'Bernays runs a multi-year press campaign', effect: 'Americans already believe Guatemala is a Soviet beachhead', because: 'A frame installed years in advance is not experienced as persuasion; it is experienced as background knowledge.' },
    { cause: 'The Cold War supplies a binary', effect: 'A land reform becomes a security question', because: 'Once a dispute is about which side you are on, the details of the dispute stop being decision-relevant.' },
    { cause: 'A radio station reports a war that is not happening', effect: 'The Guatemalan army stops fighting', because: 'An army that believes it is already surrounded behaves as though it is.' },
    { cause: 'The coup succeeds cheaply', effect: 'The method is reused at the Bay of Pigs', because: 'A success nobody examines becomes a template, and the assumptions travel with it unexamined.' },
  ],

  myths: [
    {
      myth: 'Árbenz fell because Guatemala had no army to resist the invasion.',
      reality: 'Guatemala had a standing army considerably larger than the roughly 480 men who crossed from Honduras, and that force barely advanced. What defeated it was information: unmarked air attacks and a CIA radio station broadcasting as a large rebel army, reporting victories and naming units that did not exist. The officer corps believed it, and Árbenz could not rely on officers who thought they had already lost.',
      whyItPersists: 'A coup implies a battle, so the story gets retold as one. The truth — that an army stood down because of a radio programme — is stranger and much harder to picture.',
      sourceIds: ['cullather-1999', 'gleijeses-1991'],
    },
    {
      myth: '"Banana republic" was coined for Guatemala in 1954.',
      reality: 'O. Henry invented the phrase in Cabbages and Kings in 1904, based on the year he spent in Honduras avoiding an embezzlement charge in Texas. It predates the coup by half a century.',
      whyItPersists: 'The phrase fits 1954 so exactly that it feels like it must have been made for it.',
      sourceIds: ['ohenry-1904'],
    },
    {
      myth: 'Árbenz was a communist, and the coup stopped a Soviet takeover.',
      reality: 'Árbenz was not a party member and described his goal as building a modern capitalist state. Communists had influence in his coalition and he did buy Czech arms after a US embargo, but the Soviet Union had almost no presence in Guatemala. The CIA’s own declassified history is notably unconvinced by the threat it acted on.',
      whyItPersists: 'It was the official justification, repeated for decades, and it was manufactured by professionals years before it was needed.',
      sourceIds: ['cullather-1999', 'gleijeses-1991', 'arbenz-1951'],
    },
    {
      myth: 'Decree 900 seized land without compensation.',
      reality: 'It applied only to uncultivated land above a size threshold, and the state paid in twenty-five-year bonds. The dispute was never about whether to pay — it was about the price, which the law set at the owner’s own declared tax value.',
      whyItPersists: '"Expropriation" was the word used at the time, and it carries an implication of confiscation the decree does not support.',
      sourceIds: ['decree-900', 'gleijeses-1991'],
    },
    {
      myth: 'The CIA overthrew Árbenz with an invading army.',
      reality: 'The ground force was about 480 men and barely advanced. The decisive weapons were unmarked aircraft and a radio station impersonating a large rebel army — reporting victories, columns and units that did not exist.',
      whyItPersists: 'A coup implies a battle. This one was mostly a broadcast, which is harder to picture and much stranger.',
      sourceIds: ['cullather-1999', 'schlesinger-kinzer-1982'],
    },
  ],

  disagreements: [
    {
      question: 'Was this done for United Fruit, or for the Cold War?',
      positions: [
        { view: 'The company drove it. Its lobbying, its lawyers in the cabinet and its PR campaign created both the pressure and the justification.', heldBy: 'Schlesinger and Kinzer, and most popular accounts since', sourceId: 'schlesinger-kinzer-1982' },
        { view: 'Washington would have acted anyway. The administration genuinely believed the hemisphere was contested, and the company supplied a convenient case rather than the motive.', heldBy: 'Gleijeses, and the CIA’s own internal history', sourceId: 'gleijeses-1991' },
      ],
      atlasPosition: 'The atlas reports the documented connections — the Dulles brothers’ firm, the Whitman marriage, the Bernays campaign — and does not assert that the coup would not have happened without them. Both readings agree the threat was overstated; they disagree about who most needed it overstated.',
    },
    {
      question: 'How much communist influence was there really?',
      positions: [
        { view: 'Meaningful. The PGT had real influence over agrarian policy and access to Árbenz, and the Czech arms purchase was a genuine alignment.', heldBy: 'Contemporary US assessments, and some later scholarship' },
        { view: 'Marginal to the outcome. Soviet involvement was negligible, and the reform programme was recognisably capitalist and constitutional.', heldBy: 'Gleijeses and the weight of subsequent archival work', sourceId: 'gleijeses-1991' },
      ],
      atlasPosition: 'The atlas states that communists had influence and that the Soviet Union did not. It treats "Guatemala was becoming a Soviet satellite" as unsupported, which is also how the CIA’s own declassified history reads it.',
    },
  ],

  didYouKnow: [
    'The compensation formula used the value each owner had declared for tax. United Fruit had spent years declaring its land nearly worthless.',
    'Edward Bernays, who ran the press campaign, was Sigmund Freud’s nephew and coined the term "public relations" because "propaganda" had become unusable after 1918.',
    'The Secretary of State and the Director of the CIA had both worked at the law firm that represented United Fruit.',
    'The decisive weapon was a radio station. It described a rebel army that did not exist, and the Guatemalan army believed it.',
    'Che Guevara was in Guatemala City in 1954 and took away one lesson: a revolution that leaves the old army intact does not survive.',
    'The CIA’s own classified history of the operation, declassified in the 1990s, is one of the most sceptical accounts of it.',
    '"Banana republic" was coined in 1904 by O. Henry, who was in Honduras hiding from a fraud charge.',
  ],

  lenses: [
    {
      id: 'one-minute',
      label: 'In one minute',
      kind: 'length',
      paragraphs: [
        'United Fruit was founded in 1899 by merging a fruit importer with a railway builder, and in Guatemala it ended up owning the largest estates, the railway, the only Caribbean port and the telegraph. Guatemalans called it El Pulpo — the octopus.',
        'After 1944 Guatemala became a democracy. In 1952 President Árbenz passed Decree 900: the state would buy uncultivated land from large estates, paying in bonds, at the value the owner had declared for tax. United Fruit had understated that value for years, so the offer came to about $600,000 for land it now said was worth $16 million.',
        'Unable to win that argument without admitting the tax position, the company changed the subject. Edward Bernays ran a years-long campaign presenting Guatemala as a Soviet beachhead, in a Washington where the Secretary of State and the CIA Director had both worked at the company’s law firm.',
        'In 1954 the CIA ran PBSUCCESS: about 480 men who barely advanced, unmarked bombers, and a radio station impersonating a large rebel army. Árbenz resigned undefeated. The reform was reversed, and the civil war that followed ran thirty-six years and killed around 200,000 people.',
      ],
    },
    {
      id: 'age-16',
      label: 'Explain like I’m 16',
      kind: 'age',
      paragraphs: [
        'Start with the structure. United Fruit was not primarily a plantation business; it was vertically integrated infrastructure. Owning the rails and the only deepwater Caribbean port meant it set the effective export price for everyone in the country, which is a far more durable position than owning the crop.',
        'Decree 900 was a targeted efficiency reform, not a collectivisation: uncultivated land only, above a threshold, compensated in twenty-five-year bonds. Its elegance — and its detonator — was the valuation rule. Using the owner’s declared tax value made the reform self-pricing and made chronic under-declaration suddenly very expensive.',
        'The company’s response is the part worth studying. It had a legitimate claim about market value and no way to make it without exposing its tax filings. So it shifted the dispute onto an axis where the other side had no reply: not price, but allegiance. Bernays’ contribution was to install that frame in the American press years before it was needed, so that by 1954 it functioned as background rather than argument.',
        'PBSUCCESS then succeeded through information rather than force. A 480-man column that scarcely moved, plus air attacks and a fabricated rebel radio network, produced a perception of inevitability that the Guatemalan officer corps acted on. Árbenz resigned without military defeat — which is precisely why the operation was read as a cheap template, and why the Bay of Pigs followed.',
      ],
    },
    {
      id: 'scholar',
      label: 'University level',
      kind: 'age',
      paragraphs: [
        'The historiographical axis runs between Schlesinger and Kinzer’s corporate-capture reading and Gleijeses’ security-ideological one. Gleijeses’ archival work, drawing on Guatemalan sources and interviews with surviving participants, remains the most authoritative reconstruction of the Árbenz government’s intentions and of PGT influence, and it substantially complicates any account in which United Fruit is a sufficient cause.',
        'Cullather’s Secret History is the indispensable counterweight to both, being the Agency’s own internal assessment: it is markedly unpersuaded by the threat assessment, candid about the theatrical character of the operation, and useful precisely because it was not written to persuade the public.',
        'The Decree 900 valuation mechanism deserves more attention than it usually receives. It is a rare instance of a redistributive instrument designed to be self-enforcing against under-declaration, and the company’s inability to contest it without fiscal self-incrimination is the structural pivot of the entire episode.',
        'On consequences, the CEH report supplies the evidentiary basis for treating 1954 as an antecedent of the armed conflict rather than merely as a prior event, while stopping short of a monocausal claim. That distinction is worth preserving.',
      ],
    },
    {
      id: 'propaganda',
      label: 'How the framing worked',
      kind: 'angle',
      paragraphs: [
        'Bernays is the reason this belongs beside the Dracula pamphlets rather than beside a war.',
        '**He worked years ahead of the need.** The campaign to associate Guatemala with communism began well before Decree 900 was a crisis. By the time a decision was required, the frame was not an argument anyone had to win — it was the ambient assumption.',
        '**He supplied experience, not claims.** Journalists were flown to Guatemala on organised tours with arranged interviews. What they wrote felt like first-hand reporting to them, because it was; the selection had happened upstream.',
        '**He used the neutral voice.** Material moved through what appeared to be an ordinary news service. Attribution is what lets a reader discount a source, and removing it removes the discount.',
        '**And the era did the rest.** Bernays did not have to prove Guatemala was Soviet. He only had to make the question feel like the relevant one, in a decade when that question had one acceptable answer.',
      ],
    },
    {
      id: 'from-guatemala',
      label: 'From the Guatemalan side',
      kind: 'contrast',
      paragraphs: [
        'In Guatemala 1944 to 1954 has a name — *los diez años de primavera*, the ten years of spring — and the metaphor carries the point. It was an interval, and everyone knows what came after it.',
        'Those ten years produced a minimum wage, social security, legal unions, literacy campaigns and, in Decree 900, land for something like half a million people in a country of three million. That is not a footnote to the coup; for a great many families it is the only decade in the century when the state acted in their interest.',
        'Then it was taken back, and what followed was not a return to 1944 but something far worse: thirty-six years of war, and a truth commission that had to use the word genocide about the state’s conduct toward Maya communities.',
        'Which is why the framing matters here more than the mechanism. The story is often told in the United States as a Cold War error, a policy miscalculation to be weighed. In Guatemala the ten years are the thing that was real, and 1954 is the year it was ended by people who had been told a story about it.',
      ],
    },
  ],

  beforeAfter: {
    label: 'Guatemala, either side of 1954',
    before: {
      title: 'The ten years of spring',
      points: [
        'Free elections and a peaceful transfer of power',
        'Legal trade unions, a minimum wage and social security',
        'Land redistributed to roughly half a million people',
        'Compensation paid in bonds, at declared value',
        'A press and party system that functioned',
      ],
    },
    after: {
      title: 'After the coup',
      points: [
        'Decree 900 reversed; the estates returned',
        'Political parties banned, the constitution suspended',
        'Illiterate citizens — the majority — disenfranchised',
        'Unions broken, thousands detained',
        'Civil war from 1960 to 1996, some 200,000 dead',
      ],
    },
  },

  whatIf: [
    {
      question: 'What if United Fruit had declared its land honestly for tax?',
      reasoning: 'Decree 900 would have offered something close to market value, and the compensation dispute — the thing the company could actually take to Washington — largely evaporates. Without a grievance to escalate, the case for treating a land reform as a security emergency gets much harder to make.',
      constraint: 'The Cold War frame existed independently, and Washington was already disposed to see the hemisphere as contested. The company supplied urgency and access; it probably did not supply the underlying appetite. A different pretext was available.',
    },
    {
      question: 'What if Árbenz had armed the civilian militias?',
      reasoning: 'The invading force was tiny and stationary. Armed resistance would very likely have exposed the radio broadcasts as fiction and stopped the column, because there was almost nothing there to stop.',
      constraint: 'It would have meant a president bypassing his own army, which is how a coup starts from the other direction — and the United States had already demonstrated it would escalate. Che Guevara, watching from Guatemala City, drew exactly this lesson and applied it in Cuba, where it required dismantling the old army entirely.',
    },
  ],

  quiz: [
    {
      question: 'How did Decree 900 decide what to pay for expropriated land?',
      options: [
        'An independent international valuation',
        'The value the owner had declared for tax purposes',
        'A fixed rate per acre set by the government',
        'Nothing — the land was confiscated',
      ],
      answerIndex: 1,
      explains: 'That is the pivot of the whole story. United Fruit had understated its land value for years to reduce tax, and the reform took it at its word.',
    },
    {
      question: 'What did United Fruit do when it could not win the valuation argument?',
      options: [
        'Took Guatemala to international arbitration',
        'Sold its Guatemalan holdings',
        'Recalculated and paid the back taxes',
        'Changed the subject to communism, via a public relations campaign',
      ],
      answerIndex: 3,
      explains: 'Correcting the valuation in public meant admitting what the low figure had been for. Edward Bernays reframed the dispute as a Cold War security question instead.',
    },
    {
      question: 'What actually made the Guatemalan army stand down in 1954?',
      options: [
        'A decisive battle outside the capital',
        'A CIA radio station broadcasting a rebel army that did not exist',
        'A naval blockade',
        'A general strike',
      ],
      answerIndex: 1,
      explains: 'The ground force was around 480 men and barely moved. The Voice of Liberation reported victories, columns and units that were invented, and the army acted as though they were real.',
    },
    {
      question: 'Where does the phrase "banana republic" come from?',
      options: [
        'US press coverage of the 1954 coup',
        'A 1904 book by O. Henry, written while he hid in Honduras',
        'A United Fruit advertising slogan',
        'A speech by Árbenz',
      ],
      answerIndex: 1,
      explains: 'It predates the coup by fifty years. O. Henry coined it in Cabbages and Kings while a fugitive from an embezzlement charge in Texas.',
    },
  ],

  sources: [
    {
      id: 'decree-900',
      kind: 'primary',
      author: 'Republic of Guatemala',
      title: 'Decreto 900: Ley de Reforma Agraria',
      year: 1952,
      detail: 'Enacted 17 June 1952',
      note: 'The text itself: uncultivated land only, above a size threshold, compensated in 25-year bonds at declared tax value.',
    },
    {
      id: 'arbenz-1951',
      kind: 'primary',
      author: 'Jacobo Árbenz Guzmán',
      title: 'Inaugural address',
      year: 1951,
      detail: 'Guatemala City, 15 March 1951',
      note: 'Contains his description of the goal as converting a semi-feudal economy into a modern capitalist state.',
    },
    {
      id: 'ceh-1999',
      kind: 'primary',
      author: 'Comisión para el Esclarecimiento Histórico',
      title: 'Guatemala: Memoria del Silencio',
      year: 1999,
      detail: 'UN-backed truth commission report, 12 volumes',
      note: 'The authoritative record of the civil war: attribution of 93% of documented violations to state forces, and the genocide finding.',
    },
    {
      id: 'cullather-1999',
      kind: 'archive',
      author: 'Nicholas Cullather',
      title: 'Secret History: The CIA’s Classified Account of Its Operations in Guatemala, 1952–1954',
      year: 1999,
      detail: 'Stanford University Press. ISBN 978-0-8047-5468-2',
      note: 'The Agency’s own internal history, written for internal use and later declassified. Unusually sceptical about the threat it acted on.',
    },
    {
      id: 'gleijeses-1991',
      kind: 'book',
      author: 'Piero Gleijeses',
      title: 'Shattered Hope: The Guatemalan Revolution and the United States, 1944–1954',
      year: 1991,
      detail: 'Princeton University Press. ISBN 978-0-691-02556-8',
      note: 'The standard scholarly account, and the strongest archival treatment of what the Árbenz government actually intended.',
    },
    {
      id: 'schlesinger-kinzer-1982',
      kind: 'book',
      author: 'Stephen Schlesinger and Stephen Kinzer',
      title: 'Bitter Fruit: The Story of the American Coup in Guatemala',
      year: 1982,
      detail: 'Doubleday; revised edition Harvard University Press, 2005. ISBN 978-0-674-01930-0',
      note: 'The corporate-capture account, and the source of most popular knowledge of the episode. Strongest on the United Fruit connections.',
    },
    {
      id: 'ohenry-1904',
      kind: 'primary',
      author: 'O. Henry (William Sydney Porter)',
      title: 'Cabbages and Kings',
      year: 1904,
      detail: 'McClure, Phillips & Co.',
      note: 'Where "banana republic" is coined, half a century before the coup the phrase is now attached to.',
    },
  ],
}
