import type { Story } from '../types'

export const vladTepes: Story = {
  slug: 'vlad-tepes',
  title: 'Vlad Țepeș',
  subtitle: 'Dracula was real. He was not a vampire, and the novelist barely knew who he was.',
  hook: 'Everything you know about Dracula came from two sets of people who wanted him destroyed — and from a novelist who found the name in a footnote.',
  era: 'medieval',
  years: [1431, 1476],
  regions: ['Wallachia', 'Ottoman Empire', 'Hungary'],
  nodes: ['vlad-tepes', 'wallachia', 'ottoman-empire', 'dracula-pamphlets', 'dracula-novel'],
  tags: ['legend', 'myth', 'empire', 'propaganda', 'romania', 'ottoman'],
  readingMinutes: 10,
  reviewed: '2026-08-03',
  mood: 'noir',

  reel: [
    { beat: 'hook', punch: true, text: 'Dracula was a real person. He was not a vampire.' },
    { beat: 'hook', text: 'And the man who wrote the novel took almost nothing from him except the name.' },
    { beat: 'worldBefore', kicker: '1400s', text: 'Wallachia. A small country wedged between the Ottoman Empire and the kingdom of Hungary.' },
    { beat: 'worldBefore', text: 'Both want it. Neither can hold it. A prince here lasts about two years.' },
    { beat: 'worldBefore', text: 'His father joins a knightly order. The Order of the Dragon.' },
    { beat: 'worldBefore', text: 'Dragon, in Romanian, is dracul. So the father becomes Vlad Dracul.' },
    { beat: 'worldBefore', punch: true, text: 'Drăculea just means son of the dragon.' },
    { beat: 'problem', kicker: '1442', text: 'To prove his loyalty, his father hands two sons to the Sultan as hostages.' },
    { beat: 'problem', text: 'Vlad is about eleven. His brother Radu is younger.' },
    { beat: 'problem', text: 'They grow up inside the Ottoman court, learning how the empire thinks.' },
    { beat: 'problem', punch: true, text: 'Radu likes it there.' },
    { beat: 'story', kicker: '1447', text: 'At home, the nobles murder Vlad’s father. His older brother is blinded and buried alive.' },
    { beat: 'story', text: 'He invites the noble families to an Easter feast. Most of them never go home.' },
    { beat: 'story', punch: true, mark: 'imbalance', text: 'Hold that thought. Almost everything you have heard about what he did next was written by his enemies.' },
    { beat: 'story', kicker: '1462', text: 'Mehmed II — the sultan who took Constantinople — invades with an army several times his size.' },
    { beat: 'story', text: 'He burns his own crops. Poisons his own wells. Sends the sick into the Ottoman camp.' },
    { beat: 'story', punch: true, text: 'He gets the wrong tent.' },
    { beat: 'story', text: 'When the Ottomans reach his capital, they find a forest of stakes. Thousands of bodies, standing.' },
    { beat: 'story', punch: true, text: 'Mehmed had conquered Constantinople. He turned around and went home.' },
    { beat: 'story', text: 'Vlad loses anyway. The Ottomans hand his throne to Radu — the brother raised beside him.' },
    { beat: 'whyItHappened', text: 'He escapes to Hungary to ask for help. The king imprisons him for twelve years.' },
    { beat: 'whyItHappened', text: 'That king has a problem. He took money for a crusade and never went.' },
    { beat: 'whyItHappened', punch: true, mark: 'echo', text: 'He needs Vlad to be a monster.' },
    { beat: 'consequences', text: 'The printing press is decades old. This turns out to be what it is good at.' },
    { beat: 'consequences', punch: true, mark: 'press', text: 'Pamphlets about the impaler become some of the first bestsellers in Europe.' },
    { beat: 'whyItMatters', kicker: '1897', text: 'Four centuries later, a theatre manager in London needs a name for his vampire.' },
    { beat: 'whyItMatters', text: 'He has been calling him Count Wampyr. In a library book he finds a footnote: Dracula, it says, means devil.' },
    { beat: 'whyItMatters', punch: true, text: 'That footnote is the entire connection. Stoker’s notes say almost nothing else.' },
    { beat: 'whyItMatters', text: 'The prince and the vampire were welded together in 1972, by a bestseller.' },
    { beat: 'whyItMatters', punch: true, text: 'In Romania he was never the monster. He is the one who said no.' },
  ],

  beats: {
    worldBefore: {
      heading: 'The world before',
      paragraphs: [
        'Wallachia in the fifteenth century was a small country in a bad place.',
        'To the south lay the Ottoman Empire, which was in the middle of the most successful century any state had managed in a very long time. To the north lay the kingdom of Hungary, which was determined to stop it. Wallachia sat exactly between them, on the Danube, and belonged to whoever had most recently arrived.',
        'It was not conquered. It was made tributary — which meant it kept its own prince, its own church and its own laws, and in exchange paid an annual sum and sent hostages. The prince himself was elected by the boyars, the landowning nobility, from among an extended and quarrelsome royal family.',
        'This produced exactly the politics you would expect. Between 1418 and 1476 the throne changed hands well over a dozen times. Ruling Wallachia was less a position than an interval.',
        'In 1431, in that world, a Wallachian noble named Vlad was inducted into a knightly order founded by the Holy Roman Emperor to fight the Ottomans: the Order of the Dragon. He began putting the dragon on his coins. People started calling him Vlad Dracul — Vlad the Dragon.',
        'His second son, born around the same year, inherited the nickname in its possessive form. Drăculea. Son of the dragon.',
      ],
      aside: {
        kind: 'caution',
        label: 'Dragon, not devil',
        body: 'In modern Romanian, drac does mean devil. In the fifteenth century the word still carried its older sense, from the Latin draco, and the family took it from an order of Christian knights. The devil reading arrived later — and it is the reading a nineteenth-century novelist happened to find.',
      },
      sourceIds: ['treptow-2000'],
    },

    problem: {
      heading: 'The problem',
      paragraphs: [
        'In 1442 Vlad Dracul was summoned to meet the Sultan and, on arrival, arrested. He was released on a condition that was standard practice and no less brutal for it: he would leave two of his sons behind as guarantees of his loyalty.',
        'Vlad was about eleven. His younger brother Radu was perhaps eight.',
        'They spent their adolescence inside the Ottoman court. This was not a dungeon. Royal hostages were educated — languages, horsemanship, logistics, the Qur’an, the administration of the most sophisticated state in the region. It was an excellent education, delivered under the standing condition that their father’s behaviour determined whether they lived.',
        'The two brothers came out of it as opposites. Radu adapted, converted, and became a favourite of the sultan’s son Mehmed. Vlad did not.',
        'And then, in 1447, the arrangement stopped mattering. Wallachian boyars, backed by the Hungarian regent, killed Vlad’s father. His older brother Mircea, by the account that has come down, was blinded and buried alive.',
        'At which point a young man raised by his family’s enemies, hostage to his family’s other enemies, became a claimant to a throne held by the people who had just murdered his father and brother.',
      ],
      sourceIds: ['treptow-2000', 'chalkokondyles'],
    },

    story: {
      heading: 'The story',
      paragraphs: [
        'Vlad took the throne properly in 1456, aged around twenty-five, and held it for six years. Those six years are the entire basis of his reputation.',
        'He began with the boyars. The traditional account — and the sourcing matters here, so hold it lightly — is that he invited the noble families to an Easter feast, had the older ones impaled, and marched the rest into the mountains to rebuild the fortress at Poenari until their court clothes fell off them. What is not in doubt is that the boyar class of Wallachia was substantially destroyed during his reign, and that he replaced it with men who owed everything to him.',
        'He also stopped paying the Ottoman tribute, and stopped sending the annual quota of boys for the janissary corps.',
        '**In 1462, Mehmed II came for him.** The same Mehmed who had taken Constantinople nine years earlier, ending the Roman Empire, brought an army several times the size of anything Wallachia could field.',
        'Vlad understood exactly what he could not do. He could not win a battle. So he did not offer one.',
        'He emptied and burned his own country ahead of the advance — crops, villages, wells poisoned, livestock driven off. He is reported to have sent people sick with plague and leprosy into the Ottoman camp deliberately. He harried the column continuously and never stood in front of it.',
        'On the night of 17 June 1462 he took the logic to its end and rode into the Ottoman camp itself, in the dark, intending to find and kill the sultan personally. He reached the tents of two viziers instead. The Night Attack failed by roughly the width of a camp.',
        'And then, according to the Greek historian Chalkokondyles, the Ottoman army arrived outside Târgoviște and found a field of impaled bodies, perhaps twenty thousand of them, arranged in ranks. Mehmed — a man not easily impressed by violence — is said to have looked at it, remarked that a man capable of this deserved his country, and withdrawn.',
        'It is the most famous thing Vlad ever did, and it worked.',
        'It also did not save him. Mehmed left behind a candidate the Wallachians could accept, and that candidate was Radu — Vlad’s own brother, raised in the same court, now leading Ottoman troops. The boyars, having watched Vlad govern for six years, went over. Vlad fled north to Hungary to ask his Christian allies for help.',
        'King Matthias Corvinus arrested him and kept him for about twelve years.',
      ],
      aside: {
        kind: 'voice',
        label: 'Chalkokondyles, on Mehmed at Târgoviște',
        body: 'The sultan, on seeing the field of stakes, is reported to have said that a man who could do such things was worthy of more, and that he could not take the country of one who had made such wonderful use of his rule and his subjects.',
        sourceId: 'chalkokondyles',
      },
      sourceIds: ['treptow-2000', 'chalkokondyles', 'pamphlets-1488'],
    },

    whyItHappened: {
      heading: 'Why he became a monster',
      paragraphs: [
        'The impalements were real. The scale is genuinely disputed, and the reason it is disputed is worth understanding, because it is the actual lesson of this story.',
        '**Impalement was not his invention.** It was a recognised judicial punishment across the region, used by the Ottomans and by Hungarians, and it was applied to enemies, criminals and traitors. Vlad’s distinction was scale and consistency, not novelty.',
        '**Terror was a strategy, and it was legible as one.** A ruler with no standing army, no reliable nobility and no depth of territory has very few instruments. Making an example of people is one of them. That is an explanation, not a defence.',
        '**But the man writing it all down had a motive.** After 1462 Vlad was in the custody of Matthias Corvinus, who had accepted substantial funds from the papacy for a crusade against the Ottomans, and had not gone on one. Producing evidence that his Wallachian ally was a psychopath unfit for Christian support was extremely convenient. The earliest atrocity accounts circulate from precisely this quarter, at precisely this time.',
        '**And then the technology changed.** The stories were picked up by German-speaking Saxons in Transylvania, whose merchant towns Vlad had raided and taxed and who therefore hated him on their own account. From 1463 they circulate in manuscript. From the 1480s they are *printed*, in Nuremberg, Bamberg, Lübeck, Augsburg — with woodcuts of a prince dining calmly among the stakes.',
        'The press was a few decades old. These pamphlets were among the first things it made popular across a continent. Europe’s early mass media discovered atrocity content immediately, and it sold.',
        'One check on all this: a Russian account written around 1486, from a different court with different interests, describes the same violence — and reads it as harsh justice by a ruler who hated crime and dishonesty. Same acts. Opposite verdict. Everything depends on who is holding the pen.',
      ],
      sourceIds: ['treptow-2000', 'pamphlets-1488', 'skazanie-1486'],
    },

    consequences: {
      heading: 'What changed',
      paragraphs: [
        'He got his throne back in 1476 and lost it, along with his head, within months.',
      ],
      shortTerm: [
        'Vlad was killed in late 1476 or early 1477, in circumstances that are not clear. His head is reported to have been sent to Mehmed in Constantinople.',
        'Wallachia stayed an Ottoman tributary for another three and a half centuries, which is precisely what he had failed to prevent.',
        'The boyar class he had broken did not recover its former position.',
      ],
      longTerm: [
        'The printed pamphlets kept selling and being reprinted into the sixteenth century, fixing his reputation in German-speaking Europe long after anyone remembered the politics.',
        'In Romanian tradition the opposite figure survived: a severe but just prince who defended the country and hanged thieves, remembered in folk stories rather than pamphlets.',
        'In 1897 Bram Stoker gave the name to a vampire, and the name stopped belonging to the man entirely.',
        'Romanian tourism now runs substantially on a novel about a character its author set in a country he never visited.',
      ],
      unexpected: [
        'The atrocity pamphlets are studied today less as evidence about Vlad than as evidence about print: they are among the earliest examples of mass-produced political propaganda, and they show the mechanism working perfectly on its first outing.',
        'Bran Castle, sold worldwide as Dracula’s castle, has no solid connection to him. The fortress he actually held and rebuilt, Poenari, is a ruin up 1,480 steps and gets a fraction of the visitors.',
        'Under Ceaușescu, Romania promoted Vlad as a national hero and anti-Ottoman patriot — using a fifteenth-century prince to make a twentieth-century point about foreign interference.',
        'The novel’s count is Transylvanian. The real Vlad ruled Wallachia, the neighbouring principality, and raided Transylvania.',
      ],
      sourceIds: ['treptow-2000', 'miller-2000'],
    },

    whyItMatters: {
      heading: 'Why it still matters',
      paragraphs: [
        'The Dracula story is usually told as a piece of trivia: *did you know the vampire was based on a real prince?* The interesting version runs the other way.',
        'Bram Stoker was writing a novel about a Transylvanian vampire he had provisionally named Count Wampyr. While reading in Whitby he came across William Wilkinson’s 1820 account of Wallachia and Moldavia, which mentions a voivode called Dracula and carries a footnote explaining that Dracula means devil in the Wallachian language.',
        'Stoker’s working notes survive. He took the name and that footnote. There is nothing in them about impalement, nothing about the Ottoman wars, nothing about the man’s life. The novel’s count says he is a Székely, which Vlad was not, and describes a family history that is not Vlad’s.',
        'The two were fused in the public mind in 1972, by a bestselling book that argued the connection and became the accepted version. The connection is, in other words, about fifty years old — younger than the moon landing.',
        'Which leaves the thing worth taking away. A man’s reputation was made by his jailer, printed by his commercial rivals, distributed by a new technology that rewarded the most extreme version, and then, four centuries later, permanently attached to a monster he had nothing to do with.',
        'Every stage of that is still running. Only the printing press has been replaced.',
      ],
      sourceIds: ['miller-2000', 'wilkinson-1820', 'mcnally-florescu-1972'],
    },
  },

  timeline: [
    { year: 1408, title: 'The Order of the Dragon is founded', detail: 'Sigismund of Luxembourg creates a knightly order pledged to fight the Ottomans. Vlad’s father joins in 1431 and takes the name Dracul.' },
    { year: 1431, title: 'Vlad III is born', detail: 'Probably at Sighișoara in Transylvania. The date is an estimate.', confidence: 'contested' },
    { year: 1442, title: 'Hostage to the Ottomans', detail: 'Vlad and his younger brother Radu are left at the Ottoman court as guarantees of their father’s loyalty.', pivotal: true },
    { year: 1447, title: 'His father and brother are killed', detail: 'Boyars backed by the Hungarian regent murder Vlad Dracul. His elder brother Mircea is reported blinded and buried alive.', pivotal: true },
    { year: 1453, title: 'Constantinople falls', detail: 'Mehmed II takes the city at twenty-one. The Ottoman Empire becomes the dominant power in the region.', pivotal: true },
    { year: 1456, title: 'Vlad takes the throne', detail: 'His second and longest reign begins. It lasts six years and produces the entire legend.', pivotal: true },
    { year: 1459, title: 'The tribute stops', detail: 'Vlad refuses the annual payment and the levy of boys for the janissary corps.' },
    { year: 1462, date: '1462-06-17', title: 'The Night Attack', detail: 'Vlad rides into the Ottoman camp in darkness intending to kill Mehmed II personally, and reaches the wrong tents.', pivotal: true },
    { year: 1462, title: 'The forest of the impaled', detail: 'Chalkokondyles reports the Ottoman army finding a field of impaled bodies outside Târgoviște, and Mehmed withdrawing.', confidence: 'contested', pivotal: true },
    { year: 1462, title: 'Radu takes the throne', detail: 'The Ottomans install Vlad’s younger brother, raised beside him in the same court, as prince of Wallachia.' },
    { year: 1463, title: 'The stories begin circulating', detail: 'Atrocity accounts spread in manuscript from the Hungarian court and Transylvanian Saxon towns while Vlad is in custody.', pivotal: true },
    { year: 1476, title: 'A third reign, and death', detail: 'Vlad regains the throne and is killed within months. His head is reported sent to Mehmed in Constantinople.' },
    { year: 1488, title: 'The pamphlets are printed', detail: 'Printed editions appear in Nuremberg and elsewhere, with woodcuts, and are reprinted for decades. Among Europe’s first popular bestsellers.', pivotal: true },
    { year: 1820, title: 'A footnote is written', detail: 'William Wilkinson’s account of Wallachia mentions a voivode named Dracula and notes that the word means devil.' },
    { year: 1897, title: 'Stoker publishes Dracula', detail: 'The vampire had been called Count Wampyr in the drafts. The name is taken from Wilkinson; almost nothing else is.', pivotal: true },
    { year: 1972, title: 'The two are fused', detail: 'In Search of Dracula argues the novel was based on Vlad III, becomes a bestseller, and creates the version everyone now believes.', pivotal: true },
  ],

  causeEffect: [
    { cause: 'Wallachia sits between two empires', effect: 'Its princes are installed and removed constantly', because: 'Whoever is stronger that decade picks the candidate, and the boyars follow the stronger side.' },
    { cause: 'Vlad’s father needs to prove loyalty', effect: 'Vlad spends his adolescence in Ottoman custody', because: 'Royal hostages were the standard collateral in a tributary relationship.' },
    { cause: 'His father and brother are murdered by boyars', effect: 'He destroys the boyar class on taking power', because: 'The nobility that elected princes was the same nobility that killed them, and he removed it as a factor.' },
    { cause: 'He stops paying tribute', effect: 'Mehmed II invades in 1462', because: 'A tributary that stops paying and keeps its boys is a precedent the empire cannot allow.' },
    { cause: 'He cannot win a pitched battle', effect: 'Scorched earth, disease and a night raid', because: 'Terror and denial were the only instruments available to a ruler with no army and no depth.' },
    { cause: 'He asks Hungary for help', effect: 'Twelve years in a Hungarian prison', because: 'Matthias Corvinus had crusade money he had not spent on crusading, and needed the failure to be someone else’s.' },
    { cause: 'His jailer and his commercial rivals write the accounts', effect: 'A monster is documented in detail', because: 'Both had a direct interest in the worst possible version, and no one had an interest in checking it.' },
    { cause: 'The printing press exists by the 1480s', effect: 'The worst version becomes the permanent one', because: 'Print rewarded the most sensational telling, and reprinting made it the only one in circulation.' },
  ],

  myths: [
    {
      myth: 'Bram Stoker based Count Dracula on Vlad III.',
      reality: 'Stoker’s surviving working notes show he took the name and a single footnote — Wilkinson’s 1820 remark that Dracula means devil — and essentially nothing else. His villain was called Count Wampyr until then. The novel’s count is a Székely with a history that is not Vlad’s.',
      whyItPersists: 'A 1972 bestseller, In Search of Dracula, argued the connection so effectively that it became the received version within a decade. The idea is younger than most people assume.',
      sourceIds: ['miller-2000', 'wilkinson-1820', 'mcnally-florescu-1972'],
    },
    {
      myth: 'Bran Castle was Dracula’s castle.',
      reality: 'There is no good evidence Vlad ever held it. The fortress he actually rebuilt and used was Poenari, now a ruin at the top of 1,480 steps. Bran’s association is a twentieth-century tourism creation, helped by its looking the part.',
      whyItPersists: 'It photographs extremely well, it is accessible, and no one selling tickets has an incentive to correct it.',
      sourceIds: ['treptow-2000'],
    },
    {
      myth: 'Vlad invented impalement, or was uniquely bloodthirsty for his time.',
      reality: 'Impalement was an established punishment used by the Ottomans and in Hungary. The fifteenth century was violent at the top end everywhere. His reputation rests on scale and on who wrote it down, not on inventing a method.',
      whyItPersists: 'The nickname Țepeș — the Impaler — is posthumous and vivid, and vividness travels.',
      sourceIds: ['treptow-2000', 'pamphlets-1488'],
    },
    {
      myth: 'Dracula means devil, so the name was always sinister.',
      reality: 'It comes from the Order of the Dragon, a Christian knightly order his father joined in 1431. Dracul meant dragon. The devil sense of the word became dominant later — and it is that later sense a nineteenth-century footnote recorded.',
      whyItPersists: 'The modern Romanian word does mean devil, so the mistranslation is a very easy one to keep making.',
      sourceIds: ['treptow-2000', 'wilkinson-1820'],
    },
  ],

  disagreements: [
    {
      question: 'How many people did he actually kill?',
      positions: [
        { view: 'The German pamphlet figures — tens of thousands, including twenty thousand at Târgoviște — are broadly indicative of the scale.', heldBy: 'The traditional reading, following the printed accounts and Chalkokondyles', sourceId: 'chalkokondyles' },
        { view: 'The figures come from hostile sources with clear motives and cannot bear that weight. The killing was real; the arithmetic is propaganda.', heldBy: 'Most modern scholarship on the period', sourceId: 'treptow-2000' },
      ],
      atlasPosition: 'The atlas states that he used impalement extensively and as policy, which is not disputed, and treats the specific totals as unverifiable. It does not repeat the numbers as fact.',
    },
    {
      question: 'Was he a defender of his country or a tyrant?',
      positions: [
        { view: 'A tyrant. The atrocity accounts, taken together across German, Hungarian and some Ottoman sources, describe sustained cruelty against his own subjects.', heldBy: 'The German pamphlet tradition and its inheritors', sourceId: 'pamphlets-1488' },
        { view: 'A harsh ruler doing what the position required, and the only Wallachian prince to seriously resist Ottoman expansion.', heldBy: 'Romanian national historiography, and a Russian account of 1486 that reads the same acts as justice', sourceId: 'skazanie-1486' },
      ],
      atlasPosition: 'The atlas does not pick. It reports what he did, and who was writing — because the disagreement here is not really about the facts, it is about which century’s politics is doing the judging.',
    },
  ],

  didYouKnow: [
    'Stoker’s villain was called Count Wampyr until he found a better name in a library book in Whitby.',
    'The Ottomans educated Vlad. He spoke their language, knew their army, and fought them with what they taught him.',
    'The brother who took his throne, backed by Ottoman troops, had grown up beside him in the same captivity.',
    'A Russian account written around 1486 describes the same acts as harsh justice, not tyranny. Same evidence, opposite verdict.',
    'The atrocity pamphlets are now studied mainly as evidence about early printing, not as evidence about Vlad.',
    'Bran Castle, sold worldwide as Dracula’s castle, has no solid connection to him at all.',
    'The link between the prince and the vampire was popularised in 1972 — it is younger than the moon landing.',
  ],

  lenses: [
    {
      id: 'one-minute',
      label: 'In one minute',
      kind: 'length',
      paragraphs: [
        'Vlad III ruled Wallachia, a small tributary state between the Ottoman Empire and Hungary. His father had joined the Order of the Dragon and taken the name Dracul; Drăculea means son of the dragon.',
        'Handed to the Ottomans as a child hostage, he returned to take the throne in 1456, destroyed the nobility that had murdered his father, stopped paying tribute, and in 1462 faced an invasion by Mehmed II. He could not win a battle, so he burned his own country, spread disease in the Ottoman camp, attempted to assassinate the sultan at night, and left a field of impaled bodies outside his capital. Mehmed withdrew. Vlad lost the throne anyway, to his own brother.',
        'He fled to Hungary and was imprisoned there for twelve years by a king who had taken crusade funds and not crusaded — and who needed his ally to be a monster. The atrocity stories that followed were printed from the 1480s and became some of Europe’s first bestsellers.',
        'In 1897 Bram Stoker took the name from a footnote in a library book. Almost nothing else. The vampire and the prince were fused together by a bestseller in 1972.',
      ],
    },
    {
      id: 'age-16',
      label: 'Explain like I’m 16',
      kind: 'age',
      paragraphs: [
        'Wallachia was a tributary state, not an occupied one: it kept its prince, its church and its law, and paid an annual tribute plus hostages. That arrangement is the key to everything — it made the prince simultaneously an Ottoman client and a Hungarian ally, and neither could quite trust him.',
        'Vlad’s strategy in 1462 is a textbook asymmetric campaign. Refuse decisive battle, deny the enemy supply by destroying your own territory, degrade them with disease, harass continuously, and attempt decapitation of the command. The impaled field at Târgoviște belongs to the same logic — it was a message calculated for a specific audience.',
        'The reputational history is the more interesting half. His accounts come from two sources with clear motives: Matthias Corvinus, who was holding him and had misappropriated crusade funding, and Transylvanian Saxon merchants whose towns he had raided. Both fed a printing industry that was new, hungry and unregulated.',
        'Compare a Russian narrative from around 1486, produced in a court with no stake in either grievance. It describes comparable acts and frames them as severity in the service of order. The divergence tells you the sources are recording judgement, not just events.',
      ],
    },
    {
      id: 'scholar',
      label: 'University level',
      kind: 'age',
      paragraphs: [
        'The historiography splits cleanly along the sources. The German Geschichte tradition, transmitted through the Saxon towns and printed from the 1480s, is now generally read as a politically motivated corpus rather than a documentary one; Treptow’s biography is the standard corrective, situating the reign within Wallachian factional politics and the Hungarian-Ottoman frontier rather than within a psychology of cruelty.',
        'Chalkokondyles remains the most valuable non-partisan witness for 1462, and his account of the Târgoviște field and Mehmed’s withdrawal is the basis for most reconstructions, with the usual caveats about Byzantine number conventions.',
        'The Slavonic Skazanie of c. 1486 is the essential control text: substantially overlapping content, inverted moral framing. Read against the German pamphlets it demonstrates that the divergence between "tyrant" and "just ruler" is interpretive rather than evidentiary.',
        'On the literary afterlife, Miller’s source-critical work on Stoker’s Rosenbach notes settled the question: the borrowing is onomastic, mediated by Wilkinson (1820), with no demonstrable knowledge of the historical reign. McNally and Florescu (1972) should be cited as the origin of the conflation, not as evidence for it — a rare case where a work of popular history can be dated as the point a myth entered general circulation.',
      ],
    },
    {
      id: 'propaganda',
      label: 'How propaganda works',
      kind: 'angle',
      paragraphs: [
        'This is a complete case study, and every stage of it is still in service.',
        '**A motivated author.** Matthias Corvinus had taken papal money for a crusade he did not fight. A monstrous ally converts a financial scandal into a moral judgement. He did not need to invent much — he needed to select and amplify.',
        '**An audience that already agreed.** The Transylvanian Saxon towns had been raided and taxed by Vlad. They were not persuaded; they were confirmed. Material spreads fastest through people who already want it to be true.',
        '**A distribution technology with its own incentives.** Print in the 1480s was new, cheap and commercial. The versions that sold were the extreme ones, and reprinting selected for extremity. There was no correction mechanism because there was no market for a correction.',
        '**And time.** After a century the pamphlets were the only surviving account in that language, so they stopped looking like claims and started looking like the record. That is the step people miss: propaganda does not have to win an argument, it only has to outlast the alternative.',
      ],
    },
    {
      id: 'from-romania',
      label: 'From the Romanian side',
      kind: 'contrast',
      paragraphs: [
        'From Bucharest this is not a horror story. It is the story of the one prince who refused.',
        'Wallachia paid tribute and sent its sons for a hundred years before Vlad and for three hundred and fifty after him. In the middle of that stands six years in which a ruler stopped paying, stopped sending boys to the janissary corps, and made the most powerful army in Europe turn around.',
        'The folk tradition remembers a prince obsessed with order — the stories are about thieves who did not steal and merchants who left gold cups unattended in public squares, because the punishment was certain. Severity, in a country where the previous prince had been murdered by his own nobles, was not incidental to good government. It was the offer.',
        'The discomfort is real, and Romanians argue about it too. But it is worth noticing that the version sold to tourists — the vampire, the wrong castle, the foreign novel — replaced a national memory with a monster invented somewhere else. That is the second time it has happened to him.',
      ],
    },
  ],

  beforeAfter: {
    label: 'The man and the legend',
    before: {
      title: 'What the record supports',
      points: [
        'Prince of Wallachia, three reigns, about seven years in total',
        'Raised as an Ottoman hostage; fluent in their language and methods',
        'Used impalement extensively and deliberately, as policy',
        'Stopped the tribute and forced Mehmed II to withdraw in 1462',
        'Lost his throne to his own brother, and died in about 1476',
      ],
    },
    after: {
      title: 'What the legend added',
      points: [
        'A vampire, four hundred years later, in a novel he is not in',
        'A castle at Bran he almost certainly never held',
        'Precise casualty totals sourced from his jailer and his rivals',
        'Drinking blood — an accusation absent from the contemporary accounts',
        'A surname meaning devil, rather than dragon',
      ],
    },
  },

  whatIf: [
    {
      question: 'What if the printing press had arrived fifty years later?',
      reasoning: 'The atrocity accounts would have stayed in manuscript, circulating among a few hundred readers in Hungary and Transylvania, and would most likely have faded with the politics that produced them. Vlad would be a regional figure known to specialists, like a dozen contemporaries who did comparable things.',
      constraint: 'The stories existed before print and were already doing their political work. Print did not create the account; it made it permanent and continental. He would be less famous, not differently remembered.',
    },
    {
      question: 'What if Stoker had kept the name Count Wampyr?',
      reasoning: 'The novel would probably have succeeded anyway — the vampire it invented is doing the work, not the name. And Vlad III would be left in the fifteenth century where he belongs, argued over by historians of the Ottoman frontier.',
      constraint: 'Something else would likely have collided with him eventually. The pamphlets had already made him the most famous cruel prince in Europe, which is exactly the shelf a Gothic novelist browses.',
    },
  ],

  quiz: [
    {
      question: 'Where does the name "Dracula" come from?',
      options: [
        'A Wallachian word for vampire',
        'The Order of the Dragon, which his father joined',
        'A title granted by the Ottoman sultan',
        'The name of his castle',
      ],
      answerIndex: 1,
      explains: 'Dracul meant dragon, from the knightly order his father joined in 1431. Drăculea is the possessive: son of the dragon. The devil sense of the word came later.',
    },
    {
      question: 'How did Vlad make Mehmed II withdraw in 1462?',
      options: [
        'He won a pitched battle outside Târgoviște',
        'He paid a large tribute',
        'He denied the army supply, spread disease, and left a field of impaled bodies on their route',
        'Hungary intervened with an army',
      ],
      answerIndex: 2,
      explains: 'He never offered a battle he could not win. He burned his own country ahead of the advance, harassed the column, attempted to assassinate the sultan at night, and left a message outside his capital.',
    },
    {
      question: 'Who took Vlad’s throne after 1462?',
      options: [
        'Matthias Corvinus of Hungary',
        'Mehmed II directly',
        'His younger brother Radu, backed by the Ottomans',
        'The boyar council',
      ],
      answerIndex: 2,
      explains: 'Radu had been hostage in the same Ottoman court as a boy, stayed, converted and rose. The Ottomans installed him against his brother.',
    },
    {
      question: 'What did Bram Stoker actually take from Vlad III?',
      options: [
        'His biography, his castle and his methods',
        'The name, and a footnote saying it meant devil',
        'Nothing — the resemblance is a coincidence',
        'His coat of arms and family history',
      ],
      answerIndex: 1,
      explains: 'Stoker’s working notes survive. He found the name in Wilkinson’s 1820 book, with a footnote glossing it as devil, and had been calling his villain Count Wampyr until then.',
    },
  ],

  sources: [
    {
      id: 'chalkokondyles',
      kind: 'primary',
      author: 'Laonikos Chalkokondyles',
      title: 'The Histories',
      year: 1465,
      detail: 'Greek; composed c. 1460s. Dumbarton Oaks Medieval Library edition, 2014',
      note: 'The most valuable near-contemporary account of the 1462 campaign, including the field of stakes and Mehmed’s withdrawal. Date is approximate.',
    },
    {
      id: 'pamphlets-1488',
      kind: 'primary',
      author: 'Anonymous German pamphlets',
      title: 'Von einem wütrich der hieß Trakle waida von der Walachei',
      year: 1488,
      detail: 'Printed at Nuremberg and elsewhere; manuscript versions circulate from 1463',
      note: 'The atrocity literature. Cited here as evidence of how the reputation was made, not as a reliable record of what happened.',
    },
    {
      id: 'skazanie-1486',
      kind: 'primary',
      author: 'Fyodor Kuritsyn (attributed)',
      title: 'Skazanie o Drakule voevode',
      year: 1486,
      detail: 'Church Slavonic; Russian court manuscript tradition',
      note: 'Describes much the same violence and reads it as severity in the service of justice. The essential control on the German account.',
    },
    {
      id: 'wilkinson-1820',
      kind: 'primary',
      author: 'William Wilkinson',
      title: 'An Account of the Principalities of Wallachia and Moldavia',
      year: 1820,
      detail: 'Longman, Hurst, Rees, Orme and Brown, London',
      note: 'The book Stoker read. Its footnote glossing "Dracula" as devil is the entire documented link between the prince and the novel.',
    },
    {
      id: 'treptow-2000',
      kind: 'book',
      author: 'Kurt W. Treptow',
      title: 'Vlad III Dracula: The Life and Times of the Historical Dracula',
      year: 2000,
      detail: 'Center for Romanian Studies. ISBN 978-973-98392-2-8',
      note: 'The standard scholarly biography, and the clearest account of how the sources were produced.',
    },
    {
      id: 'miller-2000',
      kind: 'book',
      author: 'Elizabeth Miller',
      title: 'Dracula: Sense & Nonsense',
      year: 2000,
      detail: 'Desert Island Books. ISBN 978-1-874287-24-6',
      note: 'Source-critical work on Stoker’s surviving notes. Settles what he did and did not take from the historical Vlad.',
    },
    {
      id: 'mcnally-florescu-1972',
      kind: 'book',
      author: 'Raymond T. McNally and Radu Florescu',
      title: 'In Search of Dracula',
      year: 1972,
      detail: 'New York Graphic Society',
      note: 'Cited as the origin of the prince-and-vampire conflation, not as support for it. This is the book that made the myth general.',
    },
  ],
}
